### ISSUE TITLE
How send telegram sticker from bot?

### ISSUE THREAD

**Issue by GermaN-st** [guidone/node-red-contrib-chatbot#101]
Hello !
Is it planned to develop a node for sending **stickers**. For telegram ?
For me, it is very important that the bot can send stickers (Created by me or from the standard set of telegram).
Perhaps this can already be done? Prompt please then how?

P.S. And thank you for the great solution for developing bots ;)

**Comment by guidone** [comment]
Thanks @GermaN-st !

Yes sending the sticker should not be complicated, I'll add to the roadmap

Thanks for the feedback

**Comment by guidone** [comment]
added in 0.8.3

Thanks for the feedback

**Comment by GermaN-st** [comment]
@guidone 
I checked the sending stickers. This works great. Thank you.
