### ISSUE TITLE
How to use API.AI node in new version of RedBot? 

### ISSUE THREAD

**Issue by fpsimonee** [guidone/node-red-contrib-chatbot#103]
Hi, 
I'm update the redbot plugin for new version, 0.8.1, but I put the access token in the field access but it's not work. In my console I this message and on facebook nothing apear.

the Message is: 
"TypeError: Cannot read property 'apiAi' of null"

![screenshot from 2017-08-07 11-52-06](https://user-images.githubusercontent.com/11202288/29032176-dd93a76c-7b66-11e7-87d5-50612d18a3f8.png)

Anything change in configuration of this node? How it Works ? 
Thanks.

**Comment by guidone** [comment]
The configuration panel for API was completely missing, I've fixed it for now, I think this node need a little refactoring.
Can you check it in 0.8.2 and give some feedback if you make it work?

Thanks for the feedback

**Comment by fpsimonee** [comment]
@guidone I'm installed the version 0.8.2 and works normally, thanks man.
