### ISSUE TITLE
Enhancement: Please add a CHANGELOG.md to your repo

### ISSUE THREAD

**Issue by TotallyInformation** [guidone/node-red-contrib-chatbot#106]
Hi. It is really hard to know what has changed from one version to another.

**Comment by guidone** [comment]
it's in the wiki

https://github.com/guidone/node-red-contrib-chatbot/wiki/Changelog

I can modify the build task to replicate this also in CHANGELOG.md

**Comment by TotallyInformation** [comment]
Most kind, thank you. It is hard, when consuming so many libraries and modules, to be able to keep track of change information so this is really useful.

**Comment by guidone** [comment]
👍
