### ISSUE TITLE
No Response from Facebook on heroku

### ISSUE THREAD

**Issue by buddhikapp** [guidone/node-red-contrib-chatbot#110]
I have the same issue that was raised earlier few time in this section. I don't get any response from Facebook. I can subscribe to webook and I do get console log with POST url as /redbot/facebook/. Nothing on debug node. I do get debug messages when trying /test and /_status.
Everything is working fine with Telegram.
Can anyone help me please. Trying to get this working for 2 days now.

**Comment by guidone** [comment]
@buddhikapp most of the people have this problem using a node-red wrapper for Heroku that does not include the body-parser middleware in Express, check this, it should solve the problem
