### ISSUE TITLE
Support Markdown and HTML tags in keyboards nodes (telegram).

### ISSUE THREAD

**Issue by GermaN-st** [guidone/node-red-contrib-chatbot#111]
Hello.

It is planned to do support Markdown and HTML in the text to be sent to the chatbot-inline-buttons (built-in telegram keypad) and chatbot-ask (telegram keypad) nodes?

Now the tag support works only in the text node(chatbot-message).

It is very necessary to send for example buttons and text, in which you need to make part of the text bold. Now, if you specify in the message for example tags \<b> Example text \</b> then in the same form it will be displayed in telegram "\<b> Example text \</b>". Tags does not parse(

If you create a text message in the function node (ex: msg.payload="\<b>sample text\</b>") before the button node and there indicate {{payload}} in message section, then text will also be displayed with unrecognized tags (

Tell me whether it is planned to implement this functionality in keyboard nodes and inline keyboards as well as in the "Text" node, or can there be a way how this can be done now?

Thank you.

**Comment by guidone** [comment]
I can add to the roadmap, I just need to find a consistent way to add it to the node interfaces.

**Comment by guidone** [comment]
Seems that the markdown support is a property common to different nodes, so instead adding a flag to each node (like messages), this should be moved to the telegram sender node, becoming a general property for all messages sent to the particular telegram node.

**Comment by guidone** [comment]
What do you think? (Sorry the mobile client for git keep sending unfinished messages)

**Comment by GermaN-st** [comment]
It would be cool and comfortable. You can specify tags anywhere, in function, in keyboard nodes, etc. And their parsing goes at the very end in the sending node. Great idea !

**Comment by guidone** [comment]
I'm afraid html and markdown are not supported in inline buttons and keyboards

<img width="769" alt="schermata 2017-08-28 alle 20 27 37" src="https://user-images.githubusercontent.com/502519/29787495-6c8a5d2a-8c2f-11e7-8742-c9373bdada13.png">

the _sendMessage_ methods supports  the `pare_mode` but only works for the text context and not the buttons.

**Comment by GermaN-st** [comment]
Hello @guidone 
I probably did not correctly explain. I mean support html not in the text of the button, but in the message that goes along with the buttons. On the screenshot noted in which message I want to support html

![11](https://user-images.githubusercontent.com/30233260/29790803-94394d9a-8c43-11e7-9b3e-dc29bf5250ee.png)
![222](https://user-images.githubusercontent.com/30233260/29790804-9454a37e-8c43-11e7-9e23-7934da2f0526.png)

I hope now explained)
If you watch your screenshot, then support the tags like you have in the message "the button" and the button is made in bold. 

Thank you.

**Comment by guidone** [comment]
Ok, this is done, five me a day or two to fix some tests and it's ready

**Comment by GermaN-st** [comment]
Thank you very much. I am waiting... ;)

**Comment by guidone** [comment]
@GermaN-st merged on master, thanks for the feedback
