### ISSUE TITLE
How to send a Value to Generic Template and List Template

### ISSUE THREAD

**Issue by fpsimonee** [guidone/node-red-contrib-chatbot#114]
Hi, I'm trying to send a value from api to generic template for render a image, my image is in s3 bucket and I'm call an API to send a link for my image.

In node red, I'm debug this request and I'm get the link but, if I set the ImageURL field with the msg.payload.myvariable, in console a see one error. This error, told me that my url is not valid. I debug the node and found in console the object was send for the sender node. In the payload for generic template, the value that was passed, don't  retrieving the value for previous payload, the call to my API. 

My configuration is: 

![image](https://user-images.githubusercontent.com/11202288/30130150-a52345fc-931e-11e7-92f4-0209927440ac.png)

the error: 
![image](https://user-images.githubusercontent.com/11202288/30130744-a0422402-9320-11e7-952d-7b2b3001f8e4.png)

thanks!!

**Comment by guidone** [comment]
Hi @fpsimonee `{{msg.payload[0].attributes.url}}` is not a valid URL for generic template, templating is not supported in these fields.
You can leave the the elements field blank in the generic template and send them from the upstream node (where I guess the S3 is available in some variable)

```
msg.payload.elements = [
  {
     title: 'Teste',
     subtitle: null,
     imageUrl: 'http://my-s3-url',
     buttons: []
  }
];
//...
return msg;
```

**Comment by fpsimonee** [comment]
Hi @guidone, I test your solution and Works. Thanks man.

**Comment by guidone** [comment]
👍
