### ISSUE TITLE
Hide keyboard flag in Telegram Out node. 

### ISSUE THREAD

**Issue by GermaN-st** [guidone/node-red-contrib-chatbot#116]
Hello @guidone .

It is often necessary after sending the keyboard and receiving the user's response, immediately hide it, since it is no longer needed.
Now, in order to hide the keyboard, after the user's response, I call the function node function, which sends a request to the telegram node and hides the keyboard. These are additional nodes on the flow.

Is it possible to simplify hiding the keyboard? Make the flag in the node of the telegram sender (with flag track ) after the user clicks the button. After sending the keyboard to the user and getting a response from him (button is pressed), we immediately hide the keyboard. It would be simple and convenient to not make additional nodes. And specify the hiding of the keyboard with one flag in the node.

How I hide the keyboard now:
![222](https://user-images.githubusercontent.com/30233260/30269189-b7ba915e-96f0-11e7-8249-f511b1281733.PNG)
![1111](https://user-images.githubusercontent.com/30233260/30269190-b7bb231c-96f0-11e7-8b20-c5d182f75a01.PNG)

**Comment by guidone** [comment]
@GermaN-st I understand, that will be useful, I'll fix it
