### ISSUE TITLE
Can't send image to telegram

### ISSUE THREAD

**Issue by JeffrySteegmans** [guidone/node-red-contrib-chatbot#119]
I'm trying to send a photo to telegram, however I always get the following error:

**Error: ETELEGRAM: 400 Bad Request: there is no photo in the request**

My flow looks like:
![image](https://user-images.githubusercontent.com/17906736/31266717-67a6fea8-aa75-11e7-8d6c-1d7f8e5b214a.png)

The code of my flow is:
[{"id":"a198dab0.466488","type":"debug","z":"181aaf5f.759b41","name":"","active":true,"console":"false","complete":"true","x":830,"y":760,"wires":[]},{"id":"31287c82.039dd4","type":"chatbot-telegram-receive","z":"181aaf5f.759b41","bot":"6fb93894.5b91f8","x":150,"y":840,"wires":[["f5d7316.6b63ed"]]},{"id":"f5d7316.6b63ed","type":"chatbot-command","z":"181aaf5f.759b41","name":"","command":"/snapshot","x":360,"y":840,"wires":[["16fc8b97.4f1b34"]]},{"id":"16fc8b97.4f1b34","type":"http request","z":"181aaf5f.759b41","name":"test image","method":"GET","ret":"bin","url":"http://wp.patheos.com.s3.amazonaws.com/blogs/faithwalkers/files/2013/03/bigstock-Test-word-on-white-keyboard-27134336.jpg","tls":"","x":530,"y":840,"wires":[["af984c54.884"]]},{"id":"af984c54.884","type":"chatbot-image","z":"181aaf5f.759b41","name":"","filename":"","image":"","caption":"","x":700,"y":840,"wires":[["53cb98c5.19e1d8","a198dab0.466488"]]},{"id":"53cb98c5.19e1d8","type":"chatbot-telegram-send","z":"181aaf5f.759b41","bot":"6fb93894.5b91f8","track":false,"parseMode":"HTML","outputs":0,"x":970,"y":840,"wires":[]},{"id":"6fb93894.5b91f8","type":"chatbot-telegram-node","z":"","botname":"PoortKelder_bot","usernames":"JeffrySteegmans","polling":"200","log":""}]

Am I doing something wrong? or is something changed in the Telegram API?

**Comment by JeffrySteegmans** [comment]
PS: msg printed by debug node:

`{"payload":{"type":"photo","content":{"type":"Buffer","data":[255,216,255,224,0,16,74,70,73,70,0,1,1,0,0,1,0,1,0,0,255,219,0,67,0,8,6,6,7,6,5,8,7,7,7,9,9,8,10,12,20,13,12,11,11,12,25,18,19,15,20,29,26,31,30,29,26,28,28,32,36,46,39,32,34,44,35,28,28,40,55,41,44,48,49,52,52,52,31,39,57,61,56,50,60,46,51,52,50,255,219,0,67,1,9,9,9,12,11,12,24,13,13,24,50,33,28,33,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,255,192,0,17,8,2,208,5,0,3,1,34,0,2,17,1,3,17,1,255,196,0,31,0,0,1,5,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,255,196,0,181,16,0,2,1,3,3,2,4,3,5,5,4,4,0,0,1,125,1,2,3,0,4,17,5,18,33,49,65,6,19,81,97,7,34,113,20,50,129,145,161,8,35,66,177,193,21,82,209,240,36,51,98,114,130,9,10,22,23,24,25,26,37,38,39,40,41,42,52,53,54,55,56,57,58,67,68,69,70,71,72,73,74,83,84,85,86,87,88,89,90,99,100,101,102,103,104,105,106,115,116,117,118,119,120,121,122,131,132,133,134,135,136,137,138,146,147,148,149,150,151,152,153,154,162,163,164,165,166,167,168,169,170,178,179,180,181,182,183,184,185,186,194,195,196,197,198,199,200,201,202,210,211,212,213,214,215,216,217,218,225,226,227,228,229,230,231,232,233,234,241,242,243,244,245,246,247,248,249,250,255,196,0,31,1,0,3,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,2,3,4,5,6,7,8,9,10,11,255,196,0,181,17,0,2,1,2,4,4,3,4,7,5,4,4,0,1,2,119,0,1,2,3,17,4,5,33,49,6,18,65,81,7,97,113,19,34,50,129,8,20,66,145,161,177,193,9,35,51,82,240,21,98,114,209,10,22,36,52,225,37,241,23,24,25,26,38,39,40,41,42,53,54,55,56,57,58,67,68,69,70,71,72,73,74,83,84,85,86,87,88,89,90,99,100,101,102,103,104,105,106,115,116,117,118,119,120,121,122,130,131,132,133,134,135,136,137,138,146,147,148,149,150,151,152,153,154,162,163,164,165,166,167,168,169,170,178,179,180,181,182,183,184,185,186,194,195,196,197,198,199,200,201,202,210,211,212,213,214,215,216,217,218,226,227,228,229,230,231,232,233,234,242,243,244,245,246,247,248,249,250,255,218,0,12,3,1,0,2,17,3,17,0,63,0,194,208,173,44,32,248,43,226,235,136,53,33,61,228,226,203,237,54,162,22,95,179,109,184,33,62,115,195,238,28,241,211,161,170,30,8,31,217,190,22,241,71,138,45,127,119,171,233,63,100,251,13,207,95,43,205,118,142,79,148,229,91,42,113,243,3,142,216,60,213,239,9,73,225,24,124,3,172,233,122,151,138,69,133,230,179,228,111,139,251,58,89,69,183,147,43,48,229,120,125,195,7,168,198,123,213,31,135,30,50,255,0,132,115,251,75,79,55,223,217,127,218,94,87,252,77,124,159,63,236,190,94,246,255,0,85,180,239,221,187,111,108,103,60,214,70,218,234,117,126,37,181,191,213,60,3,174,220,120,187,82,251,119,137,52,111,179,237,180,54,235,31,246,119,157,40,31,126,63,146,95,49,2,158,251,113,216,230,185,95,135,132,232,167,83,241,182,4,195,195,254,87,250,24,249,126,209,231,239,139,239,243,183,110,115,247,78,122,113,214,150,242,251,64,240,215,133,53,109,19,69,214,127,183,127,182,188,159,58,127,178,189,175,217,124,151,222,191,43,231,126,236,176,224,140,109,239,154,207,185,214,116,251,47,135,246,26,102,141,62,203,221,71,204,254,221,143,99,31,51,203,151,117,191,44,48,48,9,251,132,103,189,1,211,94,166,135,130,113,166,248,87,197,30,38,180,62,86,175,164,27,79,177,92,159,155,202,243,93,163,147,229,63,43,101,78,57,7,29,185,174,175,196,214,183,250,175,128,117,203,143,23,106,63,110,241,38,141,246,125,182,158,66,199,253,157,231,74,7,223,143,9,47,152,129,79,125,184,199,7,53,201,252,59,241,129,240]},"filename":"","caption":null,"chatId":425552882,"messageId":60,"inbound":false},"originalMessage":{"message_id":60,"from":{"id":425552882,"is_bot":false,"first_name":"Jeffry","last_name":"Steegmans","username":"JeffrySteegmans","language_code":"nl"},"chat":{"id":425552882,"first_name":"Jeffry","last_name":"Steegmans","username":"JeffrySteegmans","type":"private"},"date":1507276446,"text":"/snapshot","entities":[{"offset":0,"length":9,"type":"bot_command"}],"transport":"telegram"},"_msgid":"8c2ee0dc.e3ad","statusCode":200,"headers":{"connection":"close","server":"IP Webcam Server 0.4","cache-control":"no-store, no-cache, must-revalidate, pre-check=0, post-check=0, max-age=0","pragma":"no-cache","expires":"-1","access-control-allow-origin":"*","content-type":"image/jpeg","content-length":"100957","x-node-red-request-node":"59a0d09a"},"responseUrl":"http://192.168.0.7:8080/shot.jpg"}`

**Comment by guidone** [comment]
Hi @JeffrySteegmans it works on my machine

<img width="630" alt="schermata 2017-11-25 alle 09 03 33" src="https://user-images.githubusercontent.com/502519/33228605-988ea75c-d1bf-11e7-9513-08852168be72.png">

**Comment by JeffrySteegmans** [comment]
Zeer vreemd. Ik heb de bot veranderd en nu werkt het wel.
Bedankt om dit te testen.

**Comment by guidone** [comment]
Good! 🖖

**Comment by CurbYourStrangeness** [comment]
I've imported JeffrySteegmans's original code, I have node-red-contrib-telegrambot,  node-red-contrib-telegrambot-plus, node-red-contrib-telegrambot-message, and node-red-contrib-telegrambot-home installed and the IDE is telling me there are unknown nodes.

What setups are you using?
