### ISSUE TITLE
Сontext storage node

### ISSUE THREAD

**Issue by GermaN-st** [guidone/node-red-contrib-chatbot#121]
Hello, @guidone 

Is it possible to make a separate node to store the context? 
When using a messenger for which there is no node, we can not use context store system. For example, I use api Viber. But now it is very inconvenient, since there are no nodes to work with it (Send and Receive). But the context is very necessary in the development of flows. 
As I see it. A separate node is a context. Which is put after the node with a message from the api (Viber)(e.g. httpin node). There we specify which variables to assign values from msg object. 
After that, as usual in the flow, we can use the usual chat.get('variable_name').

How do you think this is really done?
Will it work? This would greatly help with the use of third-party API.
Thanks ;)

**Comment by guidone** [comment]
Hi, I've a beta with the Slack support and option to use a persistent storage

`npm install node-red-contrib-chatbot@0.9.0-0`

**Comment by GermaN-st** [comment]
Hello, @guidone 
Tried to check. I hope correctly understood how it works)
My example:
![image](https://user-images.githubusercontent.com/30233260/33069946-48212c22-cec7-11e7-926e-7414a60108e5.png)


In the first case, I set variable after the block conversion in function (1 number in screenshot):
`var chat= msg.chat();
chat.set('test',msg.test1);
return msg;`

In the lower chain, I again add the block conversion and in the function after(2 number in screenshot) I try to read the previously set variable. This is successful.
`var chat= msg.chat();
msg.result=chat.get('test');
return msg;`

I chose storage context in memory.
Thus, having an interrupted flow chain, we can receive context data. It is good)

![image](https://user-images.githubusercontent.com/30233260/33069771-9eb34332-cec6-11e7-80f7-75ddbbbd1dc4.png)

I hope I understood correctly that this should work this way? By the way, I chose telegram transport, although in theory it does not matter which one to choose.
Another question, selecting the file where it will be stored locally?
Thank's

**Comment by guidone** [comment]
Yes this how it works.

The new context storage system works only for Slack, for Telegram, Facebook and Smooch nothing is changed.
So just to recap:

- Memory Context: works like Telegram, Facebook and Smooch (volatile memory)
- Plain file: the context is stored in a plain json file. The `params` field is a json obkect used to configure the context provider, in the case of the Plain file connector it accepts the path where the json files are stored

<img width="2404" alt="screen shot 2017-11-21 at 15 21 18" src="https://user-images.githubusercontent.com/502519/33077309-cba9f67a-cecf-11e7-87bc-ae9a525872f6.png">

```
{
    "path": "/web/chat-contexts"
}
```

**Comment by GermaN-st** [comment]
Hello, @guidone 
FYI

I noticed that after installation `npm install node-red-contrib-chatbot@0.9.0-0,` there was an error when trying to write a bot. Error in the connector Telegram Receiver. Error on the screenshot. When a message arrives in a bot, it occurs.

![image](https://user-images.githubusercontent.com/30233260/33174850-afcaf890-d06a-11e7-87de-a92f0d43f87e.png)

Thanks

**Comment by guidone** [comment]
Ok I've pushed out the 0.9.0-1, not sure if this is going to fix this bug, can you copy here the error you see in the console?

**Comment by GermaN-st** [comment]
Hello, @guidone 

Output from the console for the version `0.9.0-0`  shows the same error)
![image](https://user-images.githubusercontent.com/30233260/33201373-556d9fca-d109-11e7-9c5c-5b04c4e8c37f.png)

In the version `0.9.0-1` the error did not appear. Work correctly ;)

**Comment by guidone** [comment]
Merged `0.9.0`
