### ISSUE TITLE
"Authorized users" not working

### ISSUE THREAD

**Issue by Rotzbua** [guidone/node-red-contrib-chatbot#125]
Package | Version
----- |  ----
node-red | 0.17.5
node-red-contrib-chatbot | 0.8.6

### Description
Hi,

I tried to use the node `authorized?`, but it do not work as expected. I added a user id to the node `Telegram Receiver`, so my message should be processed as `non authorized` but it is still `authorized`. 

I used this example:
https://github.com/guidone/node-red-contrib-chatbot/wiki/Authorized-users

I noticed that in the msg dump is no property `authorized`. Maybe the node do not process the check routine?

### Msg dump (anonymized):

```json
{
  "payload": {
    "chatId": 100,
    "messageId": 200,
    "type": "message",
    "content": "ping",
    "date": "2017-11-20T16:39:26.000Z",
    "inbound": true
  },
  "originalMessage": {
    "message_id": 200,
    "from": {
      "id": 100,
      "is_bot": false,
      "first_name": "xxx",
      "last_name": "xxx",
      "username": "xxx",
      "language_code": "en"
    },
    "chat": {
      "id": 100,
      "first_name": "xx",
      "last_name": "xxx",
      "username": "xxx",
      "type": "private"
    },
    "date": 1511195966,
    "text": "ping",
    "transport": "telegram"
  },
  "_msgid": "xxx.xxx"
}

**Comment by guidone** [comment]
Hi @Rotzbua , the `authorized` attribute is stored in the chat context and not in the message payload, what happens if you connect to the Telegram receiver a RedBot `Debug node`?

It should dump also all the context variables, you should see the value of the authorized key.

**Comment by TJphonix** [comment]
Hi @guidone,
i see that a list of authorized user must be set statically into Telegram Node, under "Bot configuration", filling the field named "Users" with comma separated list of userId.

If i want to pass dynamically this list, how i do?
For example, i have to retrieve the list from a DB and passing by msg

**Comment by FiloVW** [comment]
I'm interested aswell in dynamicly assign authorized users, is there a way? could you explain how I could achieve this task?

**Comment by guidone** [comment]
Yes with the extend node, you can find an example here

https://github.com/guidone/node-red-contrib-chatbot/wiki/Authorized-node

**Comment by FiloVW** [comment]
Thank you for your quick response.
I'm sorry, I already had a look to the link you shared, although I didn't really understand what I'm supposed to do.
1)Do I have to build a function node after the telegram reciever node, containing that code?
2) How could I instruct the code to point into a DB to check if user is authorized?

**Comment by guidone** [comment]
No, you can put the extend node whereever you like

https://github.com/guidone/node-red-contrib-chatbot/wiki/Extend-node

Since it accepts a javascript promises you can make any kind of non blocking call to a DB (for example mongodb), should be plenty of examples connecting Node-RED to a DB

**Comment by FiloVW** [comment]
I'm really sorry I still have trouble understanding how.
I know ho to interrogate and link a DB in Node-RED, the part I don't understand is the how to personalize the code. I'm sure it would be veary esy for my application.
It would be great if I could see an example, but I understand it might be asking too much.
(I noticed you are italian, as I am, if you prefer I could direct message you my clipboard to show you what I'm trying to achieve more clearly)
