### ISSUE TITLE
Listen for bot messages too

### ISSUE THREAD

**Issue by krystof-k** [guidone/node-red-contrib-chatbot#129]
In Slack receiver, messages sent by other bots are not recognized. It should be able to listen for `bot_message` [event](https://api.slack.com/events/message/bot_message).

It'd be great if anyone could add it.

**Comment by guidone** [comment]
@krystof-k it's fixed in `0.9.1`, I initially used this to detect messages coming from the bot itself (preventing a endless circular effect), now I'm using the bot name.

Thanks for the feedback

**Comment by krystof-k** [comment]
Cool. Thanks!

**Comment by krystof-k** [comment]
That's a pity :( Thanks for info!

**Comment by jheiselman** [comment]
One idea would be to check the bot's ID after connecting to the service (bot.info) then check all incoming messages for `subtype = "bot_message"` and `bot_id != self.id`
