### ISSUE TITLE
Is possible to use getChatMembers

### ISSUE THREAD

**Issue by pla10** [guidone/node-red-contrib-chatbot#131]
Is it possible in some way to get information about chat members knowing their ID? (Telegram)

**Comment by guidone** [comment]
@pla10 It will be, I'm working on a refactoring of the Telegram connector, basically the will be exposed the connector (https://github.com/yagop/node-telegram-bot-api), then you will be able to call any method you like

**Comment by guidone** [comment]
Install the new version
```
npm install node-red-contrib-chatbot@0.9.5
```
In the message you now have the method to get the Telegram client
```
var client = msg.client();
client.getChatMember(chatId, userId)
  .then(...)
```
which is an instance of https://github.com/yagop/node-telegram-bot-api
