### ISSUE TITLE
Inline mode

### ISSUE THREAD

**Issue by jibdata** [guidone/node-red-contrib-chatbot#134]
It seems that there is no support for Inline mode with the Telegram In node.
I would like to be able to respond on inline queries from the Telegram client side when the bot is in inline mode:
@[name of the bot] query
https://core.telegram.org/bots/inline
https://core.telegram.org/bots/api#inline-mode

Any plans for this?

**Comment by guidone** [comment]
@jibdata I'll put in the roadmap, thanks for the feedback

**Comment by guidone** [comment]
The inline mode is ready

`node-red-contrib-chatbot@0.9.5`
