### ISSUE TITLE
no send message

### ISSUE THREAD

**Issue by DimiDr0l** [guidone/node-red-contrib-chatbot#135]
Hi, no messages are sent via the function:
msg.payload = {
transport : 'telegram',
chatId : 'my chatID',
type : 'message',
content : 'test message'
};
return msg;

no error messages, no send messages

**Comment by guidone** [comment]
You should use a `Message node` to send a message, are you following this example?

https://github.com/guidone/node-red-contrib-chatbot/wiki/Basic-send-message

**Comment by DimiDr0l** [comment]
no, i wanna send messege of sensor
