### ISSUE TITLE
"Error: ETELEGRAM: 400 Bad Request: message text is empty"

### ISSUE THREAD

**Issue by JeffrySteegmans** [guidone/node-red-contrib-chatbot#136]
I get the following error when I try to send a message to telegram:
"Error: ETELEGRAM: 400 Bad Request: message text is empty"

I use the following flow:

`[{"id":"1d33f3a2.e8595c","type":"inject","z":"c442013d.554a","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":100,"y":560,"wires":[["a38b0818.654cc8"]]},{"id":"f25479cb.a769d8","type":"chatbot-conversation","z":"c442013d.554a","name":"test","chatId":"425552882","transport":"telegram","messageId":"","contextMessageId":false,"store":"","x":490,"y":560,"wires":[["fb15d3da.c024d"]]},{"id":"fb15d3da.c024d","type":"chatbot-message","z":"c442013d.554a","name":"","message":[{"message":""}],"answer":false,"track":false,"x":670,"y":560,"wires":[["4ed06b93.f0d9a4","cbb60411.a8fc08"]]},{"id":"4ed06b93.f0d9a4","type":"chatbot-telegram-send","z":"c442013d.554a","bot":"48f4c267.79407c","track":false,"parseMode":"HTML","outputs":0,"x":910,"y":560,"wires":[]},{"id":"a38b0818.654cc8","type":"function","z":"c442013d.554a","name":"","func":"msg.payload = \"Test\";\nreturn msg;","outputs":1,"noerr":0,"x":330,"y":560,"wires":[["f25479cb.a769d8"]]},{"id":"48f4c267.79407c","type":"chatbot-telegram-node","z":"","botname":"***","usernames":"***","polling":"1000","log":""}]`

The problem is when I return msg.payload="test" in my function. The text doesn't get into the content but in OriginalMessage modify_message_id: "Test"

**Comment by JeffrySteegmans** [comment]
A quickfix for this problem is putting the following function node between "text" node and "telegram sender" node:

`[{"id":"2e710b94.698564","type":"function","z":"223d3f3e.65753","name":"modify_message_id verplaatsen naar content en leeg maken","func":"if (msg.originalMessage.modify_message_id != null){\n    msg.payload.content = msg.originalMessage.modify_message_id;\n    msg.originalMessage.modify_message_id = null;\n}\n\n\nreturn msg;","outputs":1,"noerr":0,"x":1740,"y":200,"wires":[["c0de87ec.876fa8"]]}]`

**Comment by guidone** [comment]
@JeffrySteegmans I see, it's how the node gets default values from the payload, I'm fixing it, thanks for the feedback.

**Comment by guidone** [comment]
@JeffrySteegmans fixed in `0.9.4`

**Comment by JeffrySteegmans** [comment]
@guidone confirmed fixed, tx!
