### ISSUE TITLE
Bluemix Import: "Installation of module node-red-contrib-chatbot failed:"

### ISSUE THREAD

**Issue by ncklrs** [guidone/node-red-contrib-chatbot#137]
I attempted to install node-red-contrib-chatbot via Manage Palette and received this error

Error: Command failed: npm install --save --save-prefix="~" --production node-red-contrib-chatbot@0.9.3
npm WARN deprecated nlp_compromise@6.5.5: nlp_compromise has been renamed to 'compromise', please update
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

**Comment by guidone** [comment]
These are just warnings, these are two libraries that are no longer updated, somehow node-red see this as an error, can you install manually?

**Comment by ncklrs** [comment]
I am very new to both node-red and Bluemix and still trying to understand the platform.  So I am not certain how to install manually.

**Comment by guidone** [comment]
Do you see the RedBot nodes in the palette?

**Comment by guidone** [comment]
Ok, I've prepared a branch with updated libraries, unfortunately the Slack library still uses a deprecated library (throws a warning) and there's nothing I can do.
I'll publish later today

**Comment by ncklrs** [comment]
Ok great. I am really wanting to use the Smooch integration and really like all the conversational pieces with this package.

**Comment by guidone** [comment]
@ncklrs ok, try with the `0.9.4`, I've updated some libraries

**Comment by ncklrs** [comment]
Ok. Via the palette install here was the response:

"Installation of module node-red-contrib-chatbot failed:"
12/14/2017, 4:45:21 PM
msg : string[42]
"------------------------------------------"
12/14/2017, 4:45:22 PM
msg : string[165]
"Error: Command failed: npm install --save --save-prefix="~" --production node-red-contrib-chatbot@0.9.4↵npm WARN deprecated node-uuid@1.4.8: Use uuid module instead↵"


-- I think I am going to have to go about this a different way.

**Comment by guidone** [comment]
What happens with a different package (just to understand if the problem is with this specific package or with the installation)

**Comment by ncklrs** [comment]
I had issues with many packages as I was looking to see if it was across the platform or just the package. I was able to successfully install node-red-node-openweathermap

**Comment by grantwparks** [comment]
This has been a problem for me since I first started using Watson/Node Red.  Haven't been able to install a single node into my palette.  it's about to become a deal breaker.

**Comment by guidone** [comment]
Perhaps it's a matter of permission, did you start from here?

https://nodered.org/docs/platforms/bluemix

I'll try myself in the next few days and try to understand why

**Comment by r-koba** [comment]
I successfully installed node-red-contrib-telegrambot. 
However I'm facing the same problem to node-red-contrib-chatbot as @ncklrs described.

I updated everything but the issue persists

1/11/2018, 10:01:58 AM
msg : string[166]
"Error: Command failed: npm install --save --save-prefix="~" --production node-red-contrib-chatbot@0.9.13↵npm WARN deprecated node-uuid@1.4.8: Use uuid module instead↵"

**Comment by grantwparks** [comment]
If you enable continuous delivery with defaults, a git repo will be created. In that repo's package.json, these nodes can be added to dependencies.  After restarting the app, the new nodes will appear in the palette.

**Comment by guidone** [comment]
@r-koba did you try with @grantwparks suggestions?

**Comment by r-koba** [comment]
@guidone and @grantwparks, first of all, tks for replying!
I'm new in IBM cloud and node-red too... so I'm a little slow
I checked if the continuous delivery was enabled, I was analyzing the packages (both package.json and package-lock.json) and confirmed reference of node-red-contrib-chatbot@0.9.13.
(Should I have to edit anything in package.json?)
I restarted the npm and node-red but still not appear in the palette...

**Comment by grantwparks** [comment]
There may be a particular problem with that node.  I was trying to add a slack chat node to node red on the FRED web site and found that the node had an incompatible dependency in it.  In other words, the node needed to be updated by its maintainer.  It seems like there's multiple chat nodes to look at and maybe there's a different one that would work.  Pay close attention to the versions.

**Comment by carlosrodand** [comment]
@guidone 
I have installed old version 0.9.14 on bluemix by editing package.json and adding the dependency.
But if I try to update to current 0.10.2 version in the palette manager, it says update failed. But at least I can use the old version now (I have used that version because is the one I installed in the past without problems)

**Comment by carlosrodand** [comment]
@guidone 
I have forced node-red at IBM bluemix (Cloud) to install version 0.9.14 (setting a dependency in packages.json) and it works.
But it still refuses to update to 0.10.2 showing the same error "Installation of module node-red-contrib-chatbot failed".

**Comment by Freyja-Folkvangr** [comment]
I've the same error, I've installed RedBot by modifying the package.json file

**Comment by pereiraru** [comment]
hi all, i´m getting also an error installing chatbot on nodered ( on Hassio through the addon packages)

I have faced no issues until now with any other node package. this is the error i´m getting:

`"Installation of module node-red-contrib-chatbot failed:"
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated scmp@0.0.3: scmp v2 uses improved core crypto comparison since Node v6.6.0

> grpc@1.16.1 install /config/node-red/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.16.1/node-v57-linux-arm-musl.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.16.1 and node@8.12.0 (node-v57 ABI, musl) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack  ...`

**Comment by pecket** [comment]
pereirau: I'm having the exact same problem as you. Seems the limited OS behind Hass.io simply doesn't have the required components to compile, and since the precompiled binaries are missing I'm guessing we're simply out of luck until there comes some precompiled binaries.

**Comment by fperego** [comment]
I just created a Node-Red Starter instance but I cannot add any pallet from manage pallets. In my case I wanted to install node-red-contrib-telegramb. Any help on that?
2/7/2019, 8:24:41 AMmsg : string[59]
"Installation of module node-red-contrib-telegrambot failed:"
2/7/2019, 8:24:41 AMmsg : string[42]
"------------------------------------------"
2/7/2019, 8:24:41 AMmsg : string[7]
"Killed↵"
2/7/2019, 8:24:41 AM
msg : string[42]

**Comment by weslleyquadros** [comment]
@guidone you could explain to me how I can display my Watson Assistant option buttons on Facebook Message using Node-red? 
![capturar](https://user-images.githubusercontent.com/31475603/53198118-65f28700-35fa-11e9-9614-83b0340eaba6.PNG)
![capturar2](https://user-images.githubusercontent.com/31475603/53198119-65f28700-35fa-11e9-9309-6aa26e3307d0.PNG)
