### ISSUE TITLE
"Error: EFATAL: Unsupported Buffer file type"

### ISSUE THREAD

**Issue by vojtek** [guidone/node-red-contrib-chatbot#140]
Telegram receiver -> Voice {Hi} -> Telegram sender
Telegram sender - "Error: EFATAL: Unsupported Buffer file type"

**Comment by guidone** [comment]
@vojtek this in fixed in this pull request

**Comment by guidone** [comment]
@vojtek this is fixed in this pull request 

https://github.com/guidone/node-red-contrib-chatbot/pull/133/files

it will be merged in few days

Thanks for the feedback

**Comment by vojtek** [comment]
Thanks for quick answer and fix

**Comment by guidone** [comment]
Merged `node-red-contrib-chatbot@0.9.5`
