### ISSUE TITLE
firstName and lastName not available

### ISSUE THREAD

**Issue by pascalmattes** [guidone/node-red-contrib-chatbot#142]
firstName and lastName are not available in Telegram. Both are correctly set in the Telegram App and node red is receiving the values in the log.

**Comment by guidone** [comment]
Ok I’ll check, I’v just updated Telegram lib, perhaps there’s a glitch
Thanks for the feedback

**Comment by guidone** [comment]
Ok, it's fixed in `0.9.6`

Thanks for the feedback

**Comment by pascalmattes** [comment]
Thanks, it is working now.
