### ISSUE TITLE
Conversation node "null"s the payload

### ISSUE THREAD

**Issue by mapero** [guidone/node-red-contrib-chatbot#145]
Hi,

I used chatbot for a while now. After the recent update my flows stopped working. Even a simple "hello world" does not work anymore.

I noticed that the conversation node is nulling the payload send by the inject and the Telegram sender will send the value as "null".

See example attached:

![screenshot from 2017-12-22 11-21-51](https://user-images.githubusercontent.com/1754967/34294818-9237ac72-e70a-11e7-9042-8f11b0ca6a5e.png)

Thanks.

**Comment by guidone** [comment]
Ok, I'll check, what's the configuration of the conversation node?

**Comment by guidone** [comment]
@mapero check `0.9.7` now it doesn't null the payload, I'm not sure this was the cause why nothing was sent out.
Let me know.

Thanks for the feedback

**Comment by mapero** [comment]
Working now. Thanks for the fast fix.

**Comment by guidone** [comment]
Good!
