### ISSUE TITLE
Version doesn‘t update on flows.nodered.org

### ISSUE THREAD

**Issue by pascalmattes** [guidone/node-red-contrib-chatbot#147]
The Version on flows.nodered.org is still 0.9.5 for a few days now. This prevents updating through web panel.

**Comment by guidone** [comment]
I don’t control how the update the index on flows.nodered.org, I’ll try to find out if there’s a way to trigger the update of the index after a release. Meanwhile if you really need the update you can do it manually with npm

**Comment by pascalmattes** [comment]
Still no new Version, any Updates on this? I can‘t install manually in my productive environment.

**Comment by guidone** [comment]
I requested a refresh

http://d.pr/i/KFBIN7

I don't know what's behind that, I hope it's a kind of an automatic task.
Sorry for the inconvenience.

**Comment by guidone** [comment]
Ok I see `0.9.9` now.

👍
