### ISSUE TITLE
Telegram nodes doesn't work at all

### ISSUE THREAD

**Issue by athphane** [guidone/node-red-contrib-chatbot#148]
Basic setup of [In --> Message --> Out] doesn't work. 
Is my bot config wrong? 
When I deploy the flow the nodes say that it's connected. But sending a message to the bot doesn't seem to show any results. None of the debug nodes showed any results either.

![1](https://user-images.githubusercontent.com/13810742/34351046-1a7d1f70-ea3c-11e7-87c2-1cf166701113.PNG)
![2](https://user-images.githubusercontent.com/13810742/34351047-1ac55dee-ea3c-11e7-9146-0597319a5b1a.PNG)

[Telegrambot](https://github.com/windkh/node-red-contrib-telegrambot) has too much user-end coding to do, which I would like to avoid. If all doesn't work out I guess I can learn the bare minimum of JavaScript to get it up and running.

**Comment by guidone** [comment]
Do you get any error in console? What’ the configuration of the first screen of Telegrambot? Just the token in mandatory, you can leave all other fielda blank

**Comment by guidone** [comment]
It that bot-token just a placeholder you used for the screenshot? It doesn’t seem a valid telegram token

**Comment by athphane** [comment]
No errors in the console. Just a bunch of json like code that has to do something with webhooks I assume. And yes those were placeholder token and user ID.

**Comment by guidone** [comment]
I think I've found it, remove that **user1**

![34351046-1a7d1f70-ea3c-11e7-87c2-1cf166701113](https://user-images.githubusercontent.com/502519/34353841-d4f640e6-ea2a-11e7-8e3b-29d0efffc5d8.png)

it's breaking the telegram bot, I'll fix in the next few hours, but for the moment should work.

Thanks for the feedback!

**Comment by athphane** [comment]
Not working either man. Sure it now says connected. But it's not working as it should. The flow should reply, in theory, "Hello" to any message I send. But no result.

![1](https://user-images.githubusercontent.com/13810742/34354132-0b40b848-ea4e-11e7-9992-5cb6ce41b49e.PNG)
![2](https://user-images.githubusercontent.com/13810742/34354133-0b8b3800-ea4e-11e7-9031-1de05b55d6f4.PNG)

**Comment by guidone** [comment]
I've tried creating a telegram bot from scratch but it worked on my box.

Can you send over the flow with the export function of NodeRed (the credentials will not be exported).

PS I thought it was the "users" field but I was wrong so I deleted the comment

**Comment by athphane** [comment]
[{"id":"c2e6521e.d7d33","type":"chatbot-telegram-receive","z":"73696e1c.a30ea","bot":"e6da12be.7d5f8","x":150,"y":140,"wires":[["196f4132.f307ef"]]},{"id":"f8af420b.33184","type":"chatbot-telegram-send","z":"73696e1c.a30ea","bot":"e6da12be.7d5f8","track":false,"outputs":0,"x":510,"y":140,"wires":[]},{"id":"196f4132.f307ef","type":"chatbot-message","z":"73696e1c.a30ea","name":"hello","message":[{"message":"hello"}],"answer":false,"track":false,"x":330,"y":140,"wires":[["f8af420b.33184"]]},{"id":"e6da12be.7d5f8","type":"chatbot-telegram-node","z":"","botname":"RedBot","usernames":"","polling":"1000","store":"43ab0d1a.768694","log":""},{"id":"43ab0d1a.768694","type":"chatbot-context-store","z":"","name":"context","contextStorage":"memory","contextParams":"{}"}]

**Comment by guidone** [comment]
Ok it's not working on my box too.

It's the "memory" context store, switch to "plain file" and it should work.

This is a serious bug, thanks for spotting it, I'll fix as soon as possible.

**Comment by athphane** [comment]
Aight man thanks for the help. The plain file method worked perfectly.

**Comment by guidone** [comment]
The bug it's fixed in `0.9.9`
