### ISSUE TITLE
No connection possible

### ISSUE THREAD

**Issue by juhuu32** [guidone/node-red-contrib-chatbot#150]
2 Jan 11:15:11 - [error] [chatbot-telegram-node:80faf04e.df7ef] Error creating chatbot openhab2: no context provider specified.
2 Jan 11:15:14 - [warn] [chatbot-telegram-receive:24fdefad.51aa] no bot in config.

![2018-01-02 14_02_06-node-red _ openhab2](https://user-images.githubusercontent.com/28487649/34484543-97402e6a-efc5-11e7-93e8-98b90c5d7c04.png)
![2018-01-02 14_00_59-node-red _ openhab2](https://user-images.githubusercontent.com/28487649/34484517-73892ca6-efc5-11e7-8819-d309532f0215.png)
![2018-01-02 14_03_27-node-red _ openhab2](https://user-images.githubusercontent.com/28487649/34484586-d8a733ee-efc5-11e7-984f-0c810e31bfff.png)

Did I miss anything?

**Comment by guidone** [comment]
Yes, select a context store, the "memory" should be fine for testing

**Comment by guidone** [comment]
This issue should be fixed in `0.9.10`
