### ISSUE TITLE
Telegram: Conversation node seems to add wrong "modify_message_id"

### ISSUE THREAD

**Issue by stefanoco** [guidone/node-red-contrib-chatbot#153]
This used to work until days ago, started behaving like this after (apparently unrelated) flow moditications.

I have a rather complex flow, where NodeRED events should result in messages sent to a specific chatId. So I'm chaining:
- a message with payload="message to be sent";
- a "Conversation" node configured with chatId only;
- a "Text" node with nothing configured.

The result: an error in the NodeRED console "Error: ETELEGRAM: 400 Bad Request: message to edit not found" and indeed the message coming out of the "Conversation" node contains a wrongly generated modify_message_id field, see screenshot

![screenshot at 2018-01-04 12 45 39](https://user-images.githubusercontent.com/959880/34562329-2b81e68e-f14e-11e7-8830-d1e85b00d67c.png)

**Comment by guidone** [comment]
Which version of redbot are you using? Seems like a bug I've fixed a while ago

**Comment by stefanoco** [comment]
...yes discovered now reading #136 indeed. I upgaded to 0.9.9 right now and can't connect to my bot anymore unfortunately! Now when deploying a flow I get: "Error creating chatbot <bot name>: no context provider specified." but I don't want to specify a context provider...

**Comment by guidone** [comment]
Ok, you have to specify a context provider in the bot config, the "memory" one is ok for testing.
In few minutes I'll push a fix for this (if no context provider is specified it uses the default "memory")

**Comment by stefanoco** [comment]
Thanks waiting for the fix

--
Stefano Costa
R&D, Managing Director
Bluewind Embedded Systems
M. +39 335 6565749
https://t.me/stefanoco
http://www.bluewind.it
so long, and thanks for all the fish

Il 4 gen 2018, 13:11 +0100, Guidone <notifications@github.com>, ha scritto:

**Comment by guidone** [comment]
Ok, pushed `0.9.10`

**Comment by stefanoco** [comment]
Yes works now! Before I close the issue: can't specify any context provider type in the dialog (defaulting to memory now) is this normal?

**Comment by guidone** [comment]
It should work

https://d.pr/v/p1EJuv

what happens exactly?

**Comment by stefanoco** [comment]
Nothing actually: same as your workflow, the drop down menu is empty...

![screenshot at 2018-01-04 14 40 26](https://user-images.githubusercontent.com/959880/34566050-7c84a102-f15d-11e7-9223-678cc30c378e.png)

maybe due to NodeRED version? 0.17.5 here and can't upgrade for a few days

**Comment by guidone** [comment]
Even if you open the drop down, you see nothing? 0.17.5 is fine, I'm using it too

**Comment by guidone** [comment]
Sorry documentation is not updated yet, the new chat context system is available for slack and telegram (and facebook soon)

Do you see this call in the the JS console of the borwser

https://d.pr/i/GzlUB3

or any particular error?
Which version of node?

**Comment by stefanoco** [comment]
If I'm looking the correct tab the answer to the call is:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /redbot/context-providers</pre>
</body>
</html>

```

**Comment by stefanoco** [comment]
...and node 4.5.0

**Comment by guidone** [comment]
Ok, perhaps it's due to the host name (I'm testing locally), let me check

**Comment by guidone** [comment]
I guess it's because you have mounted node-red control panel in /admin and not the root, the correct link with your config should be https://myhome.bluewind.it/admin/redbot/context-providers

I'll fix it

**Comment by stefanoco** [comment]
yes this is my setup (seen also on some Raspberry SD images)

**Comment by guidone** [comment]
Ok, found it, I'll push the fix later today

**Comment by stefanoco** [comment]
Works perfectly now, thanks for your effort!
