### ISSUE TITLE
Telegram configuration node not saving correctly

### ISSUE THREAD

**Issue by jibdata** [guidone/node-red-contrib-chatbot#158]
I'm running Node-RED in Docker container (version 0.17.5), node-red-contrib-chatbot version 0.9.12.
After one of the last updates of chatbot, I am not able to save/set the "Parse" setting in the Telegram configuration node. It just go back to None after config update.
Also when I try to create a Context, I am not able to select anything from the Type dropdown field. It is not dropping down correctly/empty.

**Comment by guidone** [comment]
I am already working on it, by tomorrow it will be fixed.

Thanks for the feedback

**Comment by jibdata** [comment]
Cool, thanks a lot for your quick response.

**Comment by guidone** [comment]
Fixed in `0.9.13`

**Comment by jibdata** [comment]
Tested 0.9.13 and all OK
