### ISSUE TITLE
Multiple bot answers in Slack

### ISSUE THREAD

**Issue by MarkusDoof** [guidone/node-red-contrib-chatbot#159]
Sometimes there are 2 to 8 copies of bot answer, I did not found the reason.

**Comment by guidone** [comment]
How the flow does look like?

**Comment by MarkusDoof** [comment]
<img width="1133" alt="snimek obrazovky 2018-01-11 v 0 04 38" src="https://user-images.githubusercontent.com/11775863/34800204-1ab0b280-f663-11e7-8ec5-2b3fc4c39157.png">

**Comment by guidone** [comment]
If you restart node-red does this replication happens as well or disappear?

Can you export the flow here (I'll check tomorrow in my dev box)

Thanks for the feedback

**Comment by MarkusDoof** [comment]
After restart it is ok. but it occurs ofter some time of using it.
I tried to export but export is disabled :(

**Comment by guidone** [comment]
Is it possible that this happens after multiple deploys?
Like you edit the flow + deploy several time and then it happens?

I'll look into it

**Comment by MarkusDoof** [comment]
Yes, and if I do server restart, it is ok.

**Comment by xyleth** [comment]
Hello,

I'm getting the same symptom with a Telegraph setup.  A single message elicits an ever increasing number of responses from the bot.  As a temporary workaround I've built a little dedupe function node that seems to work:

`var messageHash = msg.payload.chatId + ":" + msg.payload.messageId;
var messageLookUp = flow.get('messageLookUp');
if (typeof messageLookUp === "undefined") {
    messageLookUp = [];
}

if (messageLookUp.indexOf(messageHash) == -1) {
    node.warn("First message");
    messageLookUp.push(messageHash);
    flow.set('messageLookUp', messageLookUp);
    return msg;
} else {
    // Do nothing as this is a duplicate
    node.warn("Duplicate message");
}`

Sometimes a deploy will clear whatever the issue is, sometimes it won't.  I haven't tried restarting the NodeRed instance yet.

Let me know if there is any other testing I can do to help.

**Comment by guidone** [comment]
Ok, this is a good hint since the telegram/slack/facebook nodes are basically the same, what differs is the chat platform class that is invoked at some point

Working on it

**Comment by guidone** [comment]
I may have found the problem, would you like to try this beta?

```
npm install node-red-contrib-chatbot@0.9.14-beta-1
```

**Comment by xyleth** [comment]
I have installed that beta and I am still getting the duplicate messages.  It seems to be fine after a restart until I deploy some changes to a flow, that's when the repeats seem to start.

**Comment by guidone** [comment]
Can you tell me which version of node/node-red are you using?

**Comment by xyleth** [comment]
node v6.12.3
node-red v0.17.5

Running on a RaspberryPi 3 running Raspian Jessie

**Comment by guidone** [comment]
If you open configuration node

<img width="1176" alt="schermata 2018-01-12 alle 16 44 25" src="https://user-images.githubusercontent.com/502519/34882810-009c2478-f7b8-11e7-95a0-2b7804046d6a.png">

How many `chatbot-slack-node` do you see?

**Comment by xyleth** [comment]
For me?  Only one, but it's a chatbot-telegram-node because I'm using Telegram not Slack.

**Comment by guidone** [comment]
@xyleth can you try this version?

```
npm install node-red-contrib-chatbot@0.9.14-beta-2
```

I've cleaned up some parts, sorry for these blind trials but I cannot replicate the error on my box,I suspect there's some race conditions when nodes are disposed in slower devices like the Raspberry

**Comment by guidone** [comment]
@xyleth @MarkusDoof I might have found the problem, just to validate it, can you confirm that in your flow there are more that one Telegram/Slack receiver and at least one Telegram/Slack sender with the "track" option enabled?

**Comment by MarkusDoof** [comment]
I have three senders and one receiver from which two have track option enabled.

**Comment by xyleth** [comment]
Hello, sorry for the delay in getting back to you.

I have only one receiver and one sender in my flow.

0.9.14 seems to have fixed the problem however.

**Comment by guidone** [comment]
Pushed out `0.9.15` that fixes the multiple messages with the track option, @xyleth not sure if this is going to solve your problem, if persists let me know and I'll investigate a little further

**Comment by bricegomis** [comment]
I have the same issue with telegram-bot after redeploy, restart node-red solve the problem.
But, when I deploy my flows, the message is duplicated.

Node-RED: v1.0.4
node-red-contrib-chatbot: v0.18.15

I have two receivers, one with track option enabled.
If I remove the receiver with the track option, I don't have the problem.
