### ISSUE TITLE
Not sent messages!

### ISSUE THREAD

**Issue by DimiDr0l** [guidone/node-red-contrib-chatbot#162]
I can not send an event message
no errors
example I enclose
`[
    {
        "id": "d1d8ba56.991b88",
        "type": "chatbot-telegram-send",
        "z": "df90cdc2.4c2fa",
        "bot": "a9eb3f2b.e00f4",
        "track": false,
        "outputs": 0,
        "x": 890,
        "y": 140,
        "wires": []
    },
    {
        "id": "21da9985.799b86",
        "type": "inject",
        "z": "df90cdc2.4c2fa",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 240,
        "y": 340,
        "wires": [
            [
                "dee11ab4.d3dd28"
            ]
        ]
    },
    {
        "id": "dee11ab4.d3dd28",
        "type": "function",
        "z": "df90cdc2.4c2fa",
        "name": "",
        "func": "msg.payload = {\ntransport : 'telegram',\nchatId : '149555324',\nmessage : \"Погода в \",\nmessageId : 28\n};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 443,
        "y": 305,
        "wires": [
            [
                "55175106.3338"
            ]
        ]
    },
    {
        "id": "82ef63c4.3b63d",
        "type": "chatbot-debug",
        "z": "df90cdc2.4c2fa",
        "x": 803,
        "y": 215,
        "wires": []
    },
    {
        "id": "55175106.3338",
        "type": "chatbot-conversation",
        "z": "df90cdc2.4c2fa",
        "name": "",
        "botTelegram": "a9eb3f2b.e00f4",
        "botSlack": "",
        "botFacebook": "",
        "chatId": "",
        "transport": "telegram",
        "messageId": "",
        "contextMessageId": false,
        "store": "",
        "x": 613,
        "y": 195,
        "wires": [
            [
                "d1d8ba56.991b88",
                "82ef63c4.3b63d"
            ]
        ]
    },
    {
        "id": "a9eb3f2b.e00f4",
        "type": "chatbot-telegram-node",
        "z": "",
        "botname": "tele_bot",
        "usernames": "********",
        "polling": "1000",
        "store": "27e3cc9d.b5abf4",
        "log": "",
        "parseMode": ""
    },
    {
        "id": "27e3cc9d.b5abf4",
        "type": "chatbot-context-store",
        "z": "",
        "name": "",
        "contextStorage": "memory",
        "contextParams": ""
    }
]`

**Comment by guidone** [comment]
In your flow a `Message node` is missing, look this example

https://github.com/guidone/node-red-contrib-chatbot/wiki/Start-conversation

**Comment by DimiDr0l** [comment]
It turned out to be sent, but it was not convenient
`[
    {
        "id": "d1d8ba56.991b88",
        "type": "chatbot-telegram-send",
        "z": "df90cdc2.4c2fa",
        "bot": "a9eb3f2b.e00f4",
        "track": false,
        "outputs": 0,
        "x": 890,
        "y": 140,
        "wires": []
    },
    {
        "id": "82ef63c4.3b63d",
        "type": "chatbot-debug",
        "z": "df90cdc2.4c2fa",
        "x": 910,
        "y": 360,
        "wires": []
    },
    {
        "id": "1cc1f295.6ef75d",
        "type": "chatbot-message",
        "z": "df90cdc2.4c2fa",
        "name": "",
        "message": [
            {
                "message": ""
            }
        ],
        "answer": false,
        "track": false,
        "x": 770,
        "y": 340,
        "wires": [
            [
                "d1d8ba56.991b88",
                "82ef63c4.3b63d"
            ]
        ]
    },
    {
        "id": "a44b6862.5add68",
        "type": "function",
        "z": "df90cdc2.4c2fa",
        "name": "",
        "func": "msg.payload = [\n  'First version of the message',\n  'Second version of the message'\n];\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 650,
        "y": 340,
        "wires": [
            [
                "1cc1f295.6ef75d"
            ]
        ]
    },
    {
        "id": "1970fe8.8e7d302",
        "type": "chatbot-conversation",
        "z": "df90cdc2.4c2fa",
        "name": "",
        "botTelegram": "a9eb3f2b.e00f4",
        "botSlack": "",
        "botFacebook": "",
        "chatId": "149555324",
        "transport": "telegram",
        "messageId": "{{messageId}}",
        "contextMessageId": true,
        "store": "",
        "x": 510,
        "y": 340,
        "wires": [
            [
                "a44b6862.5add68"
            ]
        ]
    },
    {
        "id": "dee11ab4.d3dd28",
        "type": "function",
        "z": "df90cdc2.4c2fa",
        "name": "",
        "func": "msg.payload = {\ntransport : 'telegram',\nchatId : '149555324'\n};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 370,
        "y": 340,
        "wires": [
            [
                "1970fe8.8e7d302"
            ]
        ]
    },
    {
        "id": "21da9985.799b86",
        "type": "inject",
        "z": "df90cdc2.4c2fa",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 220,
        "y": 340,
        "wires": [
            [
                "dee11ab4.d3dd28"
            ]
        ]
    },
    {
        "id": "a9eb3f2b.e00f4",
        "type": "chatbot-telegram-node",
        "z": "",
        "botname": "Telegram_bot",
        "usernames": "",
        "polling": "1000",
        "store": "27e3cc9d.b5abf4",
        "log": "",
        "parseMode": ""
    },
    {
        "id": "27e3cc9d.b5abf4",
        "type": "chatbot-context-store",
        "z": "",
        "name": "",
        "contextStorage": "memory",
        "contextParams": ""
    }
]`
