### ISSUE TITLE
Zulip support

### ISSUE THREAD

**Issue by jibdata** [guidone/node-red-contrib-chatbot#164]
Have you considered support for Zulip?
https://github.com/zulip/zulip

**Comment by xeor** [comment]
Would love zulip support! Many orgs use it as an alternative to slack, so maybe it can help nodered to be more interesting for those

**Comment by jibdata** [comment]
Yea, and there is orgs that do not allow usage of external messengers, so this could be a very good alternative in these use cases where orgs have internal ones like Zulip

**Comment by guidone** [comment]
Didn't not Zulip, it's possible.

Beside in RedBot there's some infrastructure to add platforms without reinventing the wheel (Telegram, Slack and Facebook Messenger nodes are coded this way).

I'll give a look

**Comment by jibdata** [comment]
Cool.
Give us a hint if you are going to follow that path or not.

**Comment by GermaN-st** [comment]
I will join. I'm really looking forward to and hope for a mechanism for using any platform. it will help us a lot. Since the redbot itself is very convenient.

**Comment by jibdata** [comment]
Have you decided anything regarding this matter?

**Comment by guidone** [comment]
Hi @jibdata , yes I can work on this. Basic support to text messages and images/files will be enough for you to test/use it?

**Comment by jibdata** [comment]
That's good news.
Let's start with basic support and take it from there.

**Comment by guidone** [comment]
Hi @jibdata have you aver tried to build a chatbot in Zulip? The support fo chatbot it's very strange, there are inbound webhook and outbound webhook but not both. 
Another kind of chatbot can only be handled from a python script which is a kind of extension of the server.

**Comment by xeor** [comment]
I've been playing with the python zulip lib. I'm not sure if it supports other methods, but I create 1 instance, then register a callback function on it, then use an instance created the same way to send messages.

Won't the functionality of https://github.com/zulip/zulip-js do the trick you think?

**Comment by xeor** [comment]
Closed as "not doing"? Or another reason?

**Comment by guidone** [comment]
Yes, not planning to implement zulip at this moment sorry

**Comment by guidone** [comment]
There's the universal connector if you want to play with it, but it requires coding (and time)
