### ISSUE TITLE
Facebook and nodes/chatbot-conversation.js -> sends to Telegram instead of FB

### ISSUE THREAD

**Issue by ArfyFR** [guidone/node-red-contrib-chatbot#166]
Hi,
In my node_modules, I had to change line 39 in nodes/chatbot-conversation.js
`          platformNode = RED.nodes.getNode(botTelegram).chat;
`to
`          platformNode = RED.nodes.getNode(botFacebook).chat;
`in order to be able to create and send a message to FB
(auto reply FB in -> txt -> FB out worked)

If not I got the following error (and no message to FB)
TypeError: Cannot read property 'chat' of null (or undefined)

**Comment by guidone** [comment]
Yes, copy and paste mistake, I'll fix soon.

Thanks for the feedback

**Comment by guidone** [comment]
Fixed in `0.9.15`, thanks for the feedback
