### ISSUE TITLE
Telegram receiver not working

### ISSUE THREAD

**Issue by lwhitworth** [guidone/node-red-contrib-chatbot#168]
Not seeing any messages I send to the Bot (have it going to a debug node).  Looking in syslog on the system I see:

`Feb  1 20:56:49 pi Node-RED[21062]: { RequestError: Error: connect ENOENT /botxxxxxx:xxxxxxxxxxxxxx/getUpdates
Feb  1 20:56:49 pi Node-RED[21062]:     at new RequestError (/home/pi/.node-red/node_modules/request-promise-core/lib/errors.js:14:15)
Feb  1 20:56:49 pi Node-RED[21062]:     at Request.plumbing.callback (/home/pi/.node-red/node_modules/request-promise-core/lib/plumbing.js:87:29)
Feb  1 20:56:49 pi Node-RED[21062]:     at Request.RP$callback [as _callback] (/home/pi/.node-red/node_modules/request-promise-core/lib/plumbing.js:46:31)
Feb  1 20:56:49 pi Node-RED[21062]:     at self.callback (/home/pi/.node-red/node_modules/request/request.js:123:22)
Feb  1 20:56:49 pi Node-RED[21062]:     at emitOne (events.js:116:13)
Feb  1 20:56:49 pi Node-RED[21062]:     at Request.emit (events.js:211:7)
Feb  1 20:56:49 pi Node-RED[21062]:     at ClientRequest.self.clientErrorHandler (/home/pi/.node-red/node_modules/request/request.js:244:10)
Feb  1 20:56:49 pi Node-RED[21062]:     at emitOne (events.js:116:13)
Feb  1 20:56:49 pi Node-RED[21062]:     at ClientRequest.emit (events.js:211:7)
Feb  1 20:56:49 pi Node-RED[21062]:     at TLSSocket.socketErrorListener (_http_client.js:387:9)
Feb  1 20:56:49 pi Node-RED[21062]:     at emitOne (events.js:116:13)
Feb  1 20:56:49 pi Node-RED[21062]:     at TLSSocket.emit (events.js:211:7)
Feb  1 20:56:49 pi Node-RED[21062]:     at emitErrorNT (internal/streams/destroy.js:64:8)
Feb  1 20:56:49 pi Node-RED[21062]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Feb  1 20:56:49 pi Node-RED[21062]:     at process._tickCallback (internal/process/next_tick.js:180:9) code: 'EFATAL' }`

Seems to suggest it can't connect to check for messages which would explain why the debug node never shows anything.  Have I missed something obvious?

**Comment by guidone** [comment]
I'm using an external library to connect to Telegram, this error comes straight from that library, seems like the connection is missing or the auth token is wrong.
Is there another Telegram chatbot using the same token?

**Comment by lwhitworth** [comment]
I don't think so.  I've only just started with this so I might be missing something, but I tried it didn't work so I ask @BotFather to revoke the token and issue a new one, tried the new one and that didn't work either.

I'll start from the beginning again and see if I missed something.

**Comment by guidone** [comment]
Can you share the flow (the credentials will be left out of the export by NodeRed)?

**Comment by lwhitworth** [comment]
At the moment it's simply:

`[{"id":"13e997b1.4b2958","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"21fc3447.583e1c","type":"chatbot-telegram-receive","z":"13e997b1.4b2958","bot":"e07bb9bd.9938c8","x":396,"y":133,"wires":[["2dfe7c38.d98fe4"]]},{"id":"2dfe7c38.d98fe4","type":"debug","z":"13e997b1.4b2958","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":398.5,"y":228,"wires":[]},{"id":"e07bb9bd.9938c8","type":"chatbot-telegram-node","z":"","botname":"lwnodebot","usernames":"","polling":"1000","store":"d6ebac50.72b9d","log":"","parseMode":""},{"id":"d6ebac50.72b9d","type":"chatbot-context-store","z":"","name":"Memory","contextStorage":"memory","contextParams":""}]`

I previously had a receiver -> message -> sender flow but was trying to strip it back as much as possible.

I've tried `curl -L https://api.telegram.org/botxxxx:xxxxx/getUpdates` on the host directly and that returns as expected.

**Comment by guidone** [comment]
Works for me, what version of node and redbot are you using?

**Comment by lwhitworth** [comment]
Node: v8.9.3
Redbot: 0.9.15 (I installed it via palette within nodered)

Cheers

**Comment by lwhitworth** [comment]
Okay, tried it on another pi and everything works fine with my telegram bot.....obviously something wrong with node-red or npm or cosmic rays on that other one.  Sorry for wasting your time!!

**Comment by guidone** [comment]
No problem! I rather spend some time this way rather than risking to lose a good feedback 👍
