### ISSUE TITLE
Messages lost

### ISSUE THREAD

**Issue by dezmob** [guidone/node-red-contrib-chatbot#169]
Sometimes randomly message will be lost and not appear in the log.

<img width="636" alt="capture d ecran 2018-02-05 12 29 37" src="https://user-images.githubusercontent.com/36156886/35802520-b4859256-0a70-11e8-82b7-1662b8aa6fe3.png">

![image-1](https://user-images.githubusercontent.com/36156886/35802594-021306ac-0a71-11e8-9070-b252d0ae9196.jpg)

**Comment by guidone** [comment]
Which version of redbot do you have? I’m thinking of adding a debug param to telegram receiver in order to check if these kind of problems a are due to telegram polling or redbot. Have you tried playing with the polling interval?

**Comment by dezmob** [comment]
I'm on the v0.9.15.
I've set the polling to 100ms and now my bot seems to receive all my messages!

Thanks!
