### ISSUE TITLE
Programmatic function to send buttons

### ISSUE THREAD

**Issue by lgertel** [guidone/node-red-contrib-chatbot#171]
Hello everyone. I'm following the documentation do send buttons inside a function.
There is one gotcha: I have to add extra parameters to make it work. Does anyone know if we need to do that for every message or i'm doing something wrong.
For the button example, I have to inject the type and chatId.

`msg.payload = {
  type: "inline-buttons",
  chatId: msg.payload.chatId,
  content: 'This is a message above the buttons',
  buttons: [
    {
      type: 'url',
      url: 'http://javascript-jedi.com',
      label: 'Javascript Jedi'
    },
    {
      type: 'postback',
      value: 'MY_POSTBACK_MESSAGE',
      label: 'Click me!'
    }
  ]
};
return msg;`

Using the example in Wiki, I got no answer because the object is different from the Button template for example.
<img width="1489" alt="screen shot 2018-02-08 at 10 50 44" src="https://user-images.githubusercontent.com/634985/35973810-f1069b22-0cbd-11e8-8674-539eae398cc0.png">

**Comment by guidone** [comment]
Try connecting the function node to the buttons node and the buttons node to the telegram sender.  In the function node just return the payload the buttons array the message


```
msg.payload = {};
msg.payload.message = 'This is a message above the buttons';
msg.payload.buttons = [ 
  { type: 'url', url: 'http://javascript-jedi.com', label: 'Javascript Jedi' }, 
  { type: 'postback', value: 'MY_POSTBACK_MESSAGE', label: 'Click me!' } 
]; 

return msg;
```

**Comment by lgertel** [comment]
Fantastic! This is true for all the other components?
I'm asking that because all the flow and context in my app is controlled by Watson Conversation.

I'm building a custom object from response to switch to the correct compontent.

Thanks!!!

**Comment by guidone** [comment]
Yes, in general for each node you can specify programmatically one or more parameter in a upstream node.
Parameters specified inside the node configuration have always precedence.

For each node at the bottom of the help page there's the list of available parameters

To switch based on the "topic" of the conversation (which is a special variable in the chat context) use the `Rules node`

**Comment by lgertel** [comment]
Question: And for components that have required fields? I have to ignore the message?
<img width="864" alt="screen shot 2018-02-08 at 11 53 11" src="https://user-images.githubusercontent.com/634985/35976256-b8f3b9aa-0cc6-11e8-9903-dcadc08ae6b4.png">
<img width="991" alt="screen shot 2018-02-08 at 11 53 05" src="https://user-images.githubusercontent.com/634985/35976260-b97b441a-0cc6-11e8-8a97-56a51166c23b.png">

**Comment by guidone** [comment]
Yes ignore it, I will fix in order to accept empty elements
