### ISSUE TITLE
Install not working. looks like slack/client dependancy is broken.

### ISSUE THREAD

**Issue by mrlake** [guidone/node-red-contrib-chatbot#172]
Hi,

I'm having problems getting up and running.  Fallen at the first hurdle......    I have pasted the install progress of both chatbot and slack/client below and attached the debug log.

Do you have any pointers for me ?

 npm install node-red-contrib-chatbot
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'slack/client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'node-red-contrib-chatbot'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-contrib-chatbot"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0

Tried to manually install the slack client.  With No Joy.

npm install @slack/client
npm WARN package.json node-red-project@0.0.1 No repository field.
npm WARN package.json node-red-project@0.0.1 No README data
npm WARN package.json node-red-project@0.0.1 No license field.
npm ERR! git clone git@github.com:slack/client undefined
npm ERR! git clone git@github.com:slack/client undefined
npm ERR! addLocal Could not install slack/client
npm ERR! Error: ENOENT: no such file or directory, stat 'slack/client'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.59-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "@slack/client"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! path slack/client
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0

[npm-debug.log](https://github.com/guidone/node-red-contrib-chatbot/files/1713015/npm-debug.log)

**Comment by guidone** [comment]
It strange, the publishing process tests all dependencies before publishing the package.

Beside the slack client is very popular and named `@slack/client` and not `slack/client` 

I suspect you're using an old version of node/npm

```
info using npm@1.4.21
info using node@v4.8.2
```

**Comment by mrlake** [comment]
Yup..  That was it.  

Raspbian default is ancient even from the new stretch image.  I just installed the latest LTS of node.js and and node red with this command: update-nodejs-and-nodered

I cant believe how easy this is getting and that is down to people like you contributing great work, thank you.  I'm now rubbing my hands and about to tuck into some serious chatbot action!

**Comment by guidone** [comment]
Perfect! Thanks and good work with it
