### ISSUE TITLE
Keyboard buttons from function node

### ISSUE THREAD

**Issue by GermaN-st** [guidone/node-red-contrib-chatbot#173]
Hello.
Since the last versions. After about 0.8.7, the sending of the keyboard to telegram node via the function block doesn't work.
How I did it:

Function node:
![image](https://user-images.githubusercontent.com/30233260/36159893-e9b13cf6-10f0-11e8-810d-8d02263e6a14.png)

![image](https://user-images.githubusercontent.com/30233260/36159862-dab00976-10f0-11e8-81a4-d54713bf9fd0.png)

It was very convenient. Since you can make a keyboard with several buttons in the same row

Please, fix it.

**Comment by guidone** [comment]
Ok fixed in `0.9.21`, the `Keyboard node` completely revamped, so the passed payload is no longer compatible with the one in the screenshot ([see here](https://github.com/guidone/node-red-contrib-chatbot/wiki/Keyboard-node)) but it's possible to defined row of buttons directly in the config panel
