### ISSUE TITLE
Required node-telegram-bot-api else Telegram IN/OUT does not appear under RebBot Platforms

### ISSUE THREAD

**Issue by aniston** [guidone/node-red-contrib-chatbot#178]
@guidone , Ottimo Lavoro, Complimenti ;) 
Good work on this ChatBot, Congrats.

i've just installed and tried out the node-red-contrib-chatbot v0.9.22, but could not see the Telegram IN/OUT nodes under RedBot Platforms, only after installing the node-telegram-bot-api (currently at v0.30.0) the Telegram IN/OUT nodes showed up.

Has anyone else experienced this behaviour ?
If the node-telegram-bot-api is a requirement then it might be important for first timers or the non experienced to know that, else they like me will not find the Telegram IN/OUT nodes.

My current installation versions are:
Node-RED version: **v0.18.3**
Node.js  version: **v8.9.4**
Linux **4.4.0-112-generic x64 LE**
node-red-contrib-chatbot **v0.9.22**
node-telegram-bot-api **v0.30.0** (taken from https://github.com/yagop/node-telegram-bot-api)
and installed with  `sudo npm install --save node-telegram-bot-api -g`

**Comment by guidone** [comment]
Thanks @aniston , that never happened to me, the redbot already have as dependency node-telegram-bot-api, I don't see any reason why it should use the global one instead of the local one.
Perhaps the installation failed in some why.

I'd wait a couple of days to be sure that no one has the same problem before closing the issue

Thanks for the feedback

**Comment by aniston** [comment]
Hello @guidone , i checked the npm install log and yes the node-telegram-bot-api did **not** install, as of now i cannot replicate as it is already installed, mine may be a one off case due to other system parameters/issues, so I guess you can safely close the issue if no one else brings it up.

**Comment by guidone** [comment]
🖖
