### ISSUE TITLE
Inject ad-hoc messages

### ISSUE THREAD

**Issue by jheiselman** [guidone/node-red-contrib-chatbot#182]
In a previous version of RedBot, I was able to manually create a JSON object representing a chat message and pass it to a Telegram Sender. This would act as a way for me to gateway messages from other services to me as alerts. This doesn't appear to work anymore in the current version v0.9.24.

I understand that the project aims to provide more of a user-initiated automation, however, I wonder if it's possible to get this style of functionality again.

**Comment by guidone** [comment]
Yes it's still possible, is this example what you are trying to do?

https://github.com/guidone/node-red-contrib-chatbot/wiki/Start-conversation

You can also create your message programmatically

https://github.com/guidone/node-red-contrib-chatbot/wiki/Message-node

**Comment by jheiselman** [comment]
Ah yes. That works for me. Thank you.

**Comment by guidone** [comment]
🖖
