### ISSUE TITLE
Error on clean installation of 0.9.25

### ISSUE THREAD

**Issue by jibdata** [guidone/node-red-contrib-chatbot#184]
Get following errors when doing a clean install of 0.9.25:
12 Mar 10:30:45 - [info]  - node-red-contrib-chatbot:chatbot-telegram-node : Error: cannot enable cancellation after promises are in use (line:3)
12 Mar 10:30:45 - [info]  - node-red-contrib-chatbot:chatbot-telegram-receive : Error: cannot enable cancellation after promises are in use (line:3)
12 Mar 10:30:45 - [info]  - node-red-contrib-chatbot:chatbot-telegram-send : Error: cannot enable cancellation after promises are in use (line:3)

**Comment by jibdata** [comment]
chatbot-telegram-node, chatbot-telegram-receive and chatbot-telegram-send are not working
so it seems that the errors described i my last post is fatal for the functionality of these nodes

**Comment by guidone** [comment]
Seems it has something to do with telegram api library, I'll try to update the lib

https://github.com/yagop/node-telegram-bot-api/issues/319

**Comment by jibdata** [comment]
Just a little extra thing.
Since i downgraded to 0.9.24, I have discovered that the issue with blank Type dropdown in the Context config node have returned.

**Comment by guidone** [comment]
Hi @jibdata I've just updated to `0.9.26` with the updated lib of Telegram, if this doesn't solve the problem I'll need more info about your configuration (os/version of node/version of node red) since I'm not able to replicate the problem on my box

**Comment by jibdata** [comment]
Hi,
After upgrade to 0.9.27 the nodes is working (meaning Chatbot can be used), but it throws the warning in console on start:
_Mon, 19 Mar 2018 08:48:18 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:643:30_

Since automatic enabling of cancellation of promises is deprecated I think this should be addressed sometime soon.

I am using the official Docker container image of Node-RED that contains:
OS: Debian GNU/Linux 8 (jessie)
Node-RED version: v0.18.4
Node.js  version: v8.9.4

The issue with blank Type dropdown in the Context config node is still there.

**Comment by guidone** [comment]
Fixed in `0.9.28`

**Comment by jibdata** [comment]
Good.
I will test the new version as soon it is available in the Node-RED repo.

**Comment by jibdata** [comment]
Tried to upgrade to 0.9.28, and still there is warning:
_Fri, 23 Mar 2018 11:33:57 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:643:30_

Also, the issue with blank Type dropdown in the Context config node is still there.
This one I will try to test from another PC to check if there is something browser+PC related.

**Comment by guidone** [comment]
:spock-hand: ok, thanks for for the feedback
