### ISSUE TITLE
Error on image sending via Image node + Facebook node

### ISSUE THREAD

**Issue by Ksedline** [guidone/node-red-contrib-chatbot#185]
There is a problem with an image node. When I'm trying to send image to facebook  with facebook out node I've got this error: 
"Error: EISDIR: illegal operation on a directory, open 'C:\Users\admin\AppData\Local\Temp'". 
It is a problem with the way the Facebook connector upload the file.
It stores in a temp directory and then upload.

**Comment by guidone** [comment]
Fixed in `0.9.28`
