### ISSUE TITLE
Telegram webhook option available?

### ISSUE THREAD

**Issue by suiluj** [guidone/node-red-contrib-chatbot#189]
Hello,
i was able to use the Telegram Receiver with polling.

Is there an option to use it with webhook instead?
I have https certificates so that is not a problem.

Thank you for your help.

**Comment by guidone** [comment]
Not currently, in theory it's possible, the point is that there's no backend in Telegram to handle webhooks, so some sort of UI will be needed in RedBot to handle these webhooks.

Why would you use the webhook instead of the polling?

**Comment by suiluj** [comment]
thanks for your answer.
i kind of like the direct response when actually someone is using the bot instead of in worst case 1sec waiting.
i know i could set the polling faster but then there would be a lot of requests even when nobody is doing anything.
webhooks are more elegant.

you can set a webhook for telegram bots:
[https://core.telegram.org/bots/webhooks](https://core.telegram.org/bots/webhooks)

**Comment by guidone** [comment]
Ok, I'll add to the roadmap but with a low priority, it's a big effort compared to the value that brings to the framework, let's see if someone else asks for it.
