### ISSUE TITLE
Facebook Send/ Receive node not available in RPi

### ISSUE THREAD

**Issue by sriram155** [guidone/node-red-contrib-chatbot#19]
Facebook Send/ Receive node is not loading on my Raspberry Pi 2. However, it works well on my Windows PC running an instance of Node-RED. 

NodeRED version on my RPI2 is v0.14.6, NodeJS v0.10.29

/home/pi/.node-red/node_modules/messenger-bot/index.js:2
const url = require('url')
^^^^^
21 Sep 14:29:05 - [warn] [chart request] Deprecated call to RED.runtime.nodes.re                                                                           gisterType - node-set name must be provided as first argument

**Comment by guidone** [comment]
Which version of node? I was able to run it on a raspberry pi zero, perhaps you ha e to update node

**Comment by sriram155** [comment]
node v0.10.29

**Comment by sriram155** [comment]
All other features except Facebook Messenger node works perfectly. Telegram and Slack works well.

**Comment by guidone** [comment]
Yes Facebook receiver uses an external lib that has arrow functions and I
think are not supported by node 0.10.x, I'm working on a lib that get rid
of them, you can wait a couple of day for that or upgrade node to a more
recent version
Il giorno mer 21 set 2016 alle 08:35 sriram155 <notifications@github.com>
ha scritto:

**Comment by sriram155** [comment]
I'll wait for your updates. Thanks :+1:

**Comment by guidone** [comment]
Hi @sriram155 I have a beta version you can test

npm install node-red-contrib-chatbot@0.5.14-beta1

This also moves the Facebook endpoint to the same port of node-red (so it can be used on cloud hosting like Heroku).

I've refactored the lib removing exoteric features of js, but I strongly reccomend to update node and node-red (http://nodered.org/docs/getting-started/upgrading), I've tried node 10.x and the latest of node-red and there were some things not working properly
