### ISSUE TITLE
Duplicate responses in Telegram

### ISSUE THREAD

**Issue by flamingm0e** [guidone/node-red-contrib-chatbot#194]
When I try to start a command sequence (/start) to my bot, every time I make a change and deploy, the response comes back multiple times.  It starts with one or 2, but re-deploying quickly turns it to 5-6+.

I am trying to make a very menu like system for a bot so that I can interact with my home assistant instance with it.

When I send a command of /start, I want it to display a set of buttons to choose from (this works), but the 'message' is sent many times over.

![image](https://user-images.githubusercontent.com/1229798/37887359-f603e188-3086-11e8-84df-2e6637e2d77d.png)

![image](https://user-images.githubusercontent.com/1229798/37887379-0d26af1c-3087-11e8-9937-d3be6b004d4c.png)

![image](https://user-images.githubusercontent.com/1229798/37887339-ca7968f8-3086-11e8-92bf-adc223c9b4c7.png)

**Comment by guidone** [comment]
Hi @flamingm0e thanks for the detailed issue, which version of RedBot are you using?

**Comment by flamingm0e** [comment]
I am on version 0.9.28 on node-red 0.18.4, using the v8 builds of node-red (for use with latest home-assistant nodes)

**Comment by guidone** [comment]
Hi @german-st I've fixed a bug with `0.9.29` where unused Telegram bot config where launched even if not used, causing some polling error, @flamingm0e I'm not sure this will fix the duplicate message, I'm still investigating it (I saw this happen a while ago but I'm not able to replicate)

**Comment by flamingm0e** [comment]
Thank you, my friend. 

I will test this out as soon as I can tonight

**Comment by carlosrodand** [comment]
Try to set "full deploy" and deploy the whole thing ...

In my case, a partial deploy (current flow) ends up with this behavior

**Comment by guidone** [comment]
@carlosrodand I've been chasing this bug for days without being able to replicate it, this is a good clue, thanks

**Comment by joside** [comment]
Same for me, doing only a partial deploy will duplicate the answers sent.

**Comment by guidone** [comment]
Thanks all, added in the FAQ section
