### ISSUE TITLE
Sticker Node Problem

### ISSUE THREAD

**Issue by Ksedline** [guidone/node-red-contrib-chatbot#199]
There is a problem with a sticker node and telegram. It does not works for custom sticker packs. I'm trying to send this id: CAADAgADAQADkea5FFY2S2hruN-UAg, which I got from GetStickerIdBot
Also it does not want to change a sticker's node name when you trying to do it from sticker node config (I know that does not call API or something, but if you fix this - it will help me when I have 2 more Sticker to understand which Sticker I want to send)

**Comment by guidone** [comment]
It turned out the sticker node was not working at all, I've fixed it in `0.12.1`, can you check?
Thanks for the feedback

**Comment by Ksedline** [comment]
It works. Thank you!

**Comment by guidone** [comment]
good 🖖
