### ISSUE TITLE
Enhancement: Support to send text messages with markdown and/or HTML styles

### ISSUE THREAD

**Issue by chameleonbr** [guidone/node-red-contrib-chatbot#2]
First, congratulations, it's a nice, really enjoyed.
I use the telegram and saw that it is possible to send messages using HTML or markdown, I found it interesting that to improve the format of the messages.

**Comment by chameleonbr** [comment]
You could close the issue, sorry.
Sending aditional options object to telegram sender works ok.
Example
`
msg.payload = {chatId:chatId, type:"message",content:"my content,"options":{parse_mode:"Markdown"}};
return msg;
`

**Comment by guidone** [comment]
thanks @chameleonbr for the feedback, sorry totally missed this issue, there's a drop down now in the message node to select which kind of parsing (markdown or html)

**Comment by mu3** [comment]
Looks like the option is gone from all the nodes.
It was inside the [config node](https://take.ms/u0BYv) once and it's not in the message node anymore.

Even `msg.payload.options.parse_mode = 'HTML'` doesn't work.

How `parse_mode` can be set nowadays?

**Comment by guidone** [comment]
Look at the params node
Il 21 mag 2020, 00:43 +0200, Jason <notifications@github.com>, ha scritto:

**Comment by mu3** [comment]
Thank you!
