### ISSUE TITLE
reset-buttons type telegram not functioning as expected

### ISSUE THREAD

**Issue by rneurink** [guidone/node-red-contrib-chatbot#204]
Hi,

I'm having some issues with clearing the custom keyboard in Telegram.
I've found in your code that you have made a type to use the [replykeyboardremove](https://core.telegram.org/bots/api#replykeyboardremove) in the api. Now i've tried this with a function node containing:
`msg.payload = {
  type:"reset-buttons"
};
return msg;`

When i send this message it just hides the keyboard instead of clearing it. Now i have found if you use the keyboard node with a message and a no buttons specified it will clear the keyboard but i rather do this without sending a text message to the users.

Do you have an example of a working flow to remove the custom keyboard or might this be a problem with the API or the connector?

Thnx.

**Comment by rneurink** [comment]
I forgot the message.content i hoped i would be able to achieve this without posting a message. If anyone knows how to do this without posting a message please comment.

**Comment by guidone** [comment]
is this all right?

**Comment by rneurink** [comment]
It would be nice if this was possible without posting a message but when you look at examples of other bots all the bots return a message and clear the keyboard at that point. It may be handy to create a new option (checkbox) in the text node or so to clear the keyboard

**Comment by guidone** [comment]
I've to check but I think it's the Telegram API doesn't allow it
