### ISSUE TITLE
Missing configuration in Slack Receiver

### ISSUE THREAD

**Issue by leRenart** [guidone/node-red-contrib-chatbot#207]
Hello and thank you for this nice project.

I'm trying to configure a Slack bot without success. I've got two errors once deployed a `Slack Receiver` node. (on Slack side everything is ok, bot is successfully created)

```
23/05/2018 à 18:21:44node: 67af857f.a3390c
msg : error
"TypeError: Cannot read property 'get' of undefined"
23/05/2018 à 18:21:44node: afabc5a1.17fcc
msg : string[39]
"Missing configuration in Slack Receiver"
```

![image](https://user-images.githubusercontent.com/1085151/40438088-70049d7a-5eb7-11e8-9903-ec0c5eea13ac.png)

**Comment by guidone** [comment]
sorry @leRenart for the late response, are you using DEV or PROD configuration?
