### ISSUE TITLE
Support Signal messenger

### ISSUE THREAD

**Issue by renne** [guidone/node-red-contrib-chatbot#208]
I suggest to use [libsignal-protocol-javascript](https://github.com/signalapp/libsignal-protocol-javascript) to support the [Signal](https://signal.org/)  messenger.

**Comment by rcarmo** [comment]
I was wondering if there were any plans for this to happen.

**Comment by guidone** [comment]
I agree, it’s gaining a lot of attention, it appears that its privacy and crypto solutions are the best.
I’ll put in the roadmap

**Comment by jorgeassuncao** [comment]
Plus one for that!

**Comment by T-Hollenbeck** [comment]
Plus one

**Comment by SilvainLouis** [comment]
+1

**Comment by EDsteve** [comment]
Signal implementation would be awesome.

**Comment by redflag237** [comment]
+1

**Comment by bubi1311** [comment]
Would be great! +1

**Comment by callap** [comment]
+1

**Comment by dslgomes** [comment]
+1

**Comment by shaxxx** [comment]
Yes please

**Comment by bogorad** [comment]
Once Telegram is booted from the app stores (due to it's "channels" feature) we'll need this badly!

**Comment by VooPoc** [comment]
Yes, please add! :)

**Comment by guidone** [comment]
Hi guys, sorry for the absence, I changed work recently. 
I'll work on it
