### ISSUE TITLE
Image node does not accept binary buffer from HTTP node

### ISSUE THREAD

**Issue by merlinmb** [guidone/node-red-contrib-chatbot#210]
Hi - first up, thanks for an awesome system!
I'm struggling to link together the http node (node red) directly to the chatbot image node.
returns an error: 
"Error: EISDIR: illegal operation on a directory, open '/tmp/'"

Seems the image node requires a filename and cannot handle a binary buffer as direct input?
![image](https://user-images.githubusercontent.com/6130951/41025601-a3f1b5c6-6972-11e8-8174-0efabe32b994.png)

**Comment by guidone** [comment]
Hi @merlinmb it should hadle it, I'll check in the next hours

**Comment by guidone** [comment]
Hi @merlinmb I did a quick test and it works for me, can I see the configuration of the "http request" node? In particular are you returning the content of the http request as a buffer and not a string (the default is string)

**Comment by guidone** [comment]
@merlinmb ok fixed in node-red-contrib-chatbot@0.12.7

**Comment by merlinmb** [comment]
thanks for the quick response - updating now.

**Comment by merlinmb** [comment]
Thank you, @0.2.17 works nicely. Good thinking with the unique temp filename, I simultaneously upload images to slack.

**Comment by guidone** [comment]
🖖 

Thanks for the feedback
