### ISSUE TITLE
chatbot Image node does not handle complex urls

### ISSUE THREAD

**Issue by merlinmb** [guidone/node-red-contrib-chatbot#211]
I tried using a URL directly in the config of the image node:
![image](https://user-images.githubusercontent.com/6130951/41025710-eb33d964-6972-11e8-9976-c17a6a5c737a.png)

and it seems to not allow complex URLs that specify https, and/or plain text auth pushed as part of the image url (https://username:password@url_IP_address).

The error output is:
"Don't know how to handle: https://username:password@192.168.1.23:8184/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=xxxxx&pwd=xxxxxxxx"
[chatbot-image:ea9685a6.e1fa88] TypeError: fetcher is not a function

**Comment by guidone** [comment]
Ok, I’ll update the regulR expression that matches the url, thanks for the feedback

**Comment by guidone** [comment]
It should be fixed in `0.12.8`
