### ISSUE TITLE
chatId not being defined

### ISSUE THREAD

**Issue by luismanson** [guidone/node-red-contrib-chatbot#214]
Hello, im having trouble figuring if this is a bug or an error on my part. I have an inject node send a message to a chatbot-conversation, which is not setting up chatId.

Inject settings:
`{
  "_msgid": "1b6a4fcd.d3edc",
  "topic": "/indoor/MiGrowOS-esp32_3B27C0/events",
  "payload": {
    "type": "message",
    "content": "Hola, this is an event\n"
  },
  "_event": "node:5ffacfa7.094278"
}
`

debug output from conversation node:
`
{
  "_msgid": "1b6a4fcd.d3edc",
  "topic": "/indoor/MiGrowOS-esp32_3B27C0/events",
  "payload": {
    "type": "message",
    "content": "Hola, this is an event\n"
  },
  "_event": "node:5ffacfa7.094278",
  "originalMessage": {
    "chatId": "418757665",
    "userId": null,
    "messageId": null,
    "transport": "telegram",
    "language": null
  }
}
`

Source: 
`
[
    {
        "id": "70e9fda0.25ec34",
        "type": "chatbot-conversation",
        "z": "f28ea906.5f72e",
        "name": "a_Luis",
        "botTelegram": "c064d56a.37e318",
        "botSlack": "",
        "botFacebook": "",
        "chatId": "418757665",
        "transport": "telegram",
        "messageId": "",
        "contextMessageId": false,
        "store": "",
        "x": 230,
        "y": 140,
        "wires": [
            [
                "49f429ae.a2d5b",
                "2dff9ab5.2555de"
            ]
        ]
    },
    {
        "id": "54102e75.71b17",
        "type": "inject",
        "z": "f28ea906.5f72e",
        "name": "",
        "topic": "",
        "payload": "{\"type\":\"message\",\"content\":\"Hola, this is an event\n\"}",
        "payloadType": "json",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 90,
        "y": 140,
        "wires": [
            [
                "70e9fda0.25ec34"
            ]
        ]
    },
    {
        "id": "c064d56a.37e318",
        "type": "chatbot-telegram-node",
        "z": "",
        "botname": "LuisIoTbot",
        "usernames": "",
        "providerToken": "",
        "polling": "1000",
        "store": "",
        "log": "",
        "parseMode": "",
        "debug": false
    }
]
`

**Comment by guidone** [comment]
Hi @luismanson here is an example for starting a conversation

https://github.com/guidone/node-red-contrib-chatbot/wiki/Start-conversation

It's possible to set some parameters of a **RedBot** node in a upstream node, for example in a text node to create the content of the message programmatically (the list of parameters that can be specidfied ins generally in the help page,  here for example https://github.com/guidone/node-red-contrib-chatbot/wiki/Message-node)
It's not a good practice to set the `type` (as you did in you inject payload), this is an internal parameter, it's subject to change and it's part of the abstraction the RedBot's node need to comunicate (-> unexpected results)

**Comment by luismanson** [comment]
Thanks @guidone, i have removed the "type"  parameter from my inject node and added transport parameter. Looking at "start conversation" article i noticed i was kinda building the flow backwards. 

thanks!
