### ISSUE TITLE
TypeError: msg.chat is not a function

### ISSUE THREAD

**Issue by ajinkyapuar** [guidone/node-red-contrib-chatbot#218]
I'm using the dialogflow.com node and its gives me this error. Below is my flow.

`[{"id":"8947382f.e4b698","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"25fce871.f31608","type":"chatbot-dialogflow","z":"8947382f.e4b698","dialogflow":"5ca98ddb.2c1bf4","language":"en","debug":false,"variable":"location","x":413.3973846435547,"y":237.27838325500488,"wires":[["a2dc51e8.86a33"],["a27c4f53.e7bed"]]},{"id":"a2dc51e8.86a33","type":"debug","z":"8947382f.e4b698","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":647.4030914306641,"y":198.44316291809082,"wires":[]},{"id":"a27c4f53.e7bed","type":"debug","z":"8947382f.e4b698","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":633.4031219482422,"y":308.44316482543945,"wires":[]},{"id":"1b0341bf.7b478e","type":"inject","z":"8947382f.e4b698","name":"","topic":"","payload":"where is the office?","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":187.5198745727539,"y":237.4693717956543,"wires":[["25fce871.f31608","253332be.498a0e"]]},{"id":"253332be.498a0e","type":"debug","z":"8947382f.e4b698","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":416.12055460611975,"y":87.45896657307942,"wires":[]},{"id":"5ca98ddb.2c1bf4","type":"chatbot-dialogflow-token","z":"","name":"myAgent"}]`

**Comment by guidone** [comment]
Hi @ajinkyapuar , you have to put a conversation node in front of it

<img width="912" alt="schermata 2018-06-28 alle 17 07 42" src="https://user-images.githubusercontent.com/502519/42043102-e8079d5e-7af5-11e8-889a-30cd2e1ecbac.png">

See also here

https://github.com/guidone/node-red-contrib-chatbot/wiki/Start-conversation

and here

https://github.com/guidone/node-red-contrib-chatbot/wiki/Conversation-node

**Comment by ajinkyapuar** [comment]
what about the transport in the conversation node? I'm using drift https://www.drift.com/ which isn't listed.

**Comment by ajinkyapuar** [comment]
ohhh. Is there a way I could just send the message and fetch the responses from the Dialogflow backend?

**Comment by guidone** [comment]
No, the purpose of the node is to be used with RedBot and not to be a general purpose node for DialogFlow, you can use a http request node, you can get the bash command (with curl) to make the request here

https://d.pr/i/QsXsqR

then you can extract the parameters and use them in the http request node
