### ISSUE TITLE
relying on the existence of `msg.payload.chatId` in "Telegram Sender" prevents from using some other nodes

### ISSUE THREAD

**Issue by cowchimp** [guidone/node-red-contrib-chatbot#22]
Hi.

First off, fantastic project! Thanks so much for your work.

I'm building a Telegram bot specifically, but appreciate that you make everything generic to use other platforms as well (I might want to start using Slack in the future).

The issue I encountered happens when I include some other "transformation node" (e.g. the built-in csv, html, json nodes) inside a flow that begins with the "Telegram Receiver" node and ends with the "Telegram Sender" node.
The problem is that those transformation nodes rely on their input being the `msg.payload` property, and they save their transformed output to the `msg.payload` property as well.
This means that any prior data saved on `msg.payload` is lost.
Specifically in the case of the "Telegram Sender" node this will mean it will no longer work because it expects `msg.payload.chatId` to exist ([relevant source-code](https://github.com/guidone/node-red-contrib-chatbot/blob/fc5ededefd399b1668d0ae897f5f120df8a85250/chatbot-telegram-receive.js#L332)).

From the convention I see in the built-in node-red nodes and some of the comunnity nodes as well, this is by-design and not a bug. Meaning `msg.payload` exists for direct "node-to-next-immediate-node" communication, not for data that should be persisted along with the message for the entire flow. For that type of longer-living persistence, I think the convention is to create another property on the `msg` object (like you do with `msg.originalMessage`). By using a custom property and not `payload`, it's a lot safer that another node won't overwrite it. This is, for example, how the built-in HTTP request&response nodes communicate which is similar to what you're trying to accomplish.

Please let me know if you need more info or assitance from me.
Thank you!

**Comment by guidone** [comment]
Thanks @cowchimp!

Can you tell how your flow is configured exactly? What it the last node before the Telegram sender?

All message nodes (like text, image, audio, etc) that are supposed to be connected to the Telegram sender have a line like this:

    var chatId = msg.payload.chatId || (originalMessage && originalMessage.chat.id);

that takes the _chatId_ from the payload or from the _originalMessage_.
That approach is working for a flow like this

https://github.com/guidone/node-red-contrib-chatbot#send-image

Here the http node is preserving the msg.originalMessage and the image node creates the payload using the id of the originalMessage.

This works as long as you use e message node (like text, image, audio, etc) to prepare the payload for the sender. You cannot go to the sender directly.
There's no message node for plain file (but I'm planning to create one), what node are you using before the Telegram sender?

**Comment by cowchimp** [comment]
Hi.

You are correct, of course.
It is my mistake I wasn't using the 'Message' node before the 'Sender' and that's what caused the issue.

Thanks again!

**Comment by guidone** [comment]
Thanks for your feedback, perhaps I'll include some detailed error message
in case the flow is going directly to the sender without passing through a
message node.

Guido
Il giorno sab 1 ott 2016 alle 20:00 cowchimp <notifications@github.com> ha
scritto:
