### ISSUE TITLE
Dialogflow node not passing intent and reset contexts

### ISSUE THREAD

**Issue by jflaflamme** [guidone/node-red-contrib-chatbot#221]
Hello @guidone 

Would it be a good idea to use the current topic as intent in the dialogflow node? 
Also having the option to set the resetcontexts to false would help often.

Or simply set before the node  msg.intent = 'theintent' and msg.resetContexts = false, something like that. Because I have really weird results from my dialogflow agents when not passing the intents :) 

Hope it is clear.
I could do a quick PR for that.

**Comment by guidone** [comment]
@jflaflamme yes please :-)

**Comment by Ruttolo** [comment]
Hi @guidone ,

have you scheduled an update of the node? (v1 to v2).
I read v2 supports audio input….. 
What about @jflaflamme's suggestion?

Many thanks!
