### ISSUE TITLE
Node Red Constant Reboot

### ISSUE THREAD

**Issue by Mohnki** [guidone/node-red-contrib-chatbot#224]
Good Evening

Please remove if I am wrong with this.

I have been using the chatbot for a while not and it has been brilliant. To the point where I rely on it very heavily. I specifically use the Telegram portion a lot.

Today for the first time things went bad. I have attached a screenshot of the log. It seems that something has changed and even updating has not helped.

Any help would be greatly appreciated.

<img width="960" alt="screenshot 2018-07-23 at 17 14 58" src="https://user-images.githubusercontent.com/6792816/43085709-f1e12930-8e9b-11e8-9756-01b2d0eb6598.png">

**Comment by guidone** [comment]
Hi,

It shouldn’t be any breaking changes in this version.
Have you tried downgrading it to the previous version?
It looks like a context json file is corrupted, can you try removinf that file? (It should be the <chatId>.json)

I’m not at my computer right now, we’ll fix it

**Comment by Mohnki** [comment]
The strangest thing is that I did not update anything. it just started doing this.

I will reinstall chatbot again and then if that file gives the same error I will remove it and see what happens.

I will then try an older version and let you know

**Comment by guidone** [comment]
I confirm it's a corrupted context file (in JSON), if you delete all files in the context directory il will work again.
Are there many files there? If it's not a privacy issue can I see them?

**Comment by Mohnki** [comment]
I had completely uninstalled node red and all modules and reinstalled everything seems to be online again.

I will keep an eye on it and it if happens again I'll get all those files together for you and send them through.

**Comment by guidone** [comment]
Perfect, thanks for the feedback
