### ISSUE TITLE
Documentation for nested messenger menu needed

### ISSUE THREAD

**Issue by nquam** [guidone/node-red-contrib-chatbot#225]
I've tried using Facebook's documentation for nested menus and it doesn't seem to be working properly for the messenger menu node. Standard postbacks and URLs show up but no matter how I formulate the nested menu through a function, it never shows in the results on my messenger menu.

**Comment by guidone** [comment]
I had to fix something, install `0.13.6`, here the updated documentation https://github.com/guidone/node-red-contrib-chatbot/wiki/Messenger-Menu-node

**Comment by nquam** [comment]
I updated my install and changed my function to match documentation and it works. Thanks for this!

**Comment by guidone** [comment]
🖖
