### ISSUE TITLE
Newbie: Nothing happening

### ISSUE THREAD

**Issue by jadster** [guidone/node-red-contrib-chatbot#228]
Hi there,

Just starting out with this node-red package. Had no trouble working with the node-red-contrib-telegrambot package with the exact same setup.

With this package however, I'm getting nowhere.

I've add the Telegram Receiver node and set up the Telegram config (botname and token).
=> Telegram receiver node says "connected".

Then I either:
- activate "debug" checkbox in the Telegram account config
- connecti node-red's standard debug node (with "complete message object") 
- connect this package's own Debug node

=> Upon sending a message to the bot (from a personal account), I get nothing in the browser JS console or the node-red debug window.

I'm running node-red 0.18.7 in a docker container on Mac OS.

How can I debug this?

**Comment by guidone** [comment]
what do you see in the system console (the bash shell where you launched node-red)?
Are you sure the access token is related to the chat you are using (I use RedBot with Telegram every day, it's strange it's not working)

**Comment by jadster** [comment]
Well no idea what was going on, but I revoked the token and used a new one: Voila. working fine.
Thanks for the impetus .

**Comment by guidone** [comment]
Good 🖖
