### ISSUE TITLE
Command not being recognised in group

### ISSUE THREAD

**Issue by TotallyInformation** [guidone/node-red-contrib-chatbot#23]
Hi, when using redbot with Telegram and using the command node. When my bot is added to a group, the incoming command is `/command@botname` instead of just `/command`.

This is expected behaviour as I understand it but the command node does not recognise the input so you have to add a second node which seems excessive and also isn't covered by the documentation.

It would be best if all the nodes were able to deal with `@botnetname` on the end of the command.

**Comment by guidone** [comment]
@TotallyInformation Ok, I see the bug, I'll fix soon

Thanks for the feedback

**Comment by guidone** [comment]
@TotallyInformation it's fixed in the 0.6.5-beta4, will release on stable tag in few days (there are some new nodes that might be unstable)

    npm install node-red-contrib-chatbot@0.6.5-beta4

**Comment by guidone** [comment]
Thanks for the feedback

**Comment by TotallyInformation** [comment]
MAny thanks, look forward to the update.
