### ISSUE TITLE
Facebook - Unable to get profile info for user

### ISSUE THREAD

**Issue by lexoyo** [guidone/node-red-contrib-chatbot#234]
Hello
Thank you for this great nodes, I love how easy it is to use it with telegram
For Facebook, I am struggling with this error message: "Unable to get profile info for user 15610324xxxxxx - (#100) Insufficient permission to access user profile"
Would you know where that comes from?
Have a nide day!
![screenshot from 2018-08-18 17-24-08](https://user-images.githubusercontent.com/715377/44300708-e662c300-a30b-11e8-9fe0-69ba7d3c3f5a.png)

**Comment by lexoyo** [comment]
I think this was due to my Facebook messenger app status. I published it in Facebook, now it is live like this:

![screenshot from 2018-08-19 22-38-01](https://user-images.githubusercontent.com/715377/44312984-bd702a00-a400-11e8-848e-cc305e8ce616.png)


But now it gives me another error when a user sends a message to the bot:
```
Unable to get profile info for user 2017023xxxxxxxxx - Unsupported get request. Object with ID '2017023xxxxxxxx' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api
```

**Comment by guidone** [comment]
Hi @lexoyo , sorry for the late answer.
I had similar problem in the past, I had to regenerate the access token and it worked, let me know if it works

**Comment by lexoyo** [comment]
Hi again
I'm sorry to bother you, it's probably in the config of my facebook app
The middleware which throws the error is the one which retrieves the user profile, and [in particular this line](https://github.com/guidone/node-red-contrib-chatbot/blob/master/lib/platforms/facebook-chat.js#L589), if I change the requested fields from `fields: 'first_name,last_name,profile_pic,locale,timezone,gender'` to `fields: 'first_name,last_name` it works
I can't find where I missed these access rights :-/

**Comment by guidone** [comment]
Ok, it's good to know. It's worth writing to something about it in the wiki, I'll get back to you by the eod

**Comment by lexoyo** [comment]
Let me know how I can help
Maybe change the code and make these rights an option?
Or write in the wiki
Bye!

**Comment by guidone** [comment]
@lexoyo after some reading seems like the field causing the problem is `profile_pic` which is not used in RedBot, so I left just first_name, last_name and locale which are part of the core (always available).
So no need for configurable option for now.

Thanks very much for the feedback, I guess this problem was afflicting many users.

🖖 Guido

**Comment by lexoyo** [comment]
woohoo, thx!
:vulcan_salute:

**Comment by lexoyo** [comment]
just a question, would it be hard to add a platform? I'm thinking hangout chat

**Comment by guidone** [comment]
No, you can make some experiments with

https://github.com/guidone/node-red-contrib-chatbot/wiki/Universal-Connector-node

**Comment by lexoyo** [comment]
Ok, I'll see about that
I did this for [hangout chat](https://gsuite.google.com/products/chat/)
https://www.npmjs.com/package/node-red-contrib-hangouts-chat
