### ISSUE TITLE
The link "2. Examples" under section "Documentation" on the README.md is broken.

### ISSUE THREAD

**Issue by janvda** [guidone/node-red-contrib-chatbot#235]
see readme at https://github.com/guidone/node-red-contrib-chatbot
This link is referring to an empty page.

Note also that the link "3. Advanced Examples" is referring to a page that contains much more than only advanced examples.

**Comment by guidone** [comment]
Thanks @janvda, this section need some attention, I'm working on it

**Comment by guidone** [comment]
Links fixed.

Thanks for the feedback
