### ISSUE TITLE
Waiting node doesn't send msg

### ISSUE THREAD

**Issue by Ruttolo** [guidone/node-red-contrib-chatbot#238]
Hi,
I'm having some problems related to waiting node: it correctly sends the message with type "action" and I can recognize on my telegram chat "typing…" but after that, it doesn't send the real message.

Thanks,
Alessandro

**Comment by guidone** [comment]
How the flow looks like?
(Example is missing the wiki)

**Comment by Ruttolo** [comment]
Here is the flow: I can see "typing…" on telegram but once it ends no message is recevied.

![image](https://user-images.githubusercontent.com/42807791/44900576-3591f600-ad05-11e8-9e51-c451d60e803d.png)

**Comment by guidone** [comment]
Ok meanwhile I've added an example

https://github.com/guidone/node-red-contrib-chatbot/wiki/Waiting-node

**Comment by Ruttolo** [comment]
Ok but putting both nodes in parallel I receive message instantly and "typing…" action disappears very quickly. Am I  making some mistakes?
Thanks again for your time!

**Comment by guidone** [comment]
Yes it's normal, the message just triggers the waiting status on the client, the client removes it after a timeout or after a message comes in (at least Telegram does it).
