### ISSUE TITLE
Command node does not recognise parameters? (Telegram)

### ISSUE THREAD

**Issue by TotallyInformation** [guidone/node-red-contrib-chatbot#24]
If I have a command node `/ison`, it recognises it if that is all that is typed. However, if I type `/ison all` or `/ison iron` the command isn't recognised - that can't be right can it?

**Comment by guidone** [comment]
@TotallyInformation yes, absolutely possible. I can fix that.

Stay tuned :-)

**Comment by guidone** [comment]
@TotallyInformation Ok, it should be fixed, also parameters are stored in the chat context

`npm install node-red-contrib-chatbot@0.6.5-beta5`

to get the parameters

`var chat = msg.chat();
chat.get('param1') // first param;
chat.get('param2') // second param;`

**Comment by guidone** [comment]
Thanks for the feedback

**Comment by TotallyInformation** [comment]
Thanks, I'll test it as soon as I can.
