### ISSUE TITLE
How add restriction in bot telegram

### ISSUE THREAD

**Issue by dedynobre** [guidone/node-red-contrib-chatbot#242]
I created a bot telegram and it is working normal.
But at the moment, even putting the chatid, the bot is becoming available to everyone.

How to restrict access?

**Comment by guidone** [comment]
Hi @dedynobre 

You should use the [Authorized node](https://github.com/guidone/node-red-contrib-chatbot/wiki/Authorized-node).

I will update the help in this page shortly

**Comment by dedynobre** [comment]
Hi @guidone 

Yesterday I found this node by chance and solved the access problem.

Thank you!

**Comment by guidone** [comment]
🖖
