### ISSUE TITLE
Connectivity problems with Slack

### ISSUE THREAD

**Issue by selfyguy** [guidone/node-red-contrib-chatbot#244]
I followed all of the steps in this: https://github.com/guidone/node-red-contrib-chatbot/wiki/Slack-Receiver-node

Initially messages were not coming through at all.

Now the following two messages show up in debug when I sent a single message "yess" in my slack bot app
```
9/17/2018, 4:13:36 PMnode: 8546889f.5b3178
msg.payload : Object
object
type: "message"
chatId: "DCUMQV3KM"
userId: "UCUK2TZ28"
ts: "2018-09-17T10:43:34.000Z"
transport: "slack"
inbound: true
content: "yess"

9/17/2018, 4:13:40 PMnode: 54e98567.fb87fc
msg : error
"Error: no_text"

```
But messages back to Slack channel are still not working

Here is the setup
[https://red-bot.slack.com/files/UCTDGFJ01/FCU8C7E7K/image.png](https://red-bot.slack.com/files/UCTDGFJ01/FCU8C7E7K/image.png)

**Comment by guidone** [comment]
Hi @selfyguy what do you mean with "messages to Slack channel"?

The chatbot is only able to interact with the user connected to the chatbot, not a generic channel like #general 
Perhaps there's a way with Slack to mention a chatbot user from a channel, but I've never tested this

**Comment by selfyguy** [comment]
Oh, by "channel" i meant, the slack bot. I used "channel" to refer to the medium of communication to the bot.
I am also having intermittent issues with Telegram where some messages are not received even after setting polling time to 10ms.

I suspect this is because of exact duplicate bot configurations (having exact key) - the one in the dropdown under "Bot configuration". It also shows up in the config node list pane as ununsed ones. Does each configuration spin up a polling instance?

![image](https://user-images.githubusercontent.com/34223101/45807244-b169d780-bce0-11e8-9484-de474086caa4.png)

**Comment by guidone** [comment]
Yes @selfyguy, each configuration starts a polling instance but only if it's used by some node.
Keep an eye on the system console to check which instance is actually started.

In case there's a polling conflict you will see the warning in the console
