### ISSUE TITLE
how to...

### ISSUE THREAD

**Issue by ghost** [guidone/node-red-contrib-chatbot#246]
![1](https://user-images.githubusercontent.com/36772889/45707484-ad767200-bb87-11e8-8389-f8720ee02b24.JPG)
i dont understand how to make it on/off based on the button i clicked in the bot. i must miss some node in between, no?

thank you!

**Comment by guidone** [comment]
Hi @AsafDAVIDOF 

Assuming that the blue nodes trigger their actions when a message comes in (not matter what is present in the payload), then the `Rules node` is your guy

<img width="748" alt="on-off" src="https://user-images.githubusercontent.com/502519/45760273-fd0d7a00-bc29-11e8-8fea-b76e333a9e97.png">

The `Rule node` filters any received message and redirects the flow to the first or second output if it detects a _command_ `/on` or `/off`

<img width="499" alt="rule_node" src="https://user-images.githubusercontent.com/502519/45760402-41991580-bc2a-11e8-991f-3abb187180f5.png">

If the message is not a `/on` or `/off` then the flow is redirected to the third pin which sends to Telegram the two inline buttons with payload _"/on"_ and _"/off"_

<img width="499" alt="button_node" src="https://user-images.githubusercontent.com/502519/45760505-82912a00-bc2a-11e8-84f5-1e62d32cdbd9.png">

I've not tested this but it should work
