### ISSUE TITLE
Add group in Bot permission

### ISSUE THREAD

**Issue by dedynobre** [guidone/node-red-contrib-chatbot#249]
Hi!

I do not know if this is possible but would have like in the field to add the liberated users to access the bot put a group?
So that whenever someone needs to access the bot I would add this staff to the group.

As the number of users is growing I have to go add each user directly in the configuration of the network node.

Would it be possible to put in the chatid instead of individual chatid, to be of the group?

**Comment by guidone** [comment]
You can use the example https://github.com/guidone/node-red-contrib-chatbot/wiki/Authorized-node

Here in the middleware that checks the authorization

```javascript
// this middleware will be execute before any 'in' middleware
node.chat.use(function(message) {
  const chat = message.chat();
  // always return a promise, this ensure it's a promise even if using the 
  // sync memory context
  return Promise.resolve(chat.get('chatId'))
    .then(chatId => Promise.resolve(myAuthScheme(chatId)))
    .then(authorized => Promise.resolve(chat.set('authorized', authorized)));
});
```
you just have to implement the method `myAuthScheme` that returns true or false. This method should check that the chatId exists in a file or an array (stored for example in the node context) and you can manipulate this file or array in Node-RED with the chatbot or with ui-dashboad

**Comment by dedynobre** [comment]
What would this deployment look like.
I did not understand how to use this function.
I would like the list of users to be in an external list on the server where the NR is running.

**Comment by mrvasilyev** [comment]
Hi there,

I am trying use Extend Chat for external AuthSchema.
I created code in node (it's a test to check)

`node.chat.use(function(message) {
  var chat = message.chat();
  **function myAuthScheme(chatId) {
      var authorized
      if (chatId == '51576055') {
          authorized = true;
          console.log(chatId, authorized)
          return authorized;
      } else {
          authorized = false;
          return authorized;
      }**
  }
  // always return a promise, this ensure it's a promise even if using the 
  // sync memory context
  return Promise.resolve(chat.get('chatId'))
    .then(chatId => Promise.resolve(myAuthScheme(chatId)))
    .then(authorized => Promise.resolve(chat.set('authorized', authorized)));
});`

But I can error in console log

`51576055 true

WARNING: a middleware is returning an empty payload in message

-------------------------- Error in chat-platform.js ---------------------------

TypeError: Cannot read property 'new_chat_members' of undefined

at /data/node_modules/chat-platform/chat-platform.js:378:13


function(message) {

var botMsg = message.originalMessage;

return new Promise(function(resolve) {

if (_.isArray(botMsg.new_chat_members) && !_.isEmpty(botMsg.new_chat_members)) {

message.payload.newUsers = botMsg.new_chat_members;

message.payload.type = 'event';

message.payload.eventType = 'new-user';

resolve(message);

} else {

resolve(message);

}

});

}


15 Feb 09:36:32 - [error] [chatbot-telegram-node:3e5ae8c1.0dd9f8] TypeError: Cannot read property 'new_chat_members' of undefined`

Could you tell me please what's wrong, please?
