### ISSUE TITLE
How do I use the Voice node?

### ISSUE THREAD

**Issue by TotallyInformation** [guidone/node-red-contrib-chatbot#25]
I can type in a message manually but I need the voice node to pass on a message created in an upstream node. Can this be done?

**Comment by guidone** [comment]
If I correctly understood you want to programmatically prepare the vocal message right?

It's sufficient to leave the textarea blank and send a string from the upstream node (for example a function node). As long as you keep the original msg node and, of course, just change the payload, everything should work. Also the message node works this way, so for example in the function node

    msg.payload = 'this is my string';
    return msg;

Thanks for the feedback, this might be a good topic for a blog post

**Comment by TotallyInformation** [comment]
Thanks for that. You might want to update the built-in help information too as this is rather light at present and that makes it very hard to use the nodes.

**Comment by guidone** [comment]
@TotallyInformation yes I'm updating some node docs, thanks
