### ISSUE TITLE
Message is too long

### ISSUE THREAD

**Issue by dedynobre** [guidone/node-red-contrib-chatbot#254]
This error is a limitation of the Telegram API?

**Comment by guidone** [comment]
Yes, there is a limitation to 4096 chars.

Is it possible that the error in your other issue is due to the length of the message?

**Comment by dedynobre** [comment]
Ah, ok..
In fact the other problem may be yes.
But I used another component of the telegram and it sends normally.
When I changed the pro bot I use its component does not work.

**Comment by guidone** [comment]
ok, let me check if there's a way to support long messages in the core of redbot

**Comment by dedynobre** [comment]
This is the same as I use and send normally:
![image](https://user-images.githubusercontent.com/8119694/47658194-52b23c00-db71-11e8-92b4-d27d6c8eadbe.png)

**Comment by guidone** [comment]
Is this "Telegram sender" in blue the RedBot sender? It looks like this

https://flows.nodered.org/node/node-red-contrib-telegrambot

**Comment by dedynobre** [comment]
This way I posted before it sends a message of the size of the string that it limits in the function normally.
On the test day he divided the message into four other messages.

This is the use for notification and its use with the bot. I can test without disturbing the bot. It's all right step for the bot.

In this case with the bot does not work.

**Comment by dedynobre** [comment]
> Is this "Telegram sender" in blue the RedBot sender? It looks like this
> 
> https://flows.nodered.org/node/node-red-contrib-telegrambot

Yes

**Comment by dedynobre** [comment]
> Is this "Telegram sender" in blue the RedBot sender? It looks like this
> 
> https://flows.nodered.org/node/node-red-contrib-telegrambot

It also displays the very long message error but aliasing works.

**Comment by dedynobre** [comment]
Another thing, using the node conversation leaving the fixed chatid it sent the correct message, I just could not pass the chatid automatically

**Comment by guidone** [comment]
The message too long bug was fixed, in order to pass a chatId programmatically check here

https://github.com/guidone/node-red-contrib-chatbot/wiki/Conversation-node

**Comment by dedynobre** [comment]
Do you have to update the component?

**Comment by dedynobre** [comment]
My configuration is:

![image](https://user-images.githubusercontent.com/8119694/48980785-b702e580-f0b4-11e8-8160-ae819bbf14ba.png)

**Comment by dedynobre** [comment]
![image](https://user-images.githubusercontent.com/8119694/49090602-34f5f680-f245-11e8-9253-04673814fd2f.png)
