### ISSUE TITLE
Some vulnerabilities because deprecated slack module used

### ISSUE THREAD

**Issue by m101a** [guidone/node-red-contrib-chatbot#255]
Hi.

I'm trying to install node-red-contrib-chatbot and npm finds some vulnerabilities.
All but one are associated with an depricated Slack client.

Do you plan to magrate slack to current version?

[npm audit log.txt](https://github.com/guidone/node-red-contrib-chatbot/files/2511846/npm.audit.log.txt)

**Comment by guidone** [comment]
@m101a it's ready in `0.15.6`

Thanks for the feedback
