### ISSUE TITLE
Error to send Message

### ISSUE THREAD

**Issue by dedynobre** [guidone/node-red-contrib-chatbot#256]
Hi,

I am receive error message to send message:

Flow:
![image](https://user-images.githubusercontent.com/8119694/47581124-f9ef6300-d926-11e8-85fe-a847b329ecdb.png)

Error:
![image](https://user-images.githubusercontent.com/8119694/47581154-0d9ac980-d927-11e8-9850-bcc9e40befdb.png)

Debug:
![image](https://user-images.githubusercontent.com/8119694/47581180-1be8e580-d927-11e8-85a3-6975aae886e6.png)

**Comment by dedynobre** [comment]
The function is:
`var a = msg.payload.length;
var b = a - 1;
var x;
var msg1;
var j = "";
j += "\n";
var sdata2;

var cnt1 = 0;
var cnt2 = a;
var cntd;

for(x = 0; x < a; x++ ){
    
    cnt1++;
    cnt2--;
    
    var slinha = msg.payload[x].Linha;
    var sjust = msg.payload[x].JUSTIFICATIVA
    var stpprd = msg.payload[x].Tipo_Parada
    
    //var sdata = msg.payload[x].Inicio;
    var dt1 = new Date(msg.payload[x].Inicio);
    var sdt1 = {
	    'm':	dt1.getMonth() + 1,
	    'd':	dt1.getDate(),
	    'a':	dt1.getFullYear(),
	    'h':	dt1.getHours(),
	    'mn':	dt1.getMinutes(),
	    's':	dt1.getMilliseconds()
    }
    
    if(sdt1.mn < 10) { sdt1.mn = "0"+sdt1.mn; } else { sdt1.mn = sdt1.mn ;}
    
    var sdata1 = sdt1.d+"/"+sdt1.m+"/"+sdt1.a+" "+sdt1.h+":"+sdt1.mn+"h";
    
    var dt2 = new Date(msg.payload[x].Fim);
    var sdt2 = {
	    'm':	dt2.getMonth() + 1,
	    'd':	dt2.getDate(),
	    'a':	dt2.getFullYear(),
	    'h':	dt2.getHours(),
	    'mn':	dt2.getMinutes(),
	    's':	dt2.getMilliseconds()
    }
    
    if(sdt2.mn < 10) { sdt2.mn = "0"+sdt2.mn; } else { sdt2.mn = sdt2.mn ;}
    if(sdt2.a < sdt1.a) { 
        sdata2 = "___Parada não finalizada___"; 
    } else {
        sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    }
    
    //sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    
    j += "***"+slinha+"***"+": "+sdata1+" <->" + sdata2+" |TP| "+"***"+stpprd+"***"+" |JOP| "+sjust;
    j += "\n";
    
    var tamanho = j.length;
    
    
    if (tamanho > 3000 && tamanho <= 4000){
        
        node.send({payload : j});
        
        j = "";
    }
    if (cnt2 === 0){
    
       node.send({payload : j});     

    }
        
        
}`

**Comment by dedynobre** [comment]
`var a = msg.payload.length;
var b = a - 1;
var x;
var msg1;
var j = "";
j += "\n";
var sdata2;

var cnt1 = 0;
var cnt2 = a;
var cntd;

for(x = 0; x < a; x++ ){
    
    cnt1++;
    cnt2--;
    
    var slinha = msg.payload[x].Linha;
    var sjust = msg.payload[x].JUSTIFICATIVA
    var stpprd = msg.payload[x].Tipo_Parada
    
    //var sdata = msg.payload[x].Inicio;
    var dt1 = new Date(msg.payload[x].Inicio);
    var sdt1 = {
	    'm':	dt1.getMonth() + 1,
	    'd':	dt1.getDate(),
	    'a':	dt1.getFullYear(),
	    'h':	dt1.getHours(),
	    'mn':	dt1.getMinutes(),
	    's':	dt1.getMilliseconds()
    }
    
    if(sdt1.mn < 10) { sdt1.mn = "0"+sdt1.mn; } else { sdt1.mn = sdt1.mn ;}
    
    var sdata1 = sdt1.d+"/"+sdt1.m+"/"+sdt1.a+" "+sdt1.h+":"+sdt1.mn+"h";
    
    var dt2 = new Date(msg.payload[x].Fim);
    var sdt2 = {
	    'm':	dt2.getMonth() + 1,
	    'd':	dt2.getDate(),
	    'a':	dt2.getFullYear(),
	    'h':	dt2.getHours(),
	    'mn':	dt2.getMinutes(),
	    's':	dt2.getMilliseconds()
    }
    
    if(sdt2.mn < 10) { sdt2.mn = "0"+sdt2.mn; } else { sdt2.mn = sdt2.mn ;}
    if(sdt2.a < sdt1.a) { 
        sdata2 = "___Parada não finalizada___"; 
    } else {
        sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    }
    
    //sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    
    j += "***"+slinha+"***"+": "+sdata1+" <->" + sdata2+" |TP| "+"***"+stpprd+"***"+" |JOP| "+sjust;
    j += "\n";
    
    var tamanho = j.length;
    
    
    if (tamanho > 3000 && tamanho <= 4000){
        
        node.send({payload : j});
        
        j = "";
    }
    if (cnt2 === 0){
    
       node.send({payload : j});     

    }
        
        
}`

**Comment by dedynobre** [comment]
``var a = msg.payload.length;
var b = a - 1;
var x;
var msg1;
var j = "";
j += "\n";
var sdata2;

var cnt1 = 0;
var cnt2 = a;
var cntd;

for(x = 0; x < a; x++ ){
    
    cnt1++;
    cnt2--;
    
    var slinha = msg.payload[x].Linha;
    var sjust = msg.payload[x].JUSTIFICATIVA
    var stpprd = msg.payload[x].Tipo_Parada
    
    //var sdata = msg.payload[x].Inicio;
    var dt1 = new Date(msg.payload[x].Inicio);
    var sdt1 = {
	    'm':	dt1.getMonth() + 1,
	    'd':	dt1.getDate(),
	    'a':	dt1.getFullYear(),
	    'h':	dt1.getHours(),
	    'mn':	dt1.getMinutes(),
	    's':	dt1.getMilliseconds()
    }
    
    if(sdt1.mn < 10) { sdt1.mn = "0"+sdt1.mn; } else { sdt1.mn = sdt1.mn ;}
    
    var sdata1 = sdt1.d+"/"+sdt1.m+"/"+sdt1.a+" "+sdt1.h+":"+sdt1.mn+"h";
    
    var dt2 = new Date(msg.payload[x].Fim);
    var sdt2 = {
	    'm':	dt2.getMonth() + 1,
	    'd':	dt2.getDate(),
	    'a':	dt2.getFullYear(),
	    'h':	dt2.getHours(),
	    'mn':	dt2.getMinutes(),
	    's':	dt2.getMilliseconds()
    }
    
    if(sdt2.mn < 10) { sdt2.mn = "0"+sdt2.mn; } else { sdt2.mn = sdt2.mn ;}
    if(sdt2.a < sdt1.a) { 
        sdata2 = "___Parada não finalizada___"; 
    } else {
        sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    }
    
    //sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    
    j += "***"+slinha+"***"+": "+sdata1+" <->" + sdata2+" |TP| "+"***"+stpprd+"***"+" |JOP| "+sjust;
    j += "\n";
    
    var tamanho = j.length;
    
    
    if (tamanho > 3000 && tamanho <= 4000){
        
        node.send({payload : j});
        
        j = "";
    }
    if (cnt2 === 0){
    
       node.send({payload : j});     

    }
        
        
}``

**Comment by dedynobre** [comment]
var a = msg.payload.length;
var b = a - 1;
var x;
var msg1;
var j = "";
j += "\n";
var sdata2;

var cnt1 = 0;
var cnt2 = a;
var cntd;

for(x = 0; x < a; x++ ){
    
    cnt1++;
    cnt2--;
    
    var slinha = msg.payload[x].Linha;
    var sjust = msg.payload[x].JUSTIFICATIVA
    var stpprd = msg.payload[x].Tipo_Parada
    
    //var sdata = msg.payload[x].Inicio;
    var dt1 = new Date(msg.payload[x].Inicio);
    var sdt1 = {
	    'm':	dt1.getMonth() + 1,
	    'd':	dt1.getDate(),
	    'a':	dt1.getFullYear(),
	    'h':	dt1.getHours(),
	    'mn':	dt1.getMinutes(),
	    's':	dt1.getMilliseconds()
    }
    
    if(sdt1.mn < 10) { sdt1.mn = "0"+sdt1.mn; } else { sdt1.mn = sdt1.mn ;}
    
    var sdata1 = sdt1.d+"/"+sdt1.m+"/"+sdt1.a+" "+sdt1.h+":"+sdt1.mn+"h";
    
    var dt2 = new Date(msg.payload[x].Fim);
    var sdt2 = {
	    'm':	dt2.getMonth() + 1,
	    'd':	dt2.getDate(),
	    'a':	dt2.getFullYear(),
	    'h':	dt2.getHours(),
	    'mn':	dt2.getMinutes(),
	    's':	dt2.getMilliseconds()
    }
    
    if(sdt2.mn < 10) { sdt2.mn = "0"+sdt2.mn; } else { sdt2.mn = sdt2.mn ;}
    if(sdt2.a < sdt1.a) { 
        sdata2 = "___Parada não finalizada___"; 
    } else {
        sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    }
    
    //sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    
    j += "***"+slinha+"***"+": "+sdata1+" <->" + sdata2+" |TP| "+"***"+stpprd+"***"+" |JOP| "+sjust;
    j += "\n";
    
    var tamanho = j.length;
    
    
    if (tamanho > 3000 && tamanho <= 4000){
        
        node.send({payload : j});
        
        j = "";
    }
    if (cnt2 === 0){
    
       node.send({payload : j});     

    }
        
        
}

**Comment by guidone** [comment]
Hi @dedynobre, what nodes before these highlighted with the arrow

![47581124-f9ef6300-d926-11e8-85fe-a847b329ecdb](https://user-images.githubusercontent.com/502519/47636112-8718fe80-db57-11e8-94ce-ce66ed26f80c.png)

If there isn't any receiver node going upstream from here, you at least have to put a [conversation node](https://github.com/guidone/node-red-contrib-chatbot/wiki/Conversation-node).

I can improve the error message in case something is sent to the RedBot nodes without the proper payload

Thanks for the feedback

**Comment by dedynobre** [comment]
On the other bot that is running the function is this:
var a = msg.payload.length;
var b = a - 1;
var x;
var msg1;
var j = "";
j += "\n";
var sdata2;

for(x = 0; x < a; x++ ){
    
    var slinha = msg.payload[x].Linha;
    var sjust = msg.payload[x].JUSTIFICATIVA
    var stpprd = msg.payload[x].Tipo_Parada
    
    //var sdata = msg.payload[x].Inicio;
    var dt1 = new Date(msg.payload[x].Inicio);
    var sdt1 = {
	    'm':	dt1.getMonth() + 1,
	    'd':	dt1.getDate(),
	    'a':	dt1.getFullYear(),
	    'h':	dt1.getHours(),
	    'mn':	dt1.getMinutes(),
	    's':	dt1.getMilliseconds()
    }
    
    if(sdt1.mn < 10) { sdt1.mn = "0"+sdt1.mn; } else { sdt1.mn = sdt1.mn ;}
    
    var sdata1 = sdt1.d+"/"+sdt1.m+"/"+sdt1.a+" "+sdt1.h+":"+sdt1.mn+"h";
    
    var dt2 = new Date(msg.payload[x].Fim);
    var sdt2 = {
	    'm':	dt2.getMonth() + 1,
	    'd':	dt2.getDate(),
	    'a':	dt2.getFullYear(),
	    'h':	dt2.getHours(),
	    'mn':	dt2.getMinutes(),
	    's':	dt2.getMilliseconds()
    }
    
    if(sdt2.mn < 10) { sdt2.mn = "0"+sdt2.mn; } else { sdt2.mn = sdt2.mn ;}
    if(sdt2.a < sdt1.a) { 
        sdata2 = "___Parada não finalizada___"; 
    } else {
        sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    }
    
    //sdata2 = sdt2.d+"/"+sdt2.m+"/"+sdt2.a+" "+sdt2.h+":"+sdt2.mn+"h";
    
    j += "***"+slinha+"***"+": "+sdata1+" <->" + sdata2+" |TP| "+"***"+stpprd+"***"+" |JOP| "+sjust;
    j += "\n";
    
}

msg.payload = [
    
    j
    
];

return msg;

**Comment by dedynobre** [comment]
I believe that this part the next node is not recognizing:
![image](https://user-images.githubusercontent.com/8119694/47657263-77a5af80-db6f-11e8-885f-0d1f3256856a.png)

**Comment by dedynobre** [comment]
![image](https://user-images.githubusercontent.com/8119694/47658163-3f9f6c00-db71-11e8-8a15-6028190c0047.png)

**Comment by dedynobre** [comment]
Reopen

**Comment by dedynobre** [comment]
It's working.
