### ISSUE TITLE
Telegram Unhandled rejection TypeError

### ISSUE THREAD

**Issue by cnavigato** [guidone/node-red-contrib-chatbot#26]
What might be the problem with this error?

Unhandled rejection TypeError: Cannot read property 'get' of undefined
    at TelegramBotNode.handleMessage (/home/chris/.node-red/node_modules/node-red-contrib-chatbot/chatbot-telegram-receive.js:160:39)

**Comment by guidone** [comment]
@cnavigato can you tell me which NodeRed version are you using?

**Comment by TomCompiles** [comment]
I was having a similar problem with the FacebookHandler,
when using version 0.15 or 0.15.1 of node-red.

When I downgraded to version 0.14.6 it worked again

**Comment by guidone** [comment]
It appears that the global context in NodeRed is not present, that is strange.

I've upgraded to 0.15.1 but I was not able to reproduce the error, I've been working with 0.15.0 for days and I never got this error, I also inspected the changed files from 0.15.0 to 0.15.1 but nothing touches the contexts in Node-Red.

- do you have something in you configuration for the key *functionGlobalContext*?
- is your flow working in a particular environment (like Raspberry)?
- can you reproduce it in a small flow that you can send over (without the chatbot token of course)?

I've a beta version, I'll release it soon, you can try if the bug can be reproduced with the bet

```npm install node-red-contrib-chatbot@0.6.6-beta6```

Thanks for the feedback

**Comment by monkeydave** [comment]
I am new to node-red and I am also receiving the error, I tried your beta and I still got the error.

This is my system setup
Ubuntu 16.04.1 LTS
Node-RED version: v0.15.1
Node.js  version: v4.6.1
npm version 2.15.9

In my settings.js I have the following

```
functionGlobalContext: {
        // os:require('os'),
        // octalbonescript:require('octalbonescript'),
        // jfive:require("johnny-five"),
        // j5board:require("johnny-five").Board({repl:false})
},
```

**Comment by bseishen** [comment]
Also having the same issue.
Ubuntu 16.04.1 LTS
Node-RED version: v0.15.2
Node.js version: v4.6.2
npm version 3.5.2

**Comment by bseishen** [comment]
Reverted to Node-RED 14.6, then installed 15.2 again. Seem to have fix the problem.

**Comment by guidone** [comment]
@bseishen this bug is giving me a really hard time, does it happen sistematically or sometimes?

Is Node-RED crashing at the very first message it receives or after a while?

Is there any particular node-red plugin that can cause this side effect (for example something that was no longer present after you reinstalled version 15.2)?

**Comment by aleonnet** [comment]
Hi @guidone,
Sorry but, I'm having the same issue on a Raspberry Pi 3 (Node-RED version: v0.15.2, Node.js  version: v4.6.1, Linux 4.4.21-v7+ arm LE)

<<Unhandled rejection TypeError: Cannot read property 'get' of undefined
    at TelegramBotNode.handleMessage (/root/.node-red/node_modules/node-red-contrib-chatbot/chatbot-telegram-receive.js:182:39)
>>

Already figured out what is going on?

Thanks!

**Comment by bseishen** [comment]
@guidone Only other package installed before this was node-red-contrib-telegrambot. Other than that it was a clean install of Ubuntu server. Node-Red is crashing at the very first message. Now I'm pretty new at Node.js/NPM/Node-Red so could be user error.

**Comment by guidone** [comment]
@bseishen I'm preparing a patch for that, it's just a more defensive code since I still cannot figure out why Node-RED is returning a null global context (it should not)

**Comment by aleonnet** [comment]
Just for you guys to know, the node-red-contrib-telegrambot works perfectly.

**Comment by guidone** [comment]
Ok

```npm install node-red-contrib-chatbot@0.6.6```

should fix the problem, at least it doesn't break if the global context is not available.
Sorry it took so long to fix.
