### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by franksto** [guidone/node-red-contrib-chatbot#263]
msg : string[55]
"Installation of module node-red-contrib-chatbot failed:"
15.11.2018, 10:58:30msg : string[42]
"------------------------------------------"
15.11.2018, 10:58:30msg : string[5371]
"npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0↵npm WARN deprecated scmp@0.0.3: scmp v2 uses improved core crypto comparison since Node v6.6.0↵↵> grpc@1.16.0 install /usr/local/addons/redmatic/var/node_modules/node-red-contrib-chatbot/node_modules/grpc↵> node-pre-gyp install --fallback-to-build --library=static_library↵↵node-pre-gyp WARN Using request for node-pre-gyp https download ↵node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.16.0/node-v57-linux-arm-unknown.tar.gz ↵node-pre-gyp WARN Pre-built binaries not found for grpc@1.16.0 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) ↵gyp ERR! configure error ↵gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.↵gyp ERR! stack at PythonFinder.failNoPython (/usr/local/addons/redmatic/lib/n..."
15.11.2018, 10:58:30
msg : string[42]

**Comment by guidone** [comment]
looks like python is not installed, but this is with some redbot dependency
