### ISSUE TITLE
Provide support for Slack buttons

### ISSUE THREAD

**Issue by jphillips-bp3** [guidone/node-red-contrib-chatbot#265]
Provide support for Slack message buttons as per: [https://api.slack.com/docs/message-buttons](https://api.slack.com/docs/message-buttons)

**Comment by guidone** [comment]
Inline buttons are already supported

https://github.com/guidone/node-red-contrib-chatbot/wiki/Buttons-node

This is a generic node, means that works for FB, Telegram, etc so the list of button-related features is limited.
In what are you interested here (https://api.slack.com/docs/message-buttons) that you cannot find in the generic node?

**Comment by jphillips-bp3** [comment]
Perfect thank you. One of my developers had literally found this before you responded, so I will close the ticket and give it a go.

**Comment by guidone** [comment]
🖖
