### ISSUE TITLE
Dialogflow node ignores small talk intent matches

### ISSUE THREAD

**Issue by sriramsv** [guidone/node-red-contrib-chatbot#266]
Hi @guidone,

I am unable to get the small talk feature which is enabled in my dialogflow account to be passed on to the dialogflow node in node-red.  It is always ignored and I get a "No match intent" response.

**Comment by guidone** [comment]
Hi @sriramsv let me check this, this feature was not present in the first version, totally missed it.

Thanks for the feedback
