### ISSUE TITLE
How to setup Slack Request URL for interactive message and app_mention event?

### ISSUE THREAD

**Issue by mmanak** [guidone/node-red-contrib-chatbot#267]
I am using 'Generic Template' node to send options to user using postback buttons. But when button is clicked, there is an error to setup 'Request URL'. What should this Request URL be?

**Comment by guidone** [comment]
It' something missing in the documentation, you have to set up the callback url here

https://d.pr/i/UgSOEU

You will need ngrok in the development environment.
I'll write some documentation on it.

**Comment by guidone** [comment]
@mmanak I've updated the docs

https://github.com/guidone/node-red-contrib-chatbot/wiki/Slack-Receiver-node

**Comment by mmanak** [comment]
Thanks!
So now when postback button is pressed I receive 'OK' message from Bot. And also the type of message received (Button selection) is always 'message' instead of 'interactive message'. So there is no way to know if this is a response of selection of buttons. Basically, I want to add switch after 'Slack Receiver' to identify the messages. How can we achieve this?

**Comment by guidone** [comment]
Ok that's a good question. Perhaps a wiki page on this could be useful.

I'm following the pattern of Telegram: messages starting with a "/" are commands that can be filtered by a [rule node](https://github.com/guidone/node-red-contrib-chatbot/wiki/Rules-node)

In this way you can assign a command-like text to each button ("/button1_pressed") and then put a rules node just after the receiver and route the flow appropriately

https://d.pr/i/b9VUnS

**Comment by mmanak** [comment]
Great! That worked
One last thing.. How can I stop Bot from responding with message 'OK'? Can I change this message?

**Comment by guidone** [comment]
If remember well it's the button feedback

https://d.pr/i/QIUZJ2

It's customizable, not sure if it's possible to remove completely

**Comment by mmanak** [comment]
I am using 'function' node to setup postback buttons which is something like below:
{
      type: 'postback',
      value: "/button_option1",
      label: 'Option 1'
    }
As per this, I have not specified button feedback.

**Comment by guidone** [comment]
I think the “Ok” is the default feedback of Slack
Il 21 nov 2018, 15:56 +0100, Manju Sudan <notifications@github.com>, ha scritto:
