### ISSUE TITLE
keep getting an error with slack

### ISSUE THREAD

**Issue by sebastienjouhans** [guidone/node-red-contrib-chatbot#27]
Hi I am trying to send a message to slack but I keep getting this error message

TypeError: Cannot read property 'transport' of undefined

I use a an inject node to trgger the message. the payload is set to boolean true.
the message node only contains 'hi'.
the slack node says it is connected.

not sure what I am missing...

Seb

**Comment by guidone** [comment]
Yes Slack node requires a little bit of rework, I'l try to fix it soon

**Comment by JDHH83** [comment]
I have a similar issue using Telegram.

**Comment by goingmad** [comment]
Same here with Telegram as well, tried also your 0.6.20-beta-1, not solved.

Thanks

Andrea

**Comment by guidone** [comment]
@goingmad are you using a conversation node at the beginning of the flow? Can you send a screenshot of the flow?

**Comment by goingmad** [comment]
![nr-flow](https://cloud.githubusercontent.com/assets/9416225/23961688/05a90152-09ac-11e7-97a9-70dd93a4b61b.jpeg)
![nr-error](https://cloud.githubusercontent.com/assets/9416225/23961833/6d1e1b06-09ac-11e7-97cb-9d2f713f1b92.jpeg)

Thanks for your fast reply Guidone,

the bot seems to be ok, the Telegram out node status is connected. Error shown appears after the manual injection in the flow.

**Comment by guidone** [comment]
You need a conversation node between the inject node and the message node, I am going to write some additional help on this it's a common mistake and the error message doesn't help.

15 mar 2017, 18:23 +0100, goingmad <notifications@github.com>, ha scritto:

**Comment by goingmad** [comment]
Ok Guidone, perfect result following your instructions below. Just had to dig a bit in order to find the chat id, found useful the following link: https://www.codementor.io/garethdwyer/building-a-telegram-bot-using-python-part-1-goi5fncay
As per me, Telegram Sender now is working properly, thanks a lot!

**Comment by guidone** [comment]
Ok, to get the chat id you can use the debug node, it shows all relevant information in the console.
I'll definitely write more docs about it

Thanks for the feedback

**Comment by guidone** [comment]
The Slack support now works again (I know I am late...)
