### ISSUE TITLE
New user need assistant

### ISSUE THREAD

**Issue by ranrinc** [guidone/node-red-contrib-chatbot#270]
Hi there,

I'm new and would like to try using your bot. However having problem to connect node-red to my telegram. Got no response and unsure what need to be setup on the telegram box. Is there a guide for telegram user on how to connect it? Developement or Production? 

I already put in the token.
<img width="500" alt="screen shot 2018-11-24 at 20 43 59" src="https://user-images.githubusercontent.com/15801696/48968974-ee788000-f029-11e8-930b-44045fc7af5d.png">

Unsure what need to be fill for both input and output..help?

Try to connect using a new bot created.. upon deploy debugs  show 
"Error stopping node: TimeoutError: timed out after 15000ms"

So unsure what to do

Do I need to setup webhook first?

**Comment by ranrinc** [comment]
Hi all,

I believe this is all about setting node-red to allow https or something like that in which allow telegram to connect. Is there a guide somewhere that I can follow to install node-red in the right way to be able to support telegram? Currently l used this guide to install node-red on my ubuntu [https://www.digitalocean.com/community/tutorials/how-to-connect-your-internet-of-things-with-node-red-on-ubuntu-16-04](https://www.digitalocean.com/community/tutorials/how-to-connect-your-internet-of-things-with-node-red-on-ubuntu-16-04)

**Comment by guidone** [comment]
Hi @ranrinc have you checked this?

https://github.com/guidone/node-red-contrib-chatbot/wiki/Telegram-Receiver-node

**Comment by ranrinc** [comment]
> Hi @ranrinc have you checked this?
> 
> https://github.com/guidone/node-red-contrib-chatbot/wiki/Telegram-Receiver-node

Got that one.. I found a solution where node-red suppose to be accessed from outside as https and not 127.0.0.1 allowing telegram to know.. Anyway I got my fixed on my nginx setup. I believe this information needed to new user who are using the tutorial from digital ocean. Anyway thanks for the reply. I can now begin to have fun building up my bot.. BTW anyone know a bot sample or a working bot somewhere to look into?

**Comment by guidone** [comment]
Mmm strange, Telegram doesn't require any inbound connection in order to work, it just polls the Telegram's server.
But if it works don't touch it :-)

I'm going to publish in the next few days a sandbox for Telegram similar to this

https://github.com/guidone/redbot-facebook-sandbox

**Comment by MrAndreius** [comment]
> Got that one.. I found a solution where node-red suppose to be accessed from outside as https and not 127.0.0.1 allowing telegram to know.. Anyway I got my fixed on my nginx setup. I believe this information needed to new user who are using the tutorial from digital ocean. Anyway thanks for the reply.

You write that you have found a solution to how to open access. Could you share it here? I have exactly the same problem with Node Red and Nginx. Installed and configured according to the instructions Digital Ocean
