### ISSUE TITLE
Can you display a chatbot-dialog box in Slack without a trigger Id?

### ISSUE THREAD

**Issue by jphillips-bp3** [guidone/node-red-contrib-chatbot#272]
Hi,

I have a flow that integrates with Slack. I have one part of the flow that uses a **chatbot-generic-template** that defines buttons to display back to the user. When the user selects a button I display the required **chatbot-dialog**. When the button is pressed, a trigger Id is also passed back in via the `msg.originalMessage.trigger_id` property.

Now, I also want to display a model dialog box to the user when they enter and submit text, which I am processing using the **chatbot-listen-lexicon** and **chatbot-listen** nodes. But when I try to send back a response requesting a dialog box is displayed, I get the following error:

```Error: An API error occurred: missing_trigger```

I believe this is a Slack error? So my question is, is it possible to display a **chatbot-dialog** without a trigger Id?

Thanks in advance.

**Comment by guidone** [comment]
Yes this error comes from Slack.

Yes i believe that the only way of opening a dialog is an interactive message or a command

> Build an interactive message, a slash command, or both. Dialogs cannot open until users interact with buttons, menus, or slash commands.

And it makes sense, opening a dialog box without any user interaction would be an open door for spammers

**Comment by jphillips-bp3** [comment]
Ah OK I must have missed that part of the documentation. Thanks.
