### ISSUE TITLE
Examples of slash command processing in Slack?

### ISSUE THREAD

**Issue by jphillips-bp3** [guidone/node-red-contrib-chatbot#273]
Hi,

My flow is using a **chatbot-rules** node that I am trying to get slash command processing working in Slack.

I have tried both the `Message is command` and `Message is a command` rule type. With the `Message is command` I have wired up a **chatbot-command** node, and for the `Message is command` I have just specified the command I want in the rule (i.e. `/o` in this case).

In my Slack bot configuration, I have added the slash command under Features->Slash Commands, and have set the request URL to `http://*********.eu.ngrok.io/redbot/slack`.

In both configurations, I get the following exception in Node-RED:

`TypeError: Cannot read property 'type' of null
nodered_1        |     at ChatServer./redbot/slack (/usr/src/node-red/node_modules/node-red-contrib-chatbot/lib/platforms/slack.js:117:26)
nodered_1        |     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
nodered_1        |     at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
nodered_1        |     at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
nodered_1        |     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
nodered_1        |     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
nodered_1        |     at expressInit (/usr/src/node-red/node_modules/express/lib/middleware/init.js:40:5)
nodered_1        |     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
nodered_1        |     at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
nodered_1        |     at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
nodered_1        |     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
nodered_1        |     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
nodered_1        |     at query (/usr/src/node-red/node_modules/express/lib/middleware/query.js:45:5)
nodered_1        |     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
nodered_1        |     at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
nodered_1        |     at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
nodered_1        |     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
nodered_1        |     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
nodered_1        |     at Function.handle (/usr/src/node-red/node_modules/express/lib/router/index.js:174:3)
nodered_1        |     at Function.handle (/usr/src/node-red/node_modules/express/lib/application.js:174:10)
nodered_1        |     at mounted_app (/usr/src/node-red/node_modules/express/lib/application.js:230:10)
nodered_1        |     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)`

As the exception is the same for both configurations, I am assuming the problem is occurring before it even hits the **chatbot-rules** node. Is the request URL format correct in the Slack Slash Commands config? I have noticed a remark in the **chatbot-command** info tab that states "In Slack commands in the form /my_command are used in a different way." so maybe this is related to my problem?

Thanks.

**Comment by guidone** [comment]
Yes commands starting with `/` are handled differently on Slack, in Telegram are simpler (basically a plain message).
I can work on integrate them if you're still interested

**Comment by jphillips-bp3** [comment]
Hi, yes that would be great, thanks.

**Comment by guidone** [comment]
@jphillips-bp3 turned out to be easier than expected, try `0.15.13`

**Comment by jphillips-bp3** [comment]
Great thanks, I will pull that down today and give it a go, and let you know how it goes.

**Comment by jphillips-bp3** [comment]
@guidone That works, many thanks.
