### ISSUE TITLE
OriginalMessage

### ISSUE THREAD

**Issue by ramkinavy** [guidone/node-red-contrib-chatbot#275]
Please refer documentation of the Article Anatomy of the Message 
https://github.com/guidone/node-red-contrib-chatbot/wiki/Anatomy-of-a-Message.

I want the Original Facebook Post Back data but im trying to get "originalMessage" of msg object of the receiver node as per the documentation. This is still giving out the payload part of the message

**Comment by ramkinavy** [comment]
Can we the the original data of the facebook webhook from the facebook receiver node thorugh any other means since the receiver doesnt capture post back events and many other events as given in facebook documentation https://developers.facebook.com/docs/messenger-platform/reference/webhook-events

**Comment by guidone** [comment]
Ok let me check, I'm refactoring a little the events sections in the Alexa branch (will be ready in few days)

**Comment by maverick1509** [comment]
Hi guideone, any update on this. Is there any alternate way to capture the original webhook from the facebook receiver? there are many webhooks which are not covered by the redbot nodes but which need to acted upon

**Comment by guidone** [comment]
@maverick1509 working on it, you'll get in a couple of days
