### ISSUE TITLE
Dialogflow node throws Grpc error

### ISSUE THREAD

**Issue by sriramsv** [guidone/node-red-contrib-chatbot#277]
Hello @guidone ,

I recently moved my node red from standalone installation to docker on raspberry pi.
Since then I am getting this error whenever I try to talk to dialogflow node: 
```
"Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/node_modules/grpc/src/node/extension_binary/node-v57-linux-arm-glibc/grpc_node.node)"
```
I do have libstdc++.so.6 installed on my host os.

Have you come across this problem before?

**Comment by guidone** [comment]
Hi, no never happened.

It's used by grpc, a dependency of dialogflow and others, it's something related to raspberry I guess

**Comment by sriramsv** [comment]
I rebuilt the node-red image with armv32/node base image and this error went away! So will close the issue

**Comment by guidone** [comment]
Perfect, thanks for the feedback
