### ISSUE TITLE
Support for Whatsapp API planned?

### ISSUE THREAD

**Issue by gusman80** [guidone/node-red-contrib-chatbot#279]
I love this project, but as whatsapp is the most used chat utility, did you consider / do you plan to integrate the Whatsapp API? 
+ Where can i donate sth?

**Comment by guidone** [comment]
Yes!
Tomorrow I’m merging the Alexa support and Whatsup will be the next big feature.

For donation there’s a link in the home of github, thanks for that and the feedback

**Comment by jekkos** [comment]
Check #280 for a quick solution!

**Comment by guidone** [comment]
#280 it's fixed in `0.16.1`

**Comment by guidone** [comment]
Another fix for Whatsup is `0.16.5`, I'll write a tutorial
