### ISSUE TITLE
Twilio whatsapp sandbox issue

### ISSUE THREAD

**Issue by jekkos** [guidone/node-red-contrib-chatbot#280]
Twilio offers the possiblity to testdrive their whatsapp api, which you can just use with curl after enabling this in their backend. One thing in the chatbot currently prevents me from doing this correctly

https://github.com/guidone/node-red-contrib-chatbot/blob/cb40f377b98149400b6527873c96d6d29c39830d/lib/platforms/twilio.js#L50

The destination number should be written in the format of

`whatsapp:+<phone number>`

Currently the twilio library adds a `+` as a prefix if this is not present which sends the sender as
 `+whatsapp:+<phone number>` which is obviously wrong

**Comment by jekkos** [comment]
As a temp solution I would try to add another check to see if there is no other 'scheme' present and if not, add the + upfront, otherwise leave the text untouched.

**Comment by jekkos** [comment]
Also same issue at for the receiving number

https://github.com/guidone/node-red-contrib-chatbot/blob/cb40f377b98149400b6527873c96d6d29c39830d/lib/platforms/twilio.js#L58

After removing this + I'm able to send messages to WhatsApp (through Twilio).

**Comment by guidone** [comment]
@jekkos thanks for the feedback, I'm working on it

**Comment by guidone** [comment]
@jekkos it's fixed

**Comment by jekkos** [comment]
Ok very cool! thanks for the prompt feedback. I bought you a coffee for that. Happy holidays.

**Comment by guidone** [comment]
Did you have the chance to check this?

I've tried and the whatsapp sandbox works, I always get an additional "OK" message with the RedBot answer, does this happen also for you?

**Comment by jekkos** [comment]
Yes I have upgraded to the latest release, works fine for me. Only annoying thing is that twilio sandbox after a while stops sending messages, but that probably an issue I need to check with them.

**Comment by guidone** [comment]
Ok, thanks

**Comment by jekkos** [comment]
For some reason the receive stopped working for me . Also indeed I get the additional Ok message, but that might be because of the callback page displaying OK when you load it?

The message does seem to arrive in nodered.

```
-- RELAY MESSAGE --
type:      message
chatId:    whatsapp:+32497xxxx
userId:    whatsapp:+32497xxxx
ts:        Mon Feb 11 2019 22:44:38 GMT+0100
transport: twilio
inbound:   true
content:   On
-- INBOUND MESSAGE --
SmsSid:            SMf245e175cf71be1a42af4082cf05xxx
SmsStatus:         sent
MessageStatus:     sent
ChannelToAddress:  +32497xxxx
To:                whatsapp:+32497xxxx
ChannelPrefix:     whatsapp
MessageSid:        SMf245e175cf71be1a42af4082cfxxx
AccountSid:        ACb57d1e44ca90b55718afb8aa84d11cf3
StructuredMessage: false
From:              whatsapp:+14155238886
ApiVersion:        2010-04-01
ChannelInstallSid: XEcc20d939f803ee381f2442185d0d5dc5
-- DISCARDED MESSAGE (not handled by middlewares) --
-- INBOUND MESSAGE --
EventType:         DELIVERED
SmsSid:            SMf245e175cf71be1a42af4082cf0xxx
SmsStatus:         delivered
MessageStatus:     delivered
ChannelToAddress:  +32497xxxx
To:                whatsapp:+32497xxxx
ChannelPrefix:     whatsapp
MessageSid:        SMf245e175cf71be1a42af4082cfxxx
AccountSid:        ACb57d1e44ca90b55718afb8aa84d11cf3
From:              whatsapp:+14155238886
ApiVersion:        2010-04-01
ChannelInstallSid: XE73d4c268b09c4cd4c8c236cd9da329ca
-- DISCARDED MESSAGE (not handled by middlewares) --
-- INBOUND MESSAGE --
EventType:         READ
SmsSid:            SMf245e175cf71be1a42af4082cf051b4e
SmsStatus:         delivered
MessageStatus:     delivered
ChannelToAddress:  +32497xxxx
To:                whatsapp:+32497xxxx
ChannelPrefix:     whatsapp
MessageSid:        SMf245e175cf71be1a42af4082cf051b4e
AccountSid:        ACb57d1e44ca90b55718afb8aa84d11cf3
From:              whatsapp:+14155238886
ApiVersion:        2010-04-01
ChannelInstallSid: XE73d4c268b09c4cd4c8c236cd9da329ca
-- DISCARDED MESSAGE (not handled by middlewares) --
```

**Comment by guidone** [comment]
Ok, let me check

**Comment by jekkos** [comment]
I cleared the context files and switched from file to memory . This seems to have solved the issue.
However I wonder what the best practice is here if you're using multiple receivers. Should they use different context stores so the flow can distinguish in which one to inject the message?

**Comment by jekkos** [comment]
I get varying results  when i have more than one receiver with the similar context in different flows. How can i make sure that a message ends up in the correct flow when replying to a message sent fro redbot?
I have tried to assign a different chatbot context to both but that does not seem to help.

**Comment by leroymwasaru** [comment]
sfs

> Yes I have upgraded to the latest release, works fine for me. Only annoying thing is that twilio sandbox after a while stops sending messages, but that probably an issue I need to check with them.

**Comment by leroymwasaru** [comment]
> Yes I have upgraded to the latest release, works fine for me. Only annoying thing is that twilio sandbox after a while stops sending messages, but that probably an issue I need to check with them.

@jekkos —Twilio has a 24 hr window enforced by WhatsApp where the receiver has to engage with Twilio API else WhatsApp assumes it's spam and prevents Twilio API from sending any message.
