### ISSUE TITLE
Problem sending message with no-telegram initiated chat

### ISSUE THREAD

**Issue by alasso** [guidone/node-red-contrib-chatbot#285]
Hi,

I am new with chatbots and I want to send an information message through a telegram bot I configured. The message it is a notification that a garage door was activated.
I am using the Telegram Out node but nothing happens. 
I suppose that it is because there is no msg.chat context but, I don't know how to create it. 

Any help?

Thanks a lot in advance.
Adrian

**Comment by guidone** [comment]
I’m out now I cannot copy the link, search for the conversation node

**Comment by alasso** [comment]
Resolved! I used conversation node + message node. 
Beautiful!
Thanks a lot!
