### ISSUE TITLE
Receiver problems

### ISSUE THREAD

**Issue by simiroll** [guidone/node-red-contrib-chatbot#286]
node-red-contrib-chatbot version: 0.16.3

I got 3 issues: 

1. No response from 'Facebook Receiver'
I had setup facebook app config, and I can send out message using 'Facebook Sender'. However 'Facebook Receiver' cannot receive message, no debug msg coming out from it. The 'Facebook Receiver' had green light claiming it is connected.

I then replaced 'Facebook Receiver' by using an http request endpoint node to mock '/redbot/facebook', and it can receive messages from facebook messager. I think it should not be my app's connection issue nor my facebook profile config issue.

2. No response from Dialogflow
Same as the above issue, I had setup Dialogflow profile config and cannot receive any response or debug msg.
I had tried another node-red plugin 'node-red-contrib-dialogflowv2-api', this plugin use same config fields(project id, service account, and private key), and i can receive intent from it.

3. File context store in Facebook Config node
I had tried to create a file based context store, and I had created the file in my folder. I tried to use it by 'Facebook Sender' to send message but failed. After I changed back to memory context store, the 'Facebook Sender' works.

**Comment by guidone** [comment]
I've tried with Facebook receiver and it works, both with memory and file context store.
The context store requires a directory and not a file, is it possible that this is the problem?

Try with something like

```
{"path": "/myfolder"}
```
