### ISSUE TITLE
Viber user auth not working

### ISSUE THREAD

**Issue by TUISTERa** [guidone/node-red-contrib-chatbot#289]
Hello, i am creating viber bot. But user auth is not working, i added chatid in bot config, but it is ignoring it and keep saying AUTH FALSE. I replaced auth node with rules nod and Variable chatid is USERIDHASHHERE and rule is working, so it is something with the auth node. Please test it, i can provide you my chatid on private message if you want , but i am sure that you dont need it
`
Feb 16 20:33:32 home Node-RED[30663]: -- INBOUND MESSAGE --
Feb 16 20:33:32 home Node-RED[30663]: event:         message
Feb 16 20:33:32 home Node-RED[30663]: timestamp:     1550342011721
Feb 16 20:33:32 home Node-RED[30663]: chat_hostname: SN-CHAT-06_
Feb 16 20:33:32 home Node-RED[30663]: message_token: 5277626602752337000
Feb 16 20:33:32 home Node-RED[30663]: sender:
Feb 16 20:33:32 home Node-RED[30663]:   id:          USERIDHASHHERE
Feb 16 20:33:32 home Node-RED[30663]:   name:        Georgi Valentinov Popov
Feb 16 20:33:32 home Node-RED[30663]:   avatar:      https://media-direct.cdn.viber.com/download_photo?dlid=giLCBAfRpwNZpD1JZjV-WQeusGZfn1LYkrblWLJGDnEszywA6E1GLO8ofydV2yONKKN_cql03ij2lFjK1Ph_2vNB7DbwAMYADxjax_prLOZw4iclZ4EKtWXADio&fltp=jpg&imsz=0000
Feb 16 20:33:32 home Node-RED[30663]:   language:    bg
Feb 16 20:33:32 home Node-RED[30663]:   country:     BG
Feb 16 20:33:32 home Node-RED[30663]:   api_version: 7
Feb 16 20:33:32 home Node-RED[30663]: message:
Feb 16 20:33:32 home Node-RED[30663]:   text:          d
Feb 16 20:33:32 home Node-RED[30663]:   type:          text
Feb 16 20:33:32 home Node-RED[30663]:   tracking_data: ""
Feb 16 20:33:32 home Node-RED[30663]: silent:        false
Feb 16 20:33:32 home Node-RED[30663]: -- RELAY MESSAGE --
Feb 16 20:33:32 home Node-RED[30663]: type:      message
Feb 16 20:33:32 home Node-RED[30663]: chatId:    USERIDHASHHERE
Feb 16 20:33:32 home Node-RED[30663]: userId:    USERIDHASHHERE
Feb 16 20:33:32 home Node-RED[30663]: ts:        Fri May 20 51098 09:48:41 GMT+0300
Feb 16 20:33:32 home Node-RED[30663]: transport: viber
Feb 16 20:33:32 home Node-RED[30663]: inbound:   true
Feb 16 20:33:32 home Node-RED[30663]: content:   d
Feb 16 20:33:32 home Node-RED[30663]: -- OUTBOUND MESSAGE --
Feb 16 20:33:32 home Node-RED[30663]: type:      message
Feb 16 20:33:32 home Node-RED[30663]: content:   AUTH NOT OK
Feb 16 20:33:32 home Node-RED[30663]: chatId:    USERIDHASHHERE
Feb 16 20:33:32 home Node-RED[30663]: messageId: null
Feb 16 20:33:32 home Node-RED[30663]: inbound:   false
Feb 16 20:33:32 home Node-RED[30663]: silent:    false
Feb 16 20:33:32 home Node-RED[30663]: fallback:  null
Feb 16 20:33:32 home Node-RED[30663]: options:
`

**Comment by guidone** [comment]
There was a bug in the tutorial, then webhook must use https

```
https://youraddress.ngrok.io/redbot/viber
```

Fixed docs: https://github.com/guidone/node-red-contrib-chatbot/wiki/Viber-Receiver-node

With https it worked for me
