### ISSUE TITLE
Telegram Live Location

### ISSUE THREAD

**Issue by albydnc** [guidone/node-red-contrib-chatbot#296]
Is it possible to get user live location? from the last update of the telegram bot APIs it seems so.
[StackOverflow discussion](https://stackoverflow.com/questions/48238445/how-can-i-get-live-location-in-telegram-bot-via-python)

**Comment by guidone** [comment]
ok, I'l put in the roadmap

**Comment by guidone** [comment]
Ok, the update of live location only works with the webhook for some reason, I'm working on it, it will be ready in few days

**Comment by guidone** [comment]
@albydnc with `0.16.8` live locations in Telegram are fully supported

**Comment by albydnc** [comment]
@guidone thanks that's great!
but I got some issues
``` [TELEGRAM] improperly removed some routes, this will cause unexpected results and tricky bugs```

also cannot get the webhook to work (I've used `ngrok http 80`) but no received message.

**Comment by guidone** [comment]
Is node-red runnning locally on port 80, otherwise by default should be ngrok http 1880

When this error happens means it was not able to unmount the callback, it's better to restart node-red, does it happen all the time?

**Comment by albydnc** [comment]
@guidone Yes sorry, I've forgot to use right port, right now is working seamlessy. Thanks for the release!

**Comment by guidone** [comment]
🖖
