### ISSUE TITLE
Facebook Receive does not receive message

### ISSUE THREAD

**Issue by webfrank** [guidone/node-red-contrib-chatbot#298]
Hi,
   I have Node-Red 0.20.2 and node-red-contrib-chatbot 0.16.6 and I cannot receive messages with facebook. If I sniff with tcpdump I can see facebook post but inside the code lib/platforms/facebook/facebook.js at line 45: var json = req.body I see req.body is undefined but facebook posts a correct json.

**Comment by webfrank** [comment]
I'm using Node-red standalone and I followed the wiki (prior to upgrading to latest version it was working fine)

**Comment by guidone** [comment]
Does it work if you downgrade? There are no changes in the Fb engine in the last versions

**Comment by webfrank** [comment]
Yes, if downgrade works again

**Comment by webfrank** [comment]
Hi, I solved this way, in file lib/chat-platform/chat-platform.js:

- added var bodyParser = require('body-parser');
- in function mountRoutes before RED.httpNode.use(route, middleware.bind(chatServer)); I added RED.httpNode.use(bodyParser.json());

This way I can receive Facebook Messenger messages and bot returned to work properly

**Comment by guidone** [comment]
OK thanks, this is strange, node-red should already have the body parsers in the middlewares.
Let me check if it conflicts with my version of node-red/red-bot and then let's add to master
