### ISSUE TITLE
Reply Message

### ISSUE THREAD

**Issue by dedynobre** [guidone/node-red-contrib-chatbot#299]
Hello,
How can I configure the Telegram bot chat just after the node Keyboard, when the option appears to be answered and not only what was selected?

**Comment by dedynobre** [comment]
From what I saw, my question is related to this item:

![image](https://user-images.githubusercontent.com/8119694/65735620-6e3e0380-e0ae-11e9-86cd-f898bcfdd6ea.png)

My flow of sample:
![image](https://user-images.githubusercontent.com/8119694/65735657-8b72d200-e0ae-11e9-8503-935f14cb3c66.png)

`[{"id":"c59fa6ea.a8c098","type":"chatbot-telegram-receive","z":"9329e367.e02e1","bot":"aa2eb242.ccc5","botProduction":"","x":210,"y":60,"wires":[["3dfa561c.6ba17a"]]},{"id":"1cc3f302.c41acd","type":"chatbot-message","z":"9329e367.e02e1","name":"","message":[],"answer":true,"silent":false,"x":890,"y":60,"wires":[["a896052f.094cd8"]]},{"id":"a896052f.094cd8","type":"chatbot-telegram-send","z":"9329e367.e02e1","bot":"aa2eb242.ccc5","botProduction":"","track":true,"passThrough":false,"outputs":1,"x":1110,"y":60,"wires":[[]]},{"id":"c8785703.682bf8","type":"function","z":"9329e367.e02e1","name":"","func":"msg.payload = {\n    \n    message : 'nada ta dando certo',\n}\nreturn msg;","outputs":1,"noerr":0,"x":670,"y":60,"wires":[["1cc3f302.c41acd"]]},{"id":"3dfa561c.6ba17a","type":"chatbot-command","z":"9329e367.e02e1","name":"","command":"/foo","x":430,"y":60,"wires":[["c8785703.682bf8"]]},{"id":"aa2eb242.ccc5","type":"chatbot-telegram-node","z":"","botname":"@appnexa1_bot","usernames":"","providerToken":"","polling":"1000","store":"","log":"","parseMode":"","debug":false,"webHook":"","connectMode":"polling"}]`

**Comment by dedynobre** [comment]
@guidone

**Comment by guidone** [comment]
@dedynobre what's the question about the quote option?

**Comment by dedynobre** [comment]
I wanted that when selecting a command, for example, looks like this:

![image](https://user-images.githubusercontent.com/8119694/65757026-a7956400-e0ec-11e9-9abc-c70354e2a2f2.png)

**Comment by dedynobre** [comment]
In the flow below happens exactly what is in the previous image:
![image](https://user-images.githubusercontent.com/8119694/65758859-29d35780-e0f0-11e9-9f5b-a6d7b89cefaf.png)

He has this option:
![image](https://user-images.githubusercontent.com/8119694/65758907-3fe11800-e0f0-11e9-9e2c-ed7823d6ec57.png)

From what I noticed on your node (message node) there is this option that would be the quote flag:
![image](https://user-images.githubusercontent.com/8119694/65759094-94849300-e0f0-11e9-84d6-e8c3723b344a.png)

But it's not working, or rather, I don't know if the node sequence is correct

**Comment by dedynobre** [comment]
I tested this type of configuration and it didn't work

![image](https://user-images.githubusercontent.com/8119694/65797870-a4c75d00-e146-11e9-91fe-79228ff19cfe.png)

**Comment by dedynobre** [comment]
Tested and now it works perfectly in the version 0.17.8
