### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by odenisnobre** [guidone/node-red-contrib-chatbot#300]
Hi

What is the best way to start the telegram chatbot?

Currently I have 3 bots configured and working.

When I'm on the bot1 and I go to bot2 to check the items, what's the best way to go to the bot2's main menu?

I had to put a command / start only that I have to keep pressing until the menus appear again. I do not know if this is the best strategy.

**Comment by guidone** [comment]
With bot you mean 3 different flows in the same chatbot?

**Comment by dedynobre** [comment]
Not,

I have 3 bots that work with different information with their respective flows.

What happens is that I find cached some information that when I leave the bot1 for bot2 the information of the bot1 is shown.
