### ISSUE TITLE
Extend Chat Server not executed

### ISSUE THREAD

**Issue by webfrank** [guidone/node-red-contrib-chatbot#301]
Hi, I'm trying to implement a Webex teams integration using the Universal Component.
I wrote this inside the Extend Chat Server Node:

```
node.chat.onChatId(msg => msg.payload.personId);
node.chat.onMessageId(msg => msg.payload.id);
node.chat.in(message => {
  return new Promise((resolve, reject) => {
    // check that the incoming payload is an actual "text" message
    if (message.text !== null) {
      message.payload.type = 'message';  
      message.payload.content = message.text;
    }
    resolve(message);
  });
}); 
```

but it seems this node is never called, chatId is always undefined.

**Comment by webfrank** [comment]
I have to restart node-red every time I change the Extend Node, is this required?

**Comment by guidone** [comment]
The extend node is executed each time the flow is deployed (you can try putting a `console.log` in the code)

Perhaps this lines are not correct (I've to check the examples)
```
node.chat.onChatId(msg => msg.payload.personId);
node.chat.onMessageId(msg => msg.payload.id);
```
the `payload` should not be ready and available in the _on*_ callbacks, should be something like

```
node.chat.onChatId(msg => msg.originalMessage.personId);
node.chat.onMessageId(msg => msg.originalMessage.id);
```
where `originalMessage` is the copy of what received in the input pin
