### ISSUE TITLE
Transport node dropdown

### ISSUE THREAD

**Issue by webfrank** [guidone/node-red-contrib-chatbot#302]
Transport node doesn't list universal transport

<img width="361" alt="Schermata 2019-04-08 alle 16 49 47" src="https://user-images.githubusercontent.com/4688664/55733627-703bd980-5a1e-11e9-8466-e70ad8279513.png">

**Comment by guidone** [comment]
Yes, the transport node is deprecated, use the Rules node

https://github.com/guidone/node-red-contrib-chatbot/wiki/Transport-node
