### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ivictor777** [guidone/node-red-contrib-chatbot#304]
Hello, I have a problem

root@kingserver:~> cd ~/.node-red/
root@kingserver:~/.node-red> npm install node-red-contrib-chatbot
npm WARN deprecated @types/p-cancelable@1.0.1: This is a stub types definition. p-cancelable provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/p-retry@3.0.1: This is a stub types definition. p-retry provides its own type definitions, so you do not need this installed.
npm WARN deprecated snekfetch@3.6.4: use node-fetch instead
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.

+ node-red-contrib-chatbot@0.16.6
updated 1 package and audited 3160 packages in 18.408s
found 4 vulnerabilities (2 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
root@kingserver:~/.node-red> 
root@kingserver:~/.node-red> node -v
v8.16.0
root@kingserver:~/.node-red> npm -v
6.4.1

**Comment by guidone** [comment]
these are just warnings, is it working?

**Comment by ivictor777** [comment]
did not work, I had to install each dependency separately
now works
