### ISSUE TITLE
It is possible to listen what telegram bot say?

### ISSUE THREAD

**Issue by vampywiz17** [guidone/node-red-contrib-chatbot#308]
hello there,

I will plan to install this nodes, but my question is that is possible to listen (not send) what my telegram bot say?

I use the bot to write a info from IFTTT (webhook). i would like to processing this message with Node-Red. 

So it possible to see what the bot say?

**Comment by guidone** [comment]
You can listen messages from the users to the chatbot, listening messages from the chatbot no, I mean this is what these nodes are supposed to do
