### ISSUE TITLE
 how to send a message to the event?

### ISSUE THREAD

**Issue by DimiDr0l** [guidone/node-red-contrib-chatbot#31]
how to send a message to the event?
my node:
`[{"id":"419bc18b.1d416","type":"function","z":"859404ac.f5b828","name":"","func":"console.log(msg);\nmsg.payload.transport = 'telegram';\nmsg.payload.type = 'message';\nmsg.payload.chatId = '********';\nmsg.payload.content = 'test';\nreturn msg;","outputs":1,"noerr":0,"x":410,"y":300,"wires":[["fcd65ca4.ea444"]]},{"id":"3b2db523.3c6dea","type":"inject","z":"859404ac.f5b828","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":240,"y":300,"wires":[["419bc18b.1d416"]]},{"id":"fcd65ca4.ea444","type":"chatbot-message","z":"859404ac.f5b828","name":"","message":"","answer":false,"track":false,"parse_mode":"","x":570,"y":300,"wires":[["bbaa6e12.459b2","7555aa74.d25754"]]},{"id":"bbaa6e12.459b2","type":"chatbot-debug","z":"859404ac.f5b828","x":620,"y":200,"wires":[]},{"id":"7555aa74.d25754","type":"chatbot-telegram-send","z":"859404ac.f5b828","bot":"","track":false,"outputs":0,"x":770,"y":300,"wires":[]}]`

function: 
`console.log(msg);
msg.payload.transport = 'telegram';
msg.payload.type = 'message';
msg.payload.chatId = '********';
msg.payload.content = 'test';
return msg;`

**Comment by guidone** [comment]
Hi @DimiDr0l , use a conversation node and set in the configuration menu your chat chatId

<img width="742" alt="schermata 2016-12-05 alle 15 21 09" src="https://cloud.githubusercontent.com/assets/502519/20888301/8dcefcfa-bafe-11e6-8690-31a738b98557.png">

To get your chatId, just attach a debug node to your telegram receiver, send a message and look at the console
