### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Mohnki** [guidone/node-red-contrib-chatbot#313]
<img width="846" alt="Screenshot 2019-06-25 at 09 33 46" src="https://user-images.githubusercontent.com/6792816/60078858-13061900-972d-11e9-9154-f26e45861f96.png">

My node red started rebooting in a loop last night ... I have been through all the JSON files I can find but am not able to figure out what could be causing this. 

I have uninstalled and reinstalled via npm and am still not having any luck.

Any ideas where to look would be greatly appreciated.

**Comment by guidone** [comment]
One of the context file has an error, try removing all files there (or just the invalid json file if you are abel to spot it).
I'm refactoring the plain file store to be more verbose on reporting errors

**Comment by Mohnki** [comment]
Thats what i thought ... I opened each one in a json formatter and everything came back correct. 

If it could just name the file that would be great. 

Thank you for your quick response.

**Comment by guidone** [comment]
Ok with `0.16.9` I've fixed the bug that prevents the context file to be shown in the log

**Comment by Mohnki** [comment]
Thank you. This helps to see which file it is but unfortunately the files keep being written blank. I have deleted them all but they keep being rewritten blank into the directory. Is it possible to ignore blank files or a way of knowing why the are being written to disk blank?

**Comment by guidone** [comment]
Ok, perhaps I could improve with a less draconian handling of the erros in the parsing, give me some hours

**Comment by guidone** [comment]
Just pushed `0'.16.10`, makes the parsing more robust (at least it doesn't break)
