### ISSUE TITLE
RiveScript input from file

### ISSUE THREAD

**Issue by jbperrin88** [guidone/node-red-contrib-chatbot#314]
Hi there ,

I use your marvelous nodes to handle a bot .

I want to be more open , and flexible with the rivescript Nodes .

Can you please handle a variable input for rivescript node ? 

I mean, i want to push some update to a file (via a cron , on webview , some git ... ) , and read this one instead of static rivescript text in the node .

Thanks !

**Comment by guidone** [comment]
Let me check

**Comment by guidone** [comment]
Ok updated the Rivescript node in `0.16.11`

**Comment by jbperrin88** [comment]
Thanks sooooo much

**Comment by guidone** [comment]
🖖
