### ISSUE TITLE
"Unable to get profile info for user  - Unsupported get request. Object with ID '2217730368280381' does not exist

### ISSUE THREAD

**Issue by rafikos1988** [guidone/node-red-contrib-chatbot#321]
Hi! 
Am having an issue with the facebook receiver when i try to use more than 1 Bot configuration .
I have one flow handeling facebook page 1 and another botconfiguration for facebook page 2

But it is always one working and the other giving the error, it seems that user id of page 1 is sent to both bot configuration for page 2 and then it is not recognized.

Do i need a second node-red instance to be able to use more than 1 bot configuration?

**Comment by guidone** [comment]
It should not be needed, I'm going to check it

**Comment by guidone** [comment]
You are using the same callback right?

**Comment by guidone** [comment]
Hi @rafikos1988 there's a fix in the beta channel (it's a big release with some important features and a redesigned conversation node, it might be not compatible - yet - with the old one), but it should fix the double bot problem

```
npm install node-red-contrib-chatbot@0.17.0-beta.8
```

There's a flag in the facebook configuration that enables different callbacks for each fb bot, you can see the right callback in the console

Can you give it a try?

**Comment by rafikos1988** [comment]
Hi! thank you for your feedback, will give it a try!

**Comment by rafikos1988** [comment]
Still did not work,  as soon as i configure a second bot configuration i get the same error

**Comment by guidone** [comment]
you are using two different callbacks right?

**Comment by rafikos1988** [comment]
No it is the same link, how can i make different call back?  Am using ngrok and one node red instance with the defailt port then red bot gives me the call back path.

**Comment by guidone** [comment]
Check the facebook messenger configuration, there’s a new check at the end of configuration panel, with this enabled redbot will create a different callback for each bot

**Comment by guidone** [comment]
This is the checkbox

https://d.pr/i/YBAG5B

**Comment by rafikos1988** [comment]
Just tried, i used a different word in the verification token and i got this in the console ;

Verifying Facebook Messenger token "undefined", should be "undefined"
Token verified.

i added a second botconfiguration, but the logs still show same 2 call backs ;

------ WebHooks for FACEBOOK----------------
http://localhost:1880/redbot/facebook/test - Use this to test that your SSL (with certificate or ngrok) is working properly, should answer "ok"
http://localhost:1880/redbot/facebook - Use this in the "Webhooks" section of the Facebook App ("Edit Subscription" button)


------ WebHooks for FACEBOOK----------------
http://localhost:1880/redbot/facebook/test - Use this to test that your SSL (with certificate or ngrok) is working properly, should answer "ok"
http://localhost:1880/redbot/facebook - Use this in the "Webhooks" section of the Facebook App ("Edit Subscription" button)


When i tested it still gives the same error as soon as i add a second bot to the flow

**Comment by guidone** [comment]
Sorry I published the beta in the wrong way, the multi chatbot is still not enabled.

I've pushed another version

```
npm install node-red-contrib-chatbot@0.17.0-beta.9
```

If everything works, in the console you should see the callbacks like this

```
http://localhost:1880/redbot/facebook/<first_10_chars_of_the_token>
```

Thanks for the help

**Comment by rafikos1988** [comment]
Works good!! thanks a lot for your efforts.
I will start using it and i will get back to you if i face any issues.

Will this be an official release?

**Comment by guidone** [comment]
Yes, it has big changes that requires some additional testing.

Basically it supports multi transports (a user can have multiple way (transport) to connect telegram, facebook, etc) and the system allows to create flow to handle them with the desired policy.
It will be released soon

**Comment by rafikos1988** [comment]
Much thanks for your efforts again, i admire your work.
Thanks!

**Comment by guidone** [comment]
🖖

**Comment by Nayar** [comment]
I'm not sure if this is the same issue. I'm currently on 18.15. When I have 2 facebook nodes, i get this:

```
Apr 27 16:17:21 nodered1 node-red[323]: [FACEBOOK] improperly removed some routes, this will cause unexpected results and tricky bugs
Apr 27 16:17:21 nodered1 node-red[323]: 27 Apr 16:17:21 - [error] [chatbot-facebook-node:afa6b0fa.ec019] [FACEBOOK] improperly removed some routes, this will cause unexpected results and tricky bugs
```
