### ISSUE TITLE
Send gif to telegram

### ISSUE THREAD

**Issue by jbperrin88** [guidone/node-red-contrib-chatbot#322]
Hi there ,

Last time I ask you something you was so efficient .

So let ask again .
I would like to know if you can add the send animation function for telegram bot 

I want to request some gif randomly in giphy or other provider and send it back to telegram 

https://github.com/yagop/node-telegram-bot-api/blob/0b8ca03b54ac3361c2f656e2fa23c0e4423e49e5/doc/api.md#telegrambotsendanimationchatid-animation-options-fileoptions--promise
Or maybe you have another simple ways to send gif

Thanks

**Comment by jbperrin88** [comment]
Hum .... i find a way but it's a strange one ...

Call giphy to search with http request node
parse response to get GIF URL
Call giphy with http request node with gif url , return buffer
Use function ode to set 
- msg.payload.filename = 'gif.gif' 
- msg.payload.file = buffer
- msg.payload.caption = 'something'
Send thoiw msg to document node

A bit overkill ... a bit slow ... but work !

**Comment by guidone** [comment]
Ok, here it's needed a new Telegram node, I'll put on the roadmap

**Comment by guidone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Send GIF to candidate](https://trello.com/c/FplVgvJK/15-send-gif-to-candidate)

**Comment by guidone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Send GIF to candidate](https://trello.com/c/FplVgvJK/15-send-gif-to-candidate)

**Comment by guidone** [comment]
In `0.17.5` added Animation node, you can specify the URL of the gif directly in the _animation_ field or in the payload 

https://github.com/guidone/node-red-contrib-chatbot/wiki/Animation-node

The same is for video, images, etc
