### ISSUE TITLE
universal connector help

### ISSUE THREAD

**Issue by davidwallis3101** [guidone/node-red-contrib-chatbot#324]
Hi,

I'm trying to get the universal connector working with smsd [https://flows.nodered.org/node/node-red-contrib-smstools](url) however I'm struggling somewhat.. 

![image](https://user-images.githubusercontent.com/13855486/61565720-c4207a80-aa71-11e9-9096-914f288eda60.png)

I've extended the chat server with:

`node.chat.onChatId(msg => {
  return msg.topic !== null ? msg.topic : null;
});

node.chat.onMessageId(msg => {
  return msg._msgid !== null ? msg._msgid : null;     
});

node.chat.in(message => {
    return new Promise((resolve, reject) => {
    // check that the incoming payload is an actual "text" message
    if (message.originalMessage !== null && message.originalMessage.payload.text !== '') {
        message.payload.type = 'message';  
        message.payload.content = message.originalMessage.payload; // msg content
        message.payload.topic = message.originalMessage.topic; //Phone number
    } else {
        node.warn("not text message");
    }
    resolve(message);
  });
}); 

node.chat.out(message => {
  var chat = message.chat();    
  return new Promise((resolve, reject) => {
    message.payload = message.payload.content;
    message.topic = chat.get('chatId');
    resolve(message);
  });    
});`

However I don't seem to get the same results.. first run looks ok however I dont want the chat, api, or client properties as that confuses smsd for output.. 

second run looks different:

![image](https://user-images.githubusercontent.com/13855486/61565671-aa7f3300-aa71-11e9-8b7a-e226755e8d87.png)

Any suggestions / help would be appreciated.

**Comment by guidone** [comment]
Ok I'll check, perhaps this use case is not entirely covered.
It's strange the different output, it would be useful to know what's inside the "payload" of the last debug.
Thanks for the detailed report

**Comment by davidwallis3101** [comment]
last debug from both runs, Input the same in each case:

![image](https://user-images.githubusercontent.com/13855486/61651182-3fba3b80-acad-11e9-8993-9bd95ff6cb5c.png)

**Comment by davidwallis3101** [comment]
any ideas?

**Comment by guidone** [comment]
Sorry I was off last week, I'll take a look tonight

**Comment by guidone** [comment]
@davidwallis3101 Do you have the track option activated?

**Comment by davidwallis3101** [comment]
Where do I check?

**Comment by guidone** [comment]
This check in the Universal Sender

https://d.pr/i/zLlG1t

**Comment by davidwallis3101** [comment]
![image](https://user-images.githubusercontent.com/13855486/63375706-30014600-c384-11e9-8237-649f34fc43c6.png)

**Comment by guidone** [comment]
Ok uncheck the track option, this option is used for answers from the users, that was causing the different result the second time you received a message.
It basically teleports the message to the output pin of the receiver in order to follow up a discussion with the user.

The message in the output pin has still the chat, api and client properties, I need to make a patch to redbot in order to remove it (currently are used to chain multiple messages to the client)

**Comment by guidone** [comment]
I've added some explanation in the universal node

https://github.com/guidone/node-red-contrib-chatbot/wiki/Universal-Connector-node

Later today I'll push the changes that removes the unwanted helpers like .api() .chat() etc.

**Comment by davidwallis3101** [comment]
Brilliant, working now - thanks!
