### ISSUE TITLE
Telegram receiver stops working

### ISSUE THREAD

**Issue by jmai444** [guidone/node-red-contrib-chatbot#326]
I am having an issue where the Telegram receiver for my chat stops working after some period of time.

- Node red runs on an Ubuntu 17.04 VM
- The receiver works and the flow responds to messages sent to the chat after rebooting the VM
- At some point later the flow stops responding to messages sent to the chat
- The chat doesn't seem to receive the input message at all.  When the flow is working properly the blue activity indicator is triggered in some of the downstream nodes at the time messages are sent to the chat.  These are not seen once the issue starts occurring. 
- There are no error messages sent to syslog when the message is sent to the chat
- The Telegram receiver node shows it is connected when viewing the flow
- The remainder of the flow continues to function - I receive messages generated within the node-red flow and sent by the Telegram sender node in the chat
- After rebooting the VM, the chat receives and actions all of the messages missed
- The issue first occurred a week ago
- The issue has occurred 3 times now
- I haven't changed my configuration for several months

Without any error messages, I understand it will be difficult to troubleshoot the problem.  Hoping for some advice on how to find some clues regarding what is happening.  Thanks!

**Comment by jmai444** [comment]
I redeployed the flows rather than rebooting the VM after another failure today.  I notice the following error message on redeployment:

`Jul 26 07:19:00 node-red node-red[852]: 26 Jul 07:19:00 - [error] [chatbot-telegram-node:c5fd291b.866488] Error stopping node: TimeoutError: timed out after 15000ms`

The node id refers to the configuration node for my bot referenced by both the Telegram sender and receiver nodes in my flow.  Is it silently failing?

**Comment by jmai444** [comment]
This is going to be difficult to figure out.  Everything was fine for 5 days - happened again today.  The only clue I've got is the Error stopping node message mentioned above.

**Comment by guidone** [comment]
Hi @jmai444 do you still have the problem? Perhaps I can try updating the telegram lib to 0.40.0

**Comment by jmai444** [comment]
The problem seems to have been transient.  I haven't experienced the issue since early September.  No changes to my config or software.  I'll close this for now.
