### ISSUE TITLE
Video node not working whilst sending mp4 to Telegram

### ISSUE THREAD

**Issue by mihma** [guidone/node-red-contrib-chatbot#327]
Hello and thank you for this amazing project.
I have a rather strange issue with Video node. It throws the error like this when sending mp4 file recorded from CCTV camera: "Error: EFATAL: Unsupported Buffer file-type"
That made me think that the file is corrupted but I can play it just fine in VLC and I've actually managed to send it to Telegram using telegram payload node from another set of nodes.
If I call it with Method: sendVideo and feed the msg.payload below into it it send me a GIF to my bot.
msg.payload = {
    video: "/config/www/snap.mp4"
};
return msg;

My question is: is this a bug o there're simply some restrictions on how mp4 file should be generated in order to be accepted by Video node?
Thank  you.

**Comment by mihma** [comment]
add: if I use Document node it sends it just fine but as a ZIP file which is not exactly what I want.

**Comment by guidone** [comment]
Thanks @mihma 
According to Telegram API there's a 50mb limit

https://core.telegram.org/bots/api#sendvideo

Yes the document node zips everything that the client is not able to handle as a document (included in this case the mp4)

**Comment by mihma** [comment]
Thanks for your reply @guidone 
The file I am trying to send is 10Mb so that's not the issue. Also as I had mentioned I can send it via telegrambot.payload from https://flows.nodered.org/node/node-red-contrib-telegrambot-home using sendVideo method. Hence I wondered how is it different from your Video node.
Cheers.

**Comment by mihma** [comment]
Ok I did some more tests and it looks like it's the mp4 file which is broken. Used another method to create one and sent it just fine using Video node.
Thanks.
