### ISSUE TITLE
extract variables?

### ISSUE THREAD

**Issue by davidwallis3101** [guidone/node-red-contrib-chatbot#329]
Hi,
I'm using the universal receiver and I've created a lexicon step that defines some objects to test with called HouseObjects as follows (Ill make this dynamic later)

![image](https://user-images.githubusercontent.com/13855486/63654075-63214c00-c76d-11e9-9567-68298e824ab5.png)

 I've then got a listen node which has the following in 

![image](https://user-images.githubusercontent.com/13855486/63654080-70d6d180-c76d-11e9-9b55-7a8aeb4e19c5.png)

however in my text node I cant get it to use the object - and I suspect I'm missing something simple.. 

![image](https://user-images.githubusercontent.com/13855486/63654090-9368ea80-c76d-11e9-898c-1dd9284833a8.png)

Also in the listen is it possible to do Turn[Verb] Switch[Verb] and have an or? can I use a Pipe like in regex - as some examples have pipes some have quotes and I'm not entirely sure on the syntax.

Also can I reference the matched word - from the "Turn or Switch" and then use the correct response automatically such as turning switching?

Thanks

David

**Comment by davidwallis3101** [comment]
also:

![image](https://user-images.githubusercontent.com/13855486/63654137-0d996f00-c76e-11e9-8457-88b31c86658c.png)

![image](https://user-images.githubusercontent.com/13855486/63654138-1a1dc780-c76e-11e9-97db-5dfbd569151e.png)

**Comment by davidwallis3101** [comment]
Anyone?

**Comment by m1kr0b1** [comment]
I use a switch node, then a function to set a variable in msg.payload.smething = "My Option"

**Comment by davidwallis3101** [comment]
This isnt closed - I'm still at a loss with this - I want to dynamically extract the houseObject - I dont want to use a switch node - it doesn't achieve it being dynamic.

**Comment by guidone** [comment]
Hi @davidwallis3101 , the point is that node is quite old and the implementation is a wrong approach to solve the problem.
The idea is to implement this 

https://github.com/axa-group/nlp.js?utm_source=gold_browser_extension

a machine learning library with data extraction features

**Comment by davidwallis3101** [comment]
Is there anyway of extracting the object that is matched?, just so I can carry on playing until NLP could be implemented?

NLP would be great to add and have previously looked at using it in a different project.

**Comment by guidone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support for NLP.js](https://trello.com/c/r7dkgqg0/20-support-for-nlpjs)

**Comment by guidone** [comment]
Working on NLP implementation

**Comment by guidone** [comment]
Development is almost done, I writing some docs and tests

https://github.com/guidone/node-red-contrib-chatbot/wiki/NLP.js

**Comment by davidwallis3101** [comment]
can't wait to test it!

**Comment by davidwallis3101** [comment]
any planned date for merging the pull into main?

**Comment by guidone** [comment]
Sometime during this week 🖖

**Comment by guidone** [comment]
NLP.js was merged in `0.18.19`

**Comment by davidwallis3101** [comment]
how do I install this version as it's not published to npm.

**Comment by guidone** [comment]
just launch

```
npm install node-red-contrib-chatbot
```

in your node red installation (should be `$HOME/.node-red` on a Mac)

**Comment by davidwallis3101** [comment]
it didn't appear to have been pushed to npm when I looked?

**Comment by davidwallis3101** [comment]
ok, npm view says it is the correct version - but node-red still stuck on 0.18.8 - will flatten my end and start again!

**Comment by davidwallis3101** [comment]
Ok, getting somewhere with this now, need to have a play with it in more detail and actually get it to do something :)

**Comment by davidwallis3101** [comment]
Looks good, any thoughts on whether Slots would be possible?

**Comment by davidwallis3101** [comment]
for example https://github.com/axa-group/nlp.js/blob/master/docs/v3/slot-filling.md
