### ISSUE TITLE
Telegram: Edit buttons from context

### ISSUE THREAD

**Issue by fmartingr** [guidone/node-red-contrib-chatbot#332]
Hi folks,

I'm currently creating a personal bot that sends out several messages to the user with inline buttons to perform actions, but following [this](https://github.com/guidone/node-red-contrib-chatbot/wiki/Edit-Message-Buttons) what happen is that the last message from the chat (which happens to be inline buttons because of the bot behaviour) is edited, not the ones I clicked.

Is a very simple bot that contains a "save" button on several messages and I want it to react to that save, perform an action and update that buttons.

The flow looks like this:
![image](https://user-images.githubusercontent.com/812088/64128177-79568a00-cdb5-11e9-8e61-3947f8226a3a.png)
> All senders but the last are passthrough, the third is a track.

I get the message id using `chat.get("messageId")` as per the docs, but I don't know if the `postback` action from the buttons have any kind of `replying_to` field to get the message ID from the buttons. [It seems so from the telegram API](https://core.telegram.org/bots/api#callbackquery) but I'm not very familiar with it so I could be wrong.

I will try to experiment a bit more, but any help is appreciated.

**Comment by guidone** [comment]
Hi @fmartingr sorry for the delay, still struggling with this?

**Comment by fmartingr** [comment]
No worries! I didn't manage to make it work so I moved to other things. Was that possible or did I made a mistake in my flow? I think I have it archived somewhere.
