### ISSUE TITLE
terminated by other getUpdates request; make sure that only one bot instance is running (409)

### ISSUE THREAD

**Issue by iptvcld** [guidone/node-red-contrib-chatbot#335]
Hello;
Love the Nodes - however; i am seeing the error posted in the subject spamming approx every few seconds in the HA logs.

node-red-contrib-chatbot - Ver 0.16.12
NodeRed:  ver 4.1.1

- I have checked the Node Red Config panel and i only have a Telegram receiver and sender - noting else.

I cannot figure out why this keeps spamming the logs and hope you can help me out.

Thank you!

**Comment by KrunkKracker** [comment]
Do you have the same bot configured for both development and production? Removing one is what fixed that for me.

![image](https://user-images.githubusercontent.com/1335547/65786288-5739f880-e124-11e9-94fd-c3a3aba5dcce.png)

**Comment by guidone** [comment]
Thanks @KrunkKracker , @iptvcld does this fix your problem?
