### ISSUE TITLE
Unable to get profile info for user 

### ISSUE THREAD

**Issue by rafikos1988** [guidone/node-red-contrib-chatbot#336]
i have an issue getting user infos after i changed my facebook password ;
i tried creating new app, new token, new all...but still same issue :(

-------------------------- Error in chat-platform.js ---------------------------
Unable to get profile info for user 1995053190607544 - Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.

30 Sep 13:50:24 - [error] [chatbot-facebook-node:31ea0ee1.afef82] Unable to get profile info for user 1995053190607544 - Error validating access token: The session has been invalidated because the user changed their password or Facebook has

**Comment by rafikos1988** [comment]
if i try using a chatbot third party provider like chatfuel, it works fine :(

**Comment by guidone** [comment]
I think you have to regenerate the access token for the chatbot

**Comment by rafikos1988** [comment]
Hi, i already did many times, i event changed the facebook app and the user.
Seems the node is still using an old token?

**Comment by guidone** [comment]
Perhaps there's an error calling the server, you see someting in the system console?

If there's nothing strange I've to check with one ofmy examples

**Comment by rafikos1988** [comment]
I only see that error ;

Unable to get profile info for user 1995053190607544 - Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.

it happened after i changed my facebook account password.
if i use chatfuel and link it to my page, it works fine

**Comment by rafikos1988** [comment]
Hi, it could be something related to the network firewall...checking..

**Comment by rafikos1988** [comment]
So yes it was due to network firewall, someone blocked something...
Sorry i was missguided by the error message!
