### ISSUE TITLE
set Telegram Bot Config dynamically

### ISSUE THREAD

**Issue by spirit78** [guidone/node-red-contrib-chatbot#337]
Hi, 

more a question rather than an issue: Is there any way to set Telegram Bot config at runtime? 

I'am running more than one chatbot on different production sides. I would like to deliver same codebase to all production environments. Depending on the production side (side config based on setting outside node-red) I would like to use a different bot. 

Great thx in advance!

**Comment by guidone** [comment]
Not at the moment, you can put the configuration in the settings file

https://github.com/guidone/node-red-contrib-chatbot/wiki/Global-Configuration
