### ISSUE TITLE
Modifying chat ID of Conversation node

### ISSUE THREAD

**Issue by stefanoco** [guidone/node-red-contrib-chatbot#35]
Thinking about this use case:

- I create a group and invite the bot 
- a Telegram user sends a message with command "/listen" to the group
- a listening chatbot flow gets chatId and saves it
- from now on, specific events will trigger a message sent with the Conversation node to that chatId

But I don't see any way for specifiying the chatId to Conversation out of manually configuring it, correct? It would be great to be able to add chatIds to nodes.

**Comment by guidone** [comment]
@stefanoco you're right, it can be useful, I'll work on it.

Thanks for the feedback

**Comment by stefanoco** [comment]
great project anyway! Thanks

**Comment by guidone** [comment]
@stefanoco thanks! It's fixed in 0.6.10
