### ISSUE TITLE
I dont Edit Message Buttons

### ISSUE THREAD

**Issue by Andorium** [guidone/node-red-contrib-chatbot#350]
I'm trying to change the text and buttons, but I have a new message being sent. What am I doing wrong ?

![image](https://user-images.githubusercontent.com/46258470/68300639-053fa780-00c0-11ea-87d0-9163d9965324.png)

![image](https://user-images.githubusercontent.com/46258470/68300645-0a9cf200-00c0-11ea-8bde-1fa2dec46655.png)

![image](https://user-images.githubusercontent.com/46258470/68300652-0c66b580-00c0-11ea-9b55-19ed048b1814.png)

![image](https://user-images.githubusercontent.com/46258470/68300660-0f61a600-00c0-11ea-88a8-e853fe1eb7ba.png)

![image](https://user-images.githubusercontent.com/46258470/68300664-125c9680-00c0-11ea-8446-9f9c24ce7922.png)

![image](https://user-images.githubusercontent.com/46258470/68300671-15578700-00c0-11ea-94a1-9918665e33ce.png)

**Comment by Andorium** [comment]
[{"id":"be548aee.e751c8","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"bd572d13.c59a1","type":"chatbot-telegram-receive","z":"be548aee.e751c8","bot":"5b296ef4.b5893","botProduction":"","x":151.5,"y":151,"wires":[["47ab6851.e0df98"]]},{"id":"6afa4c51.87a664","type":"chatbot-telegram-send","z":"be548aee.e751c8","bot":"5b296ef4.b5893","botProduction":"5b296ef4.b5893","track":false,"passThrough":false,"outputs":0,"x":737,"y":466,"wires":[]},{"id":"8fd00e61.b6585","type":"chatbot-conversation","z":"be548aee.e751c8","name":"","botDevelopment":"5b296ef4.b5893","botProduction":"5b296ef4.b5893","chatId":"","userId":"","transport":"telegram","store":"ac640c32.37459","x":435,"y":364,"wires":[["7bae457.a771cbc"]]},{"id":"47ab6851.e0df98","type":"chatbot-inline-buttons","z":"be548aee.e751c8","name":"What ?","buttons":[{"type":"postback","label":"Yes","value":"1","answer":"","alert":false,"style":"default"},{"type":"postback","label":"No","value":"2","answer":"","alert":false,"style":"default"}],"message":"What ?","x":338.5,"y":161,"wires":[["687c3fab.4897"]]},{"id":"db3eb1aa.f61a6","type":"function","z":"be548aee.e751c8","name":"FN","func":"var chat = msg.chat();\nvar messageId = chat.get('messageId');\nvar chatId = chat.get('chatId');\nmsg.payload = {    \n  chatId: chatId,    \n  messageId: messageId,\n  buttons: [{ type: 'postback', value: 'clicked', label: 'Clicked!' }]\n};\nreturn msg;","outputs":1,"noerr":0,"x":376.5,"y":288,"wires":[["8fd00e61.b6585"]]},{"id":"687c3fab.4897","type":"chatbot-telegram-send","z":"be548aee.e751c8","bot":"5b296ef4.b5893","botProduction":"5b296ef4.b5893","track":true,"passThrough":false,"outputs":1,"x":342,"y":226,"wires":[["db3eb1aa.f61a6"]]},{"id":"7bae457.a771cbc","type":"chatbot-inline-buttons","z":"be548aee.e751c8","name":"Update Button","buttons":[],"message":"New MSG","x":542,"y":421,"wires":[["6afa4c51.87a664"]]},{"id":"5b296ef4.b5893","type":"chatbot-telegram-node","z":"","botname":"BT","usernames":"","providerToken":"","polling":"300","store":"1a9245a4.418a3a","log":"","parseMode":"HTML","debug":true,"webHook":"https://5a8ee40e.ngrok.io/redbot/telegram","connectMode":"polling"},{"id":"ac640c32.37459","type":"chatbot-context-store","z":"","name":"SupportChat","contextStorage":"","contextParams":""},{"id":"1a9245a4.418a3a","type":"chatbot-context-store","z":"","name":"QustionContext","contextStorage":"memory","contextParams":""}]

**Comment by otakuf** [comment]
Can`t get postback inline-buttons work, too. Something wrong.

**Comment by guidone** [comment]
Hi @otakuf thins changed a bit here, since there are a lot of possible platform specific params I've introduced a new node for that.
in this case in order to edit a previous message you have to add a [[Params node||Params-node]] like this

<img width="1375" alt="Screen Shot 2020-01-07 at 10 45 18" src="https://user-images.githubusercontent.com/502519/71885575-ecdd1f00-313a-11ea-92be-e1e97f46ce2b.png">

Unfortunately there's a bug on this node, I'll fix quickly in this PR #377

**Comment by guidone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix edit message buttons](https://trello.com/c/WoNpnHGW/27-fix-edit-message-buttons)

**Comment by guidone** [comment]
fixed in `0.18.4`
