### ISSUE TITLE
Universal Connector node with basic http call

### ISSUE THREAD

**Issue by dfit** [guidone/node-red-contrib-chatbot#352]
Hello first thank u for your work you seems very invested in it !

I didn't find something in your documentation or in the web related to the problem I encounter.

I want to do a simply http endpoint which will call a dialog flow node to get the intent of my text request.

But first I saw i had to create a connector in order to pass some func to the flow.
 
And here I am, I manage to create a mini flow that go throught the simpliest step, but when linked to http in / out node it don't have the res/req object to perform the response.
Is it a desired behaviour, I am facing a issue or I do something wrong ?

`[{"id":"a23efa1c.df30d8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"3d2d2a58.aea756","type":"http in","z":"a23efa1c.df30d8","name":"meta-bot","url":"/meta-bot","method":"post","upload":true,"swaggerDoc":"","x":200,"y":300,"wires":[["1d0ccdec.6219d2"]]},{"id":"1b657622.28b0ea","type":"chatbot-extend","z":"a23efa1c.df30d8","codeJs":"node.chat.onChatId(message => message.payload.userId);\nnode.chat.onMessageId(message => 0);\n\nnode.chat.in(message => {\n  return new Promise((resolve, reject) => {\n    message.payload.type = 'message';\n    message.payload.content = message.originalMessage.payload;\n    resolve(message);\n  });\n});\n\nnode.chat.out('message', message => {\n  return new Promise((resolve, reject) => {\n    resolve(message.payload);\n  });\n});","platform":"universal","noerr":0,"x":370,"y":420,"wires":[]},{"id":"1d0ccdec.6219d2","type":"chatbot-universal-receive","z":"a23efa1c.df30d8","bot":"b7a6942a.462408","botProduction":"8a84f708.76e778","x":430,"y":300,"wires":[["fe828e6f.57a1b"]]},{"id":"fe828e6f.57a1b","type":"chatbot-conversation","z":"a23efa1c.df30d8","name":"","botDevelopment":"b7a6942a.462408","botProduction":"b7a6942a.462408","chatId":"409994","userId":"","transport":"universal","store":"fdb57f77.2f3e7","x":550,"y":220,"wires":[["3707b99d.aee8c6"]]},{"id":"3707b99d.aee8c6","type":"chatbot-universal-send","z":"a23efa1c.df30d8","bot":"b7a6942a.462408","botProduction":"8a84f708.76e778","track":false,"passThrough":false,"x":790,"y":180,"wires":[["76f88252.34996c"]]},{"id":"76f88252.34996c","type":"http response","z":"a23efa1c.df30d8","name":"User Response","statusCode":"","headers":{},"x":1060,"y":180,"wires":[]},{"id":"b7a6942a.462408","type":"chatbot-universal-node","z":"","botname":"meta-bot","usernames":"","connectorParams":"","store":"fdb57f77.2f3e7","log":"","debug":true},{"id":"8a84f708.76e778","type":"chatbot-universal-node","z":"","botname":"meta-bot-prod","usernames":"","connectorParams":"","store":"fdb57f77.2f3e7","log":"","debug":true},{"id":"fdb57f77.2f3e7","type":"chatbot-context-store","z":"","name":"context","contextStorage":"memory","contextParams":""}]`
![image](https://user-images.githubusercontent.com/6095328/68315431-0ec51180-00b8-11ea-855f-6b3208be6ebd.png)

This is what I got in the terminal on my docker logs after attempting a http call: 
![image](https://user-images.githubusercontent.com/6095328/68318983-e3ddbc00-00bd-11ea-8b67-2bff39d6c2f1.png)

Thank u for you time :)

**Comment by dfit** [comment]
Hi,

I found the solution by passing the "req" and "res" object in the chat context during the "in" phase and after the "universal sender" node I use a function node to get them and set them as so : msg.res = msg.chat().get("res").

This allow me to call the res callback to respond to a custom synchronous http bot.

**Comment by guidone** [comment]
Sorry for the late answer, yes it could be a solution be it could also lead to potential memory leak.

But basically all you want to do to use the dialogflow node right? In this is the case are there around some nodes that talks to dialogflow without the overhead of RedBit/platforms/chat context?

**Comment by dfit** [comment]
Actually we need to enhanced our user experience by providing other chat interface than our own front (that work with classic and controlled request) such as Facebook and your nodes should help us a lot.
