### ISSUE TITLE
RiveScript parser

### ISSUE THREAD

**Issue by peter-clarke** [guidone/node-red-contrib-chatbot#36]
I have followed the RiveScript parser example but I keep receiving error on the 'Telegram Sender' node when the second output flow is triggered.

TypeError: msg.chat is not a function

**Comment by guidone** [comment]
Hi Peter, the output of a rivescript is a string, is there a message node between the parser and the telegram node?
Perhaps I've to improve the error handling

Thanks for the feedback

**Comment by peter-clarke** [comment]
Yes there is a message node in between the output of the rivescript module and the telegram sender module.

The first output of the rivescript operates as expected.

Using a debug module I do get something out of the second output that looks to be correct but for some reason it triggers a fault on the telegram sender and I do not receive a reply in Telegram.

**Comment by guidone** [comment]
@peter-clarke Ok now I see, it should be fixed in 0.6.11

Thanks
