### ISSUE TITLE
Stickers in telegram not working after update to 0.18.2

### ISSUE THREAD

**Issue by IsaTTeN** [guidone/node-red-contrib-chatbot#364]
Hi!

After update chatbot to 0.18.2 the sticker node isn´t working anymore. Every time I try to send a sticker I get this

`"Don't know how to handle: CAADAgAD9wADVp29CgtyJB1I9A0wFgQ"`

![image](https://user-images.githubusercontent.com/20249994/70333311-2ddfcc00-183b-11ea-936a-4160fc1af277.png)

for example in this flow

![image](https://user-images.githubusercontent.com/20249994/70333377-45b75000-183b-11ea-9a6c-920792d7a5a4.png)

**Comment by guidone** [comment]
Ok, got it.
Fixing soon, thanks for the feedback

**Comment by guidone** [comment]
Fixed in `0.18.3`

**Comment by IsaTTeN** [comment]
Thanks!!! @guidone

**Comment by bonnydeal** [comment]
I am now getting this error in 0.19.7
