### ISSUE TITLE
Conversation node does not recognize msg.payload.chatId param

### ISSUE THREAD

**Issue by jm8985** [guidone/node-red-contrib-chatbot#365]
Creating this from [this issue: node-red-contrib-chatbot/issues/347](https://github.com/guidone/node-red-contrib-chatbot/issues/347)

Version:
6 Dec 18:42:12 - [info] Node-RED version: v1.0.1
6 Dec 18:42:12 - [info] Node.js version: v10.16.3
6 Dec 18:42:12 - [info] node-red-contrib-chatbot@0.18.2

I'm using the Slack input/output nodes.

In a function node before the conversation node, setting msg.payload.chatId results in error message: "11 Nov 19:51:51 - [error] [chatbot-conversation:813812b2.2135e] Both chatId and userId are empty"

This can be fixed for my purpose in chatbot-conversation.js: 
Change:
//const chatId = extractValue('stringOrNumber', 'chatId', node, msg, false);
var chatId = msg.payload.chatId;

**Comment by guidone** [comment]
Ok thanks, fixing soon

**Comment by guidone** [comment]
To what is attached the function node (upstream)?

**Comment by jm8985** [comment]
I have an http-in node, which posts the payload of:
`{
				"userId": "ABC",
				"channelId": "ABC",
				"chatId": "ABC",
				"actionName": "confirm",
				"actionValue": "true"
			}`

If any arbitrary value is set in the editor for the chatId, the Slack sender will send a message, but the tracking will not work. (when chatId is set in an upstream node)
Leaving the chatId value blank in the editor results in the error message.

**Comment by guidone** [comment]
I made a little fix in `0.18.3`, I'm not sure it was the cause.
I've re-created your scenario in the Slack playground (2nd tab) [here](https://github.com/guidone/redbot-slack-playground) and it works.

If yours still doesn't work the problem could be something specific with your flow, can you try?

**Comment by jm8985** [comment]
Thank you, I will try it soon.

**Comment by Terxeno** [comment]
Finnaly, it's work! Thanks!

**Comment by jm8985** [comment]
@Terxeno I haven't tried it yet as it would affect production, but I'm happy to see your response that the problem is fixed!

**Comment by nathish** [comment]
> I made a little fix in `0.18.3`, I'm not sure it was the cause.
> I've re-created your scenario in the Slack playground (2nd tab) [here](https://github.com/guidone/redbot-slack-playground) and it works.
> 
> If yours still doesn't work the problem could be something specific with your flow, can you try?

I confirm that the fix resolved the same issue when passing telegrams chatId. Thanks
