### ISSUE TITLE
How to get ChatID on a docker deployment?

### ISSUE THREAD

**Issue by dedepene** [guidone/node-red-contrib-chatbot#366]
I'm struggling accessing the console terminal/log on a hass.io deployment (alpine linux on docker).  According to this piece of documentation this is where I get the ChatID - https://github.com/guidone/node-red-contrib-chatbot/wiki/Start-conversation

Where do I look for the log please?

Thanks!

**Comment by guidone** [comment]
You should be able to see the logs here

https://d.pr/i/Jqr9DU

In the page of Node-RED inside hass.io

**Comment by dedepene** [comment]
Thanks @guidone, I found it! Unfortunately I'm not seeing the ID there :( This is all I get after a flow re-deployment:

```
9 Dec 23:19:37 - [info] Starting flows
Telegram Bot mladost_homeass will be launched, environment is development
No context provider specified for chatbot mladost_homeass. Defaulting to "memory"
9 Dec 23:19:37 - [info] [tcp out:e35538ec.1797c8] connecting to 192.168.1.204:8888
9 Dec 23:19:37 - [error] [poll-state:f73813f2.535ed] Error: Entity Id is required
9 Dec 23:19:37 - [info] Started flows

------ WebHooks for TELEGRAM----------------
http://localhost:46836/redbot/telegram/

Chat server started, transport: telegram
[09/Dec/2019:23:19:37 +0200] 200 192.168.1.1, 172.30.32.1(172.30.32.2) POST /flows HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36)
```

**Comment by guidone** [comment]
What if you redirect the output of the receiver to a Node-Red debug node (not the RedBot debug) and check the right column of Node-RED (there will be a lot fo data but the chatId should be there).

If doesn't work try contacting the author of the Node-RED addon for hass.io

**Comment by dedepene** [comment]
Thanks, I got it - all I had to do is actually send some random string to telegram, which triggered the receiver node and debug was generated. Thanks again!

**Comment by guidone** [comment]
🖖
