### ISSUE TITLE
Cannot receive telegram messages when using postback buttons using webhooks

### ISSUE THREAD

**Issue by lustmolch** [guidone/node-red-contrib-chatbot#371]
Hey,

I am using the Telegram provider with the webhook option (in development mode).
Receiving messages is working normally like it should.

But when I send buttons (using the button node) with type postback to a user and the user is clicking on the button, the receive node is not receiving the message. The telegram client is just showing "loading..." at the top.

I inspected the incoming http requests from the Telegram API and saw that there is in fact a request arriving at the webhook url, but it is somehow not being parsed by redbot.

When using the polling option, everything is working fine.

If necessary I can build a test flow.

**Comment by guidone** [comment]
Ok, it's possible that with webhooks the postback message is sent in a different way.
I'll investigate soon, thatnks for the feedback

**Comment by guidone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cannot receive postback buttons using webhooks](https://trello.com/c/GkqBHXH1/26-cannot-receive-postback-buttons-using-webhooks)

**Comment by guidone** [comment]
fixed in `0.18.4`
