### ISSUE TITLE
Facebook messenger not accepting messages from others

### ISSUE THREAD

**Issue by luisfosoares** [guidone/node-red-contrib-chatbot#372]
I did all process for facebook messenger integration but it can only receive messages from the account I have created the page (mine account)

When others send me messages they are not received in Node Red 

Is this normal? How can I change it ? 

Thanks

**Comment by guidone** [comment]
Is you application approved? If it's not it's only accessible by admins, devs and test users (you can change that in the config panel)

**Comment by luisfosoares** [comment]
Can you please let me know precisely where i can check that? 

Application is Live and all settings look ok and i don't find a field referencing approval 

Thanks

**Comment by guidone** [comment]
Check here

<img width="1247" alt="Screen Shot 2020-01-07 at 11 10 29" src="https://user-images.githubusercontent.com/502519/71887423-5b6fac00-313e-11ea-8e24-5ea8a11ffbe5.png">

**Comment by luisfosoares** [comment]
Mine is clear, what request should i make?

![1](https://user-images.githubusercontent.com/6531538/71894494-5151ab80-3146-11ea-8cdc-e8d32b46d632.PNG)

**Comment by guidone** [comment]
Did you solve the problem?
In [this](https://github.com/microsoft/botframework-sdk/issues/1465#issuecomment-258893966) discussion are talking about a similar problem

**Comment by Nayar** [comment]
![Screenshot_20200429_221415](https://user-images.githubusercontent.com/454815/80632598-8a50bb80-8a68-11ea-8737-0cf2e8c649d1.png)

You need to request this permission like this
