### ISSUE TITLE
FB Quick Reply - Message should not Mandatory

### ISSUE THREAD

**Issue by rainerkrueger** [guidone/node-red-contrib-chatbot#374]
Hello,

The message in node Quick Reply is mandatory for the UI but it's can be read from Payload. To use the payload value and prevent the Error message in Node-red, I will suggest to remove this validation:

<img width="502" alt="Bildschirmfoto 2020-01-03 um 11 08 16" src="https://user-images.githubusercontent.com/38502484/71717756-5c8c9a80-2e19-11ea-8309-c420c261c8d2.png">

https://github.com/guidone/node-red-contrib-chatbot/blob/3861cc8770944f44924be512405676da670ef781/nodes/chatbot-quick-replies.html#L13

The logic to load the payload value if the config's value is not set:
https://github.com/guidone/node-red-contrib-chatbot/blob/3861cc8770944f44924be512405676da670ef781/nodes/chatbot-quick-replies.js#L30

**Comment by guidone** [comment]
I agree, will fix soon

**Comment by guidone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validationof FB Quick Reply](https://trello.com/c/OwP8XuH2/25-validationof-fb-quick-reply)

**Comment by guidone** [comment]
fixed in `0.18.4`
