### ISSUE TITLE
Need help on webhook

### ISSUE THREAD

**Issue by Dwarika-Patra** [guidone/node-red-contrib-chatbot#375]
Hi ,

Through Node-Red configured for Telegram , we are able to get response and able to have conversations.  This is with polling and get the updates.

But if the webhook is set with a external public url , we are not getting user responses. 

The primary objective is to use webhooks instead of polling , for telegram conversation. Here we want to pass the response from this external webhook to Node Red.

We need your input and please guide us here.

Regards,
Dwarika

**Comment by guidone** [comment]
Are you testing this locally or in a public available server?
In development (locahost) you have to use ngrok to make the development box available outside.

If you make a POST call to http://yourpublicaddress/redbot/telegram do you get a response?

**Comment by Dwarika-Patra** [comment]
Hi - We are trying with a ngrok created url. We are not getting any response from with http://<our ngrokurl>/redbot/telegram.

Please help us here . Are we missing something here ?

**Comment by guidone** [comment]
You should launch ngrok with 

ngrok http 127.0.0.1:1880

and your public address should be something like

http://youraddress.ngrok.io/redbot/facebook 

Replace "youraddress" with what you get from the ngrok app

https://github.com/guidone/node-red-contrib-chatbot/raw/master/docs/images/facebook-1.png

**Comment by Dwarika-Patra** [comment]
Hi ,
Just to give some basic from where we get the problem, when we run <our ip>:3000 port we are able to get Node Red UI up and running with background process running on a unix box. 

But when we try it with sam port i.e.  <our ip>:3000/redbot/telegram , we are not getting the response. Is there anything to be done with routing ?

Let me know , if anything is not clear to you. 

We would really appreciate if you can spend some for a quick chat. We really liked your contribution and don't want to waste your time. Hence need a quick chat with you if possible.

**Comment by Dwarika-Patra** [comment]
Hi ,
We followed the same way with a public url. Is that some thing we need to add any specific port  other that what we have use i.e. 3000?

Just wanted to know what port Node Red is assgined for telegram service. 

Please help us here.

**Comment by guidone** [comment]
The port is the same of node-red, default is 1880 if not changed in settings.js

**Comment by Dwarika-Patra** [comment]
Hi - Thanks for your input.  Error log is indicating a  bad webhook at one of our IP. Please suggest. Is that something we are doing wrong? Below are the Debug and Error log.

Debug logs :

> this:  { webHook:
>    { autoOpen: true,
>      port: 1880,
>      key: '/root/node_modules/node-red/node-key.pem',
>      cert: '/root/node_modules/node-red/node-cert.pem' },
>   baseApiUrl: 'https://api.telegram.org',
>   request: undefined,
>   polling: false,
>   filepath: true,
>   badRejection: false }
> { autoOpen: true,
>   port: 1880,
>   key: '/root/node_modules/node-red/node-key.pem',
>   cert: '/root/node_modules/node-red/node-cert.pem' }

Error Log: -

**Unhandled rejection Error: ETELEGRAM: 400 Bad Request: bad webhook**: IP 172.16.10.190 is reserved
    at request.then.resp (/root/.node-red/node_modules/node-telegram-bot-api/src/telegram.js:285:15)
    at tryCatcher (/root/.node-red/node_modules/bluebird/js/release/util.js:16:23)

**Comment by Dwarika-Patra** [comment]
Hi,
Now we are trying node-red-contrib-chatbot with a public Nated IP .  This is to insure that we check telegram.js logs for endpoint and catch user response.

But we are struck at setting webhook with one of our public ip. I have attached a screen shot for your reference.  

Please help us here.

![Node-Red](https://user-images.githubusercontent.com/59477145/72792359-e41e3a00-3c5e-11ea-8aa8-369174385eeb.png)

**Comment by guidone** [comment]
Hi @Dwarika-Patra I can give you a little help on this, I don't know your infrastructure and I've no access to it, I can really tell what is going wrong in your configuration.

I can add a test url (like the other services), something like

https://220.227.38.106/redbot/telegram/test

that you can try on your browser and will return just a simple "ok". Until you don't see this test address working, means that your nat/reverse proxy problem is not solved.

Will push this change later today

**Comment by Dwarika-Patra** [comment]
Hi - Thanks for your input. Yes it is not displaying ok. We are working on the reverse proxy and will take your help once done.

**Comment by guidone** [comment]
The endpoint was not ready yet, it's available in `0.18.6` (pushed right now)
