### ISSUE TITLE
Message Node

### ISSUE THREAD

**Issue by dedynobre** [guidone/node-red-contrib-chatbot#378]
Hello,

After updating the version I realized that the item below is no longer available
![image](https://user-images.githubusercontent.com/8119694/71984936-8f170880-3208-11ea-80fc-d1d9271cde78.png)

I tried to use this setting and it still didn't work
![image](https://user-images.githubusercontent.com/8119694/71984885-7b6ba200-3208-11ea-968b-9b34814cdf54.png)

**Comment by guidone** [comment]
Use the params node

https://github.com/guidone/node-red-contrib-chatbot/wiki/Params-node

**Comment by dedynobre** [comment]
thank you

**Comment by guidone** [comment]
🖖
