### ISSUE TITLE
Alexa endSession

### ISSUE THREAD

**Issue by guidone** [guidone/node-red-contrib-chatbot#383]
No problem. Just one thing reading the docs I don’t why it was decided that endsession should carry no text speech. It should allow text, as the docs in Amazon allow the payload to contain a text ending the session.

**Comment by guidone** [comment]
@subzero79

**Comment by subzero79** [comment]
Not only endsession, just any intent does not chain any dialog. Been just testing the flow example in the sandbox(just to make sure i wasn't making a mistake) and it doesn't work.

From the sandbox you can launch it as "alexa ask chatbot nodered to switch on the lights", replies comes in as "Can you tell me where?" and you can see the returning payload in the console with no directive at all, when it should have an elicitslot directive.

![Screenshot from 2020-02-17 11-24-14](https://user-images.githubusercontent.com/7058119/74617320-47c15780-5178-11ea-951c-cf4c42cb8ac5.png)

![Screenshot from 2020-02-17 11-27-08](https://user-images.githubusercontent.com/7058119/74617370-74756f00-5178-11ea-8094-9540345f2a8e.png)

**Comment by polcape** [comment]
Hi @subzero79 ,

can you help me with configuration of Alexa? I follow the wiki guide but I get
type": "INVALID_RESPONSE",
"message": "An exception occurred while dispatching the request to the skill."
