### ISSUE TITLE
MSTeams Node Missing

### ISSUE THREAD

**Issue by arnydo** [guidone/node-red-contrib-chatbot#388]
Working on configuring a MSTeams node as described in https://github.com/guidone/node-red-contrib-chatbot/wiki/Microsoft-Teams-Receiver-node but can't seem to locate a MSTeams node. Is this expected? How can I utilize the MSTeams node?

I have the latest node-red-contrib-chatbot installed.

Images below show what I am seeing.

![image](https://user-images.githubusercontent.com/11653079/73765013-f067c400-4741-11ea-8a36-04bb4b6459d2.png)
![image](https://user-images.githubusercontent.com/11653079/73765069-05dcee00-4742-11ea-84e8-f9169d6bdf7d.png)

**Comment by guidone** [comment]
You're right, for some reason the nodes were not included in `package.json`, fixed in `0.18.11`
