### ISSUE TITLE
Facebook Messenger send Buttons

### ISSUE THREAD

**Issue by webfrank** [guidone/node-red-contrib-chatbot#39]
Code for sending buttons to messenger is broken:
case 'buttons':
            // prepare buttons
            var quickReplies = _(msg.payload.buttons).map(function(button) {
              return {
                content_type: 'text',
                title: button,
                payload: button
              };
            });
            // send
            bot.sendMessage(
              msg.payload.chatId,
              {
                text: msg.payload.content,
                quick_replies: quickReplies
              },
              reportError
            );
            break;

it should be:

var quickReplies = _(msg.payload.buttons).map(function(button) {
              return {
                content_type: 'text',
                title: button.label,
                payload: button.value
              };
            });

And also html for buttons does not permit to insert value/label

**Comment by guidone** [comment]
Ok, thanks for the feedback, I'll check

**Comment by guidone** [comment]
@webfrank thanks your code works, I think I need to reorganize the nodes here:

* I'll rename the "Buttons" node in "Keyboard" and make it available just for Telegram (this option is present only in Telegram)
* I'll rename "Inline Buttons" in "Buttons" and make it available also for Facebook and Smooch. The URL and value parameters are already there, some parameters like "Button feedback", "Alert" and "New line" will be available only for Telegram

**Comment by guidone** [comment]
@webfrank this is done, v0.6.13.

Thanks for the feedback
