### ISSUE TITLE
Send message on external event 

### ISSUE THREAD

**Issue by marvincaspar** [guidone/node-red-contrib-chatbot#390]
I want to send a message if an external event was triggered. In my example when the door bell rings I want to send me a picture from the door camera. 
Here is my workflow. The green doorbell element is triggered but I don't receive any messages. I think it is because there is no chat id where the image can be send too. Is there an option to define fixed chat ids where the message can be send?

<img width="895" alt="Screenshot 2020-02-05 at 17 23 02" src="https://user-images.githubusercontent.com/2600346/73860833-70725480-483c-11ea-9aff-e8225b6f6cf7.png">

It works fine for the door command.

**Comment by guidone** [comment]
You have to start a conversation somewhere, the conversation node is the place to put the chatId

https://github.com/guidone/node-red-contrib-chatbot/wiki/Conversation-node

**Comment by marvincaspar** [comment]
Thanks, that fixed the problem.
