### ISSUE TITLE
Callback URL or Verify Token couldn't be validated

### ISSUE THREAD

**Issue by dr-boss** [guidone/node-red-contrib-chatbot#399]
I doing all like in wiki for Bot configuration (development) but I stop on creation of  webhooks with  this error:
The Callback URL or Verify Token couldn't be validated. Please verify the provided information or try again later.
and in ngrok with this information:
GET /redbot/facebook           404 Not Found
Please help me

**Comment by guidone** [comment]
Still have this problem?
