### ISSUE TITLE
Telegram multiple bots

### ISSUE THREAD

**Issue by sutidor** [guidone/node-red-contrib-chatbot#400]
For the telegram API the telegram url must be unique for each bot. But chatbot requires it to be my.site/redbot/telegram/. How can I setup multiple telegram bots?

I tried to do my.site/redbot/telegram/1 and my.site/redbot/telegram/2 but it does not work.

**Comment by sutidor** [comment]
When I look at /lib/platforms/telegram.js there is no option to add another route, correct?


```
  routes: {
    '/redbot/telegram/test': function(req, res) {
      res.send('ok');
    },
    '/redbot/telegram': function(req, res) {
      const chatServer = this;
      const json = req.body;
      if (json.message != null) {
        chatServer.receive(json.message);
      } else if (json.edited_message != null) {
        chatServer.receive(json.edited_message);
      } else if (json.callback_query != null) {            
        this.callbackQuery(json.callback_query);
      }
      res.send({ status: 'ok' });
```

What would be necessary im theory to make a multi-bot support?

**Comment by guidone** [comment]
It's possible using webhooks for Telegram

<img width="854" alt="Screen Shot 2020-07-02 at 14 37 18" src="https://user-images.githubusercontent.com/502519/86359838-d0e1b280-bc71-11ea-8186-75618a2c06a0.png">

I've released a big update in the last few weeks, it's possible that the webhooh feature in Telegram had bugs
