### ISSUE TITLE
Documentation for Slack is outdated

### ISSUE THREAD

**Issue by rcarmo** [guidone/node-red-contrib-chatbot#401]
I'm going through the Wiki and trying to set up a Slack connection, and most of the screenshots are outdated.

**Comment by rcarmo** [comment]
Also, the Slack invite link in the README and website is outdated.

**Comment by akshay7394** [comment]
Agreed, quite outdated. I wasn't able to get it working with slack though it worked fine on telegram

**Comment by smugleafdev** [comment]
Is this why I can't set it up? I thought I was making a mistake on my end.

I set up on and off triggers for ngrok, grabbed the URL it generated, added /redbot/slack to the end, but Slack won't take it. My logs show 401s. The link it gives works for me in that I can log into NR just fine, but it just will not work for Slack.

**Comment by guidone** [comment]
Ok, I'm working on this

**Comment by guidone** [comment]
The Slack connector was completely refactored in `0.19.4`, please read the [[release notes|Changelog]]
