### ISSUE TITLE
Depreciated packages

### ISSUE THREAD

**Issue by josephdouce** [guidone/node-red-contrib-chatbot#402]
![Capture](https://user-images.githubusercontent.com/1834595/76849927-3edaa900-683e-11ea-9c47-e52a3e8223ce.JPG)

**Comment by gramilla** [comment]
Did you fix this problem ?

**Comment by guidone** [comment]
It's just a warning. Not fixed, it's deprecated but it will be still around for some time, 41k modules depend on it (as the author states).
I will gradually remove it from the codebase
