### ISSUE TITLE
Delete message on telegram

### ISSUE THREAD

**Issue by alokt** [guidone/node-red-contrib-chatbot#404]
Hi,

Do nodes support to delete telegram message? I'm trying to delete the telegram message but could not find how to do it. If it is not supported i can raise a PR. 

Thanks,
Alok

**Comment by guidone** [comment]
It's not supported yet, I'll add to the roadmap.
I'm quite busy with a big refactoring, after that I can concentrate on these smaller but useful features

**Comment by daddvok** [comment]
is there any news on this?

**Comment by rcarmo** [comment]
This would also be handy for Slack.

**Comment by guidone** [comment]
This will be fixed in PR #565 (also the Slack delete message).

The documentation is already available: https://www.notion.so/redbot/Params-node-d8b27db3949c475184923af913563833
