### ISSUE TITLE
 var nodeRedUrl = $.RedBot.getNodeRedUrl(); is not a function

### ISSUE THREAD

**Issue by mectors** [guidone/node-red-contrib-chatbot#408]
The chatbot extend node in HTML is calling  var nodeRedUrl = $.RedBot.getNodeRedUrl(); just like several others but for some reason it gives the error that it is not a function. The extend platform drop-down can not be filled and as such the node cannot be used.

**Comment by guidone** [comment]
This is fixed in `0.19.3`
