### ISSUE TITLE
Message template error

### ISSUE THREAD

**Issue by webfrank** [guidone/node-red-contrib-chatbot#41]
If I have a message like this:

xxxx {{payload}} xxxx

and payload is a string everything is ok, but if payload is a number it does not get inserted.

**Comment by guidone** [comment]
I'm not sure I've understood completely, {{payload}} is something that was inserted in the chat context before?

A simple test like this

<img width="756" alt="schermata 2017-01-19 alle 15 25 10" src="https://cloud.githubusercontent.com/assets/502519/22110304/7fcbc018-de5b-11e6-9203-528f68bb1387.png">

Where the function node is

    var chat = msg.chat();
    chat.set('payload', 42);
    return msg;

and the text node is

    test {{payload}} ...

works, it aswers with 

    test 42 ...

**Comment by webfrank** [comment]
Hi, 
{{payload}} is msg.payload with a number. Before Message node I
put a Function node with code:

msg.payload =
String(msg.payload);
return msg;

This way it works.

Il 19.01.2017
15:26 Guidone ha scritto: 

> I'm not sure I've understood completely,
{{payload}} is something that was inserted in the chat context before?

> 
> A simple test like this 
> 
> [1] 
> 
> Where the function node is

> 
> var chat = msg.chat(); chat.set('payload', 42); return msg; 
> 
>
and the text node is 
> 
> test {{payload}} ... 
> 
> works, it aswers
with 
> 
> test 42 ... 
> 
> --
> You are receiving this because you
authored the thread.
> Reply to this email directly, view it on GitHub
[2], or mute the thread [3].
  


Con Smart 3 Giga a 9 euro/4 sett navighi veloce, chiami e invii SMS dal tuo smartphone verso tutti i fissi e mobili in Italia. Passa a Tiscali Mobile! http://casa.tiscali.it/mobile/

**Comment by guidone** [comment]
Ok I see now, {{payload}} is also used in the template node, it's a good idea to suppor it also here. I'll fix.

Thanks for the feedback

**Comment by guidone** [comment]
Ok, done in 0.6.14
