### ISSUE TITLE
Update messages on Slack

### ISSUE THREAD

**Issue by hnioche** [guidone/node-red-contrib-chatbot#410]
Hi! First, thanks for this plugin, it works like a charm!
I'm doing some automation using Slack and I need to build some simple UI using Slack blocks but going through several steps.

It works well but for now the UI elements are pilling up as new messages which looks a bit clunky. I'm not really willing to use a modal dialog for the interaction as it can run fairly long jobs, so it would not be the best for users....

I was thinking that the way to handle this would be to use this API from Slack https://api.slack.com/methods/chat.update but I can't find any existing node that provides it.

Is there something I'm missing or would I need to add this to red-bot? (either using the extend platform node or adding this to the plugin itself)

**Comment by guidone** [comment]
I'll add to the roadmap
