### ISSUE TITLE
Telegram down?

### ISSUE THREAD

**Issue by flamingm0e** [guidone/node-red-contrib-chatbot#411]
Since yesterday, every time a flow tries to send a message to Telegram it fails with:

Error: EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443

Is there a known problem with Telegram integration?  Is there some way I can debug this?

**Comment by flamingm0e** [comment]
I take that back.  I was able to get 2 messages through since yesterday, so this might be a problem with Telegram API?

**Comment by guidone** [comment]
It's possible, either is down or someone tried to block it (I guess the Russian government is still trying to block it)
