### ISSUE TITLE
Image + HTML caption + Buttons

### ISSUE THREAD

**Issue by mu3** [guidone/node-red-contrib-chatbot#413]
I'd like to send an image with html-formated caption and actionable buttons:

<img width="353" alt="Screen Shot 2020-05-21 at 20 56 20" src="https://user-images.githubusercontent.com/661220/82590068-ba8e0480-9ba5-11ea-8a51-9e264d559778.png">

Using [node-red-contrib-telegrambot](https://flows.nodered.org/node/node-red-contrib-telegrambot) it is possible to achieve with the following payload:

    {
      "chatId": 123,
      "type": "photo",
      "content": "https://...jpg",
      "caption": "<b>Tony Vespa</b>\n<a href=\"https://...\">link</a>",
      "options": {
        "parse_mode": "HTML",
        "reply_markup": {
          "inline_keyboard": [
            [{ "text": "⭐️", "callback_data": "rate 1" }]
          ]
        }
      }
    }

So I've adopted it for the RedBot:

    {
      "chatId": msg.originalMessage.chatId,
      "type": "photo",
      "content": "https://...jpg",
      "caption": "<b>Tony Vespa</b>\n<a href=\"https://...\">link</a>",
      "params": { "parseMode": "HTML" },
      "buttons": [{
        "type": "postback",
        "label": "⭐️",
        "value": "1",
        "answer": "Rated: ⭐️",
        "alert": false,
        "style": ""
      }]
    }

Seems that **type** must be set to `message` (for html formatting), `photo` or `inline-buttons` but not combined.

**Comment by guidone** [comment]
I recently added the [params node](https://github.com/guidone/node-red-contrib-chatbot/wiki/Params-node) which allows to set the parse mode (for telegram) for every type of messages

**Comment by mu3** [comment]
Oh thanks!
Is there a way to combine photo with buttons?

**Comment by guidone** [comment]
yes just chain them

receiver -> photo block -> text block -> sender block

https://github.com/guidone/node-red-contrib-chatbot/wiki/Changes-0.19.0

**Comment by mu3** [comment]
Chaining `Conversation > Image > Buttons > Sender` generates the following msg.payload:

    [{
      "type": "photo",
      "content": buffer[78045],
      "filename": "image.png",
      "mimeType": "image/png",
      "caption": "tony",
      "chatId": "******",
      "messageId": null,
      "inbound": false
    }, {
      "type": "inline-buttons",
      "name": null,
      "content": null,
      "chatId": "******",
      "messageId": null,
      "buttons": [{
        "type": "postback",
        "label": "⭐️",
        "value": "1",
        "answer": "Rated ⭐️",
        "alert": false,
        "style": ""
      }]
    }]

And only the first item is sent.
I want to combine them:

    "type": "photo",
    "buttons": [...]

**Comment by guidone** [comment]
Ok, I think it's technically possible

https://core.telegram.org/bots/api#sendphoto

Telegram allows to add buttons to every type of message, the problem is that other platforms don't, so I have to come up with something that doesn't break the compatibility with other platforms and it's not too specific.

Let me think about it
