### ISSUE TITLE
Postback botton  do not work on a conversation node.  

### ISSUE THREAD

**Issue by federicotellez** [guidone/node-red-contrib-chatbot#414]
Hi there ,
If I begin a conversation with a specific chatId  and pass it to a button node with postback for the first run it will work. If I  Deploy and run it again the messageId of the first conversation stays in the postback and do not match with the messageId of the new conversation so it never recognizes the postback and the flow ends. I need to stop node-red and run it again in order to make the postback work but again just for one time because messageId from my respond never changes in the complete flow after Deploy.  Can you please let me know  how can I  fix this issue?

**Comment by guidone** [comment]
Can yout post a picture of the flow?

**Comment by federicotellez** [comment]
Thanks, suddenly the problem was fixed.

I didn't change anything and it worked.

Thanks

Federico
