### ISSUE TITLE
Conversation node cannot set chatbot

### ISSUE THREAD

**Issue by roozeboos** [guidone/node-red-contrib-chatbot#415]
Hi,
I have had it al working , but since the last update I cannot choose the variables like the  bot in the configuration node. I cannot choose my bot, and so I get the error that it is not send.
There is no list with possible bots, also the transport box is empty!

With a function using payload I can set the id and the Telegram and pass it to conoversation node.
Unfortunately i cannot pas the bot name.
howto solve this?
Chris

**Comment by roozeboos** [comment]
Anybody??

**Comment by guidone** [comment]
I pushed a big update, do you still have the problem?
