### ISSUE TITLE
Nodes not showing in palette after install on latest NR

### ISSUE THREAD

**Issue by craigcurtin-dev** [guidone/node-red-contrib-chatbot#416]
I have the latest version of Node-red 1.0.2 - attempted install from within Palette manager - install appeared to go OK after enabling selected nodes (Telegram and Slack) nothing shows in the sidebar.

Performed a restart of Node-red - Ubuntu - systemctl restart nodered as root - no difference - nothing in sidebar - but palette manager thinks i have enabled the nodes

Restart the Virtual machine - no difference

Uninstall from the Palette manager, reboot NR, reinstall from the commandline as basic user where NR runs from - errors re a number of deprecated nodes but install finalised

Restarted NR - confirmed seen in palette manager - re enabled the nodes - still nothing showing in sidebar

Appears to be broken - this is on Ubuntu 18.04 LTS

Craig

**Comment by guidone** [comment]
do you see any errors in the system console?

**Comment by Edo78** [comment]
I'm experiencing the same problem on NR v1.2.7 (installed with docker). The installation of this package showed no error and even a restart there are no error in the logs and but still no luck ...
```
18 Jan 17:12:42 - [info] 
Welcome to Node-RED

===================

18 Jan 17:12:42 - [info] Node-RED version: v1.2.7
18 Jan 17:12:42 - [info] Node.js  version: v10.23.1
18 Jan 17:12:42 - [info] Linux 5.10.7-v7l+ arm LE
18 Jan 17:12:43 - [info] Loading palette nodes
Mon, 18 Jan 2021 16:12:53 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal/modules/cjs/loader.js:778:30
18 Jan 17:12:54 - [info] RedBot version: 0.19.7 (node-red-contrib-chatbot)
18 Jan 17:12:54 - [info] Dashboard version 2.23.4 started at /ui
18 Jan 17:12:54 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
18 Jan 17:12:56 - [info] Settings file  : /data/settings.js
18 Jan 17:12:56 - [info] Context store  : 'default' [module=memory]
18 Jan 17:12:56 - [info] Context store  : 'file' [module=localfilesystem]
18 Jan 17:12:56 - [info] Context store  : 'thermostat' [module=localfilesystem]
18 Jan 17:12:56 - [info] User directory : /data
18 Jan 17:12:56 - [info] Server now running at http://127.0.0.1:1880/
18 Jan 17:12:57 - [info] Active project : home-assistant-integration
18 Jan 17:12:57 - [info] Flows file     : /data/projects/home-assistant-integration/flows.json
18 Jan 17:12:57 - [info] Starting flows
18 Jan 17:12:57 - [info] Started flows
```

**Comment by Edo78** [comment]
I'm not sure what I've done ... I uninstalled/reinstalled/restarted everything multiple times and now it's working
