### ISSUE TITLE
Telegram authorized node doesn't work

### ISSUE THREAD

**Issue by egorvas** [guidone/node-red-contrib-chatbot#417]
Hi, I tried to use authorized node for the telegram receiver.
My configuration at the settings.json look like:
![image](https://user-images.githubusercontent.com/7426788/85196277-cfaf9d80-b2e1-11ea-91a5-92d5f5bb71e9.png)
Test flow is:
![image](https://user-images.githubusercontent.com/7426788/85196317-130a0c00-b2e2-11ea-9d21-495f73de3154.png)
I also tried to use any kind of telegram ids like: 'Egorvas,@Egorvas,86733501,egorvas,@egorvas'
It also doesn't work if I configure telegram receiver at the UI.
What am I doing wrong?

**Comment by guidone** [comment]
Should be fixed in `0.19.1`, let me know if it works (userId in Telegram are integers and in the config are strings, but should work).

Thanks for the feedback

**Comment by egorvas** [comment]
@guidone, but seems that nothing changed...
This is configuration which I'm using:
![image](https://user-images.githubusercontent.com/7426788/85272887-73857e80-b485-11ea-878d-5b8d1f7e5b60.png)
This is debug:
![image](https://user-images.githubusercontent.com/7426788/85272975-99ab1e80-b485-11ea-9e56-7c6deb4b6acf.png)

By the way:
Seems that "parseMode: 'html'" configuration not working as well.
I have to use parameter node to display message like: "<b>Message</b>"

**Comment by guidone** [comment]
Ok I've to test locally, I'll get back to you on this.

For the parseMode yes, it's no longer a global variable, it's a flow variable and yes for this reason you have to add the param node (I've updated che documentation)

**Comment by guidone** [comment]
Ok a bit of refactoring was needed here, please revert the changes in your _settings.js_ file, the right key is _usernames_ (I've updated the [docs](https://github.com/guidone/node-red-contrib-chatbot/wiki/Global-Configuration)).

It should work in `0.19.2`

**Comment by egorvas** [comment]
Its perfect now. Thank you!

**Comment by guidone** [comment]
🖖
