### ISSUE TITLE
chatbot-inline-buttons node shows error when I add "URL button" with {{payload.url}}

### ISSUE THREAD

**Issue by egorvas** [guidone/node-red-contrib-chatbot#418]
Hi, I have configured chatbot-inline-buttons node like this:
![image](https://user-images.githubusercontent.com/7426788/85196702-b78d4d80-b2e4-11ea-9453-ba0ab684864e.png)
But it shows error(but work) on the node and before every deployment.
If I change {{payload.url}} to hardcoded url like https://www.google.ru everything works well

**Comment by guidone** [comment]
Ok it's a validation problem of the front end, I will fix it shortly thanks for reporting

**Comment by guidone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix validation of buttons in the frontend](https://trello.com/c/Y3DzwTtc/32-fix-validation-of-buttons-in-the-frontend)

**Comment by guidone** [comment]
Fixed, thanks for the feedback
