### ISSUE TITLE
Response changes identity

### ISSUE THREAD

**Issue by webfrank** [guidone/node-red-contrib-chatbot#42]
Hi, I have a simple bot which replies with a message like: "Hi {{firstName}}" and is ok, I got my name when I start it.

Some step ahead I issue a /back command (from a button) which points me to the start message but this time I got "Hi <<Bot Name>>" and not my name, why?

**Comment by guidone** [comment]
Are you using telegram?

**Comment by webfrank** [comment]
Yes


In data 24 gennaio 2017 7:59:45 PM Guidone <notifications@github.com> ha 
scritto:

**Comment by guidone** [comment]
Good catch @webfrank, fixed in 0.6.15. Thanks for the feedback
