### ISSUE TITLE
Is it way to handle chatbot-telegram-node error information?

### ISSUE THREAD

**Issue by egorvas** [guidone/node-red-contrib-chatbot#420]
Hi @guidone, I faced with situation when my buttons node has an error:
```
Error: ETELEGRAM: 400 Bad Request: BUTTON_DATA_INVALID
25 Jun 10:48:47 - [error] [chatbot-telegram-node:d45d71eb.8ac9a] Error: ETELEGRAM: 400 Bad Request: BUTTON_DATA_INVALID
```
Is it way to catch this error and get information like msg.payload or msg.anyOther for understanding an issue?
I tried to use the "catch node" but it returns nothing. Also, I tried to use debug: true option in telegram node configuration, but nothing as well.

In my case issue was because of too long button feedback value(value length more than 64 characters). Is it real limitation of telegram?

**Comment by guidone** [comment]
Ok, another user asked for this, I will provide an error pin of the sender node.

I'll work on this next week

Thanks for the feedback

**Comment by guidone** [comment]
@egorvas in `0.19.3` you can now enable and error pin in the sender node
