### ISSUE TITLE
Documentation possibly out of date for Slack setup

### ISSUE THREAD

**Issue by smugleafdev** [guidone/node-red-contrib-chatbot#421]
I say possibly because this may be user error.

Following the [Slack guide](https://github.com/guidone/node-red-contrib-chatbot/wiki/Slack-Receiver-node), it seems the Ngrok portion is out of date since the screenshots show the older layout of Slack API. I expect that since I'm having so much trouble with it, there are other portions that are out of date as well.

I'm using HomeAssistant with the NodeRed add-on. I downloaded the Ngrok node package and generated a URL that I gave to Slack on the Events page and formatted it as https://[numbersandletters].ngrok.io/redbot/slack. Slack responds with:

> Your URL didn't respond with the value of the challenge parameter.

NR logs say:

> 401 <ipaddress>(127.0.0.1) POST /redbot/slack HTTP/1.1 (Slackbot 1.0 (+https://api.slack.com/robots))

If I paste the URL into my browser and received an auth popup. I filled out my HA login and username and was greeted with my NR page. So it seems it properly links to NR, but Slack doesn't like it.

I assume Slack changed their API and the additional steps necessary are not included in the documentation.

**Comment by guidone** [comment]
Unfortunately is not an easy fix, they basically changed the permission scheme.
Everytime you read "improvement" in Slack, you should read "revolution".

Basically the "bot" scope is no longer available, replaced by a more granular permission model, unfortunately these new permissions doesn't include listening to events, so they are basically deprecating the RTM Client for chatbots with the Event API. Old applications still works (until the end of the year), new applications cannot use RTM for bots (and of course RedBot uses RTM).

I'll start working on the update

**Comment by smugleafdev** [comment]
That's rough. Guess I better look into Slack's API.

**Comment by guidone** [comment]
I'm working on this

**Comment by guidone** [comment]
Fixed in `0.19.4`
