### ISSUE TITLE
Telegram bot not working since update

### ISSUE THREAD

**Issue by flamingm0e** [guidone/node-red-contrib-chatbot#424]
Updated to version `0.19.3` on Monday.  Restarted docker container.  My flows with my chatbot do not show a problem and don't log any errors, but in docker logs I see this every time something tries to send an alert to my telegram bot:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'sourceCode' of undefined at /data/node_modules/chat-platform/chat-platform.js:505:34
```

Same message every time.  I am going to remove the palette and try to reinstall.  Will update.

**Comment by flamingm0e** [comment]
No change.  Still receiving the same error.

Rolling back to 0.18.15 didn't resolve either.  Could this be because of Node Red updates as well?

**Comment by flamingm0e** [comment]
Removed all config for bot, readded bot, tried a different bot...same error messages.

Used another palette to make sure it wasn't a problem with Node Red or Telegram, and the other palette worked.

Anyone have any insight where I can start looking?  Perhaps I missed a notice in an update about changing format of the message?

**Comment by guidone** [comment]
It's possible, I'm running the latest version of RedBot and Node-RED and it works, let me check the code

**Comment by guidone** [comment]
This is strange, the piece of code that breaks is 

```
.catch(function (error) {
  error.sourceCode = filter.toString();
  reject(error);
});
```

which is strange, there's something that raises an error but without the error. In order to get a better explanation of this can you add a console.log in the catch function?

Edit the .node-red/node-modules/chat-platform/chat-platform.js line 505, and add

```
.catch(function (error) {
  console.log('Strange error:', filter.toString()); // add this
  error.sourceCode = filter.toString();
  reject(error);
});
```

**Comment by flamingm0e** [comment]
Finally had a chance to test that out.

This is what I get now:

`Unable to find a valid chat context instance for the selected context provider`

I have a path set for my file context, and a log file.

This is weird that this would have stopped after the node red update.  I have not had any real issues prior.

Something else that's bothering me, is that random people are adding my bot to channels/groups and when they do it's creating a new file in my context file path.

**Comment by flamingm0e** [comment]
It appears to be working right now?  I am baffled.

I will monitor and make sure it is stable over the next day or so.  I should know by tomorrow if it's still broken.

**Comment by flamingm0e** [comment]
I seem to be getting all the notifications that I have configured but I am still seeing this a LOT in the logs.  It's actually spamming my log all day

```
error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443"}
Error: EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443
20 Jul 21:01:16 - [error] [chatbot-telegram-node:8819b2a2.272e2] Error: EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443
```

**Comment by guidone** [comment]
Hi @flamingm0e still having the last issue?
