### ISSUE TITLE
Most everything for slack seems to not work

### ISSUE THREAD

**Issue by rlewkowicz** [guidone/node-red-contrib-chatbot#43]
When piping from slack receiver to just about anything I get "ReferenceError: self is not defined". If I just do receiver to output, it works just fine (it just echos my input). I see some comments that say that the slack module needs some love which is super ok, It'd still be nice to have that disclaimer up front vs trying it and being like why the heck does this not work (if it does indeed not work).

**Comment by cerebrate** [comment]
I'm having the same set of issues; while it works for my most trivial need (notifications via slack), being able to at least get the Listen node working would be nice.
