### ISSUE TITLE
Conversation node problem

### ISSUE THREAD

**Issue by pilip87** [guidone/node-red-contrib-chatbot#430]
I've just updated node red from a very old version to the lastest v1.1.2
I've also update node-red-contrib-chatbot palette to 0.19.3

I use node red in a docker container

When I create a conversation node I can't select transport or bot configuration, so I get the error "chatId was correctly specified but without a valid chatbot configuration" and I'm unable to  send telegram messages.

Can someone pleas help me to solve my issue?

Thank you

Filippo

**Comment by pilip87** [comment]
Also if I use a funcion node like this:
msg.payload=
{
    "transport": "telegram",
    "chatId": "XXXXXX"
}
return msg;

followed by conversation node, I got the same error

**Comment by guidone** [comment]
If you open the browser console do you see any failed call 404?

**Comment by node-red-italia** [comment]
I  have the same problem, and when open a conversation node  I receive a dialog box for autentication (below).


![aut](https://user-images.githubusercontent.com/64190779/87588670-56d71200-c6e4-11ea-8baa-eb4b472ca54a.PNG)

**Comment by pilip87** [comment]
> If you open the browser console do you see any failed call 404?

My raspberry died yesterday. Now I've moved over Hass.IO where i'm looking if it's possible to install. Sorry but can't check anymore atm

**Comment by node-red-italia** [comment]
@pilip87 I have resolved a question. After the authentication I have set the transport section.

In settings.js file I have previusly set a httpNodeAuth and httpStaticAuth.

Try this.
