### ISSUE TITLE
Problem with request from FB test account

### ISSUE THREAD

**Issue by crboschi74** [guidone/node-red-contrib-chatbot#431]
After created the BOT, I make the request to FB to enable for production, request for pages_messaging.

When arrive themessage from user test of FB, i receive one error on the log.. and the user test of FB BOT not receive the response..so FB reject my request.

The error is:
Unable to get profile info for user

Can You Help me?

**Comment by crboschi74** [comment]
I try to check the code... the problem is in facewbook.js at function getProfile...

**Comment by guidone** [comment]
Sorry for the delay.
For some reasons the page doesn't have the rights to get the user profile, can you check here

https://developers.facebook.com/docs/messenger-platform/identity/user-profile/#request

In particular section "Requesting feature access to user fields for the Page"
