### ISSUE TITLE
cannot send image

### ISSUE THREAD

**Issue by ghost** [guidone/node-red-contrib-chatbot#435]
hi, i have installed nodered on windows, but i cannot send image to telegram, on windows.
i need to send image from my desktop to telegram user.
i tried many methods, but on image node exit, i nothing receive, no errors, no logs, nothing!
i tried to read file using file, i tried using function, i tried to put URL directly in image node, locally, and from http, but nothing results.
![image](https://user-images.githubusercontent.com/20506433/90009940-aa1e8f00-dca7-11ea-869d-97d78b2bd915.png)
thanks, best regards

**Comment by guidone** [comment]
Do you see anything in the system console? 
I'm running in Mac so I cannot try with a similar file path, have you tried removing the double backslash?

As last resort try loading the file with a Node-RED's file node and set the output as buffer then connect it to the image node, if it still doesn't work then there's something wrong with the path
