### ISSUE TITLE
Random rule for answering

### ISSUE THREAD

**Issue by GRawhideMart** [guidone/node-red-contrib-chatbot#445]
Hello!
As in object, I am trying to build a Telegram chatbot with your library, but I am having a hard time figuring out a couple of things.
Among them, I wish to set the bot inside a group, but in order to not bother people, it has to answer only one time out of 15. I can't see inside the rule node such a thing, I tried to implement a function node to set msg.payload to true only if Math.random (normalized to return a number between 1 and 15) is 1, but this doesn't work. Can someone tell me more?

**Comment by guidone** [comment]
```javascript
Math.round(Math.random()*16) === 1
```

should work
