### ISSUE TITLE
Keyboard buttons dissapears when edit buttons

### ISSUE THREAD

**Issue by donsergiobejarano** [guidone/node-red-contrib-chatbot#448]
Hi, I am using Node-Red v1.2.2 and Chatbot v0.19.7 in Debian 10. Installed with Debian/Rasbperry .sh script. If install with npm same issue.

When add a keyboard and create the buttons, accept and deploy... if open again the keyboard the buttons have dissapeared...

Is a bug? A operating system issue?

Is any way to fix it?

Thanks!!

**Comment by GitUser0001** [comment]
Hi, I have the same issue.

Node-RED version: v1.2.6
Node.js  version: v14.15.3
Windows 10

thanks in advance!

**Comment by neutronica** [comment]
I have the same issue on the Node-RED version 2.2.0 (last version).

**Comment by neutronica** [comment]
The same issue remains on the Node-RED version 3.0.2 and node-red-contrib-chatbot version 1.2.0, and there is no field to enter a label for button.

**Comment by guidone** [comment]
Ok, I'll check this, seems Telegram introduced some changes about keyboards

**Comment by guidone** [comment]
done in `1.2.1`.

Check Params node for keyboard flags

**Comment by neutronica** [comment]
It is working now! Thanks!!!
