### ISSUE TITLE
MarkDown Option

### ISSUE THREAD

**Issue by dedynobre** [guidone/node-red-contrib-chatbot#449]
Hello,

after I upgraded to version 0.19.7 there was no option to select the text as .html or markdown in the bot configuration.

Is this no longer available or am I doing something wrong?

**Comment by doucreator** [comment]
Hello! To configure messaging options, use Params node before Telegram Sending node

![image](https://user-images.githubusercontent.com/1189977/103120932-589dfc00-46ac-11eb-9144-311b16b59ac7.png)

**Comment by dedynobre** [comment]
Ahh Okay.

Thank you!
