### ISSUE TITLE
Rules Node is not working properly

### ISSUE THREAD

**Issue by doucreator** [guidone/node-red-contrib-chatbot#456]
Hi!
I have context
![image](https://user-images.githubusercontent.com/1189977/103282624-f4ab6880-4a08-11eb-8d49-1215190ed5e7.png)

I tried using Rules Node in 2 ways:
1. "The context variable is defined" - not working if checking object property
![image](https://user-images.githubusercontent.com/1189977/103282765-5cfa4a00-4a09-11eb-8955-03b30e90fc34.png)

2. "The context variable ... is ..." - not working
![image](https://user-images.githubusercontent.com/1189977/103283158-59b38e00-4a0a-11eb-92e8-9f729774d4d1.png)

What am I doing wrong?

**Comment by guidone** [comment]
1 is not supported yet
2 I'll add some louse checking (1 == "1" instead of 1 === "1")
