### ISSUE TITLE
Catch telegram error 403

### ISSUE THREAD

**Issue by webfrank** [guidone/node-red-contrib-chatbot#46]
When sending a message to a user (chatId) which has deleted and blocked the bot, I receive the following error on the debug tab:

 
7/2/2017, 14:52:46
msg : error
Error: 403 {"ok":false,"error_code":403,"description":"Forbidden: Bot was blocked by the user"}

But I cannot catch it using catch node. What could I do? I need to delete the corresponding chatId from my db.

**Comment by guidone** [comment]
I see, it's not triggering the catch node. I'll fix, thanks for the feedback

**Comment by guidone** [comment]
@webfrank would you like to try this beta?

    npm install node-red-contrib-chatbot@0.6.18-beta-1

It's a beta, I've to fix the error handling also for Facebook Messenger

**Comment by webfrank** [comment]
Hi,

     it works perfectly.


Il 10/02/17 15:28, Guidone ha scritto:
