### ISSUE TITLE
Telegram. mp3-file and video_note -- DISCARDED MESSAGE (not handled by middlewares) --

### ISSUE THREAD

**Issue by doucreator** [guidone/node-red-contrib-chatbot#460]
Hey. I am testing a simple flow
![image](https://user-images.githubusercontent.com/1189977/104832219-3457c880-58c2-11eb-89af-0851f1c2c0e6.png)

When I submit a **video_note** or **mp3-file**, the debug node doesn`t display a message in the debug window. The console displays the following message

![image](https://user-images.githubusercontent.com/1189977/104832313-f27b5200-58c2-11eb-84ab-3ef3d238e0c8.png)

And another question. The Node.js Telegram Bot API already supports Bot API 5.0. Are you planning to upgrade the **node-telegram-bot-api** dependency from version 0.40.0 to 0.51.0?

**Comment by guidone** [comment]
Now is able to receive vide notes and telegram-bot-api update.
Thanks for the support
