### ISSUE TITLE
bug with message editing 

### ISSUE THREAD

**Issue by daddvok** [guidone/node-red-contrib-chatbot#467]
When I try to edit the message sent by the button node, my inline buttons change, and everything is correct. But the text remains from the old message. That is, the buttons change, but the text remains unchanged, what could be the problem? I use the params node, select modify message inside, attach it in front of the out node.

Node-red -v 1.2.6
chatbot -v 0.19.7

**Comment by onestix** [comment]
I am observing the same problem.
