### ISSUE TITLE
Support for Slack websocket API

### ISSUE THREAD

**Issue by rcarmo** [guidone/node-red-contrib-chatbot#471]
Slack has a new transport that does away with the need to handle web hooks and has the potential to make integration a lot cleaner - https://api.slack.com/apis/connections/socket 

It does, however, require the new auth model and scopes, so it's not likely to be a trivial thing to add. Nevertheless, I thought it was a good idea to file an issue for roadmap purposes...

**Comment by samtaav** [comment]
Bumping this here. Would love to see the Sockets integration in place. This way, one can avoid exposing internal services to the public. @guidone, any thoughts?

**Comment by rcarmo** [comment]
Bumping this too. I've recently come across two situations where I had to use other stuff to talk to Slack and build a bot, and this would be much easier altogether.

**Comment by guidone** [comment]
Ok, I'll investigate

**Comment by onestix** [comment]
Thanks @guidone happy to see it's been picked up! Appreciate it very much! 

CC @rcarmo
