### ISSUE TITLE
Does redbot install/use nlp.js v3 or v4

### ISSUE THREAD

**Issue by ninjamoba** [guidone/node-red-contrib-chatbot#474]
Does redbot install /use nlp.js v3 or v4?

Can someone elaborate on these nodes please?

**Comment by estalldecker** [comment]
hi @ninjamoba 

if you take a look at the [package.json](https://github.com/guidone/node-red-contrib-chatbot/blob/master/package.json) you'll be able to see that it installs v4 in line 126:

`  "node-nlp": "^4.10.4",`

**Comment by guidone** [comment]
👍
