### ISSUE TITLE
builtin entities missing

### ISSUE THREAD

**Issue by pmjgeraeds** [guidone/node-red-contrib-chatbot#478]
i have installed node-red-contrib-chatbot version 0.19.7
and don't get the builtin entities like number, email, age, duration etc. to be picked up by the NLP engine.

I refer to them in the intends like shown in the examples:
I want %number% %fruit%

although fruit is picked up as expected, any number is ignored. 
NO error messages in the logging or whatsoever.

note: I running nodered in a docker container on rancheros.

for reference the docker-compose setting: 
note: I running two nodered instances 1) node-red (port 1880) and  2) node-rood (port 1881)
but that should be the issue, because everything else is running perfectly.

node-rood:
    image: nodered/node-red:latest
    restart: always
    depends_on:
      - mssql
      - mosquitto
      - node-red
    container_name: noderood
    environment:
      - TZ=Europe/Amsterdam
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone
    ports:
      - "1881:1880"
    networks:
      - default
    volumes:
      - /home/rancher/.node-rood:/data

**Comment by pmjgeraeds** [comment]
please forget this issue, it somehow resolved itself (maybe an installation issue)

**Comment by estalldecker** [comment]
Hi @pmjgeraeds, how did you solve it? I'm having the same issue running it locally and by debugging it I found that nlp.js returns those values in a different variable that is not used by the [chatbot-nlp.js](https://github.com/guidone/node-red-contrib-chatbot/blob/master/nodes/chatbot-nlp.js) (NLP Process) node. 

I just opened a PR but was wondering if you know how you fixed it.

Thanks!

**Comment by pmjgeraeds** [comment]
HI estalldecker,
the problem is partly solved : 
- I hardcoded the slotting scripts in the chatbot-nlp-train.js file (like many of the examples provided for nlpjs or equal sites), this got the slotting logic working. 
However chatbot-nlp.js does not show this in the payload. Hence the variables like .slotfill .scrAnswer .Answer .etc are not visible / available in the payload. Hence I modified the chatbot-nlp.js javascript to create an extra output in the msg. called NLP to make that available for further processing. In this msg.NLP all of these variables are visible. This indicated (see image) that Slotting is working and I could procede to the next step.
- Part which is not working : the logic of slotting is that it should keep track of slots filled and slots to be filled and send a response accordingly. Specifically in the example : i saw {{person}} eat {{fruit}}. if i first would send a message "I saw somebody eat apples" NLP-slotmanager will pick up the entity {{fruit}}=apples, and send the scrAnswer "whom did you see eating apples" once I send a message  "pascal" I would expect the slotmanager to fill the remaining slot {{person}}= pascal. and finish the conversation with an answer like "Wow did you see pascal eat apples" or something similar.
The problem is that I can't make the NLP engine remember the allready filled slot and finalise the conversation, but instead respond with a scrAnswer "and what did you see Pascal eat" and staying in a loop to either get the {{person}} or {{fruit}} slot filled. But never have both filled.
This is why I opened another issue to Guido to get advice on what I am doing wrong.
In this other issue (#480) I also copied my flow, to understand my way of thinking.

![image](https://user-images.githubusercontent.com/58753832/117164050-8d416300-adc4-11eb-8395-e9665441ee01.png)

`     let intent = 'None';
      if (response.score > scoreThreshold) {
        intent = response.intent;
      }

// --------- modified by PGE -------------

     msg.NLP=response;      

//------------------------------------- 
 
      send({
        ...msg,
        previous: msg.payload, // store previous msg, use POP to retriev
	payload: {
          type: 'intent',
          score: response.score,
          isFallback: intent === 'None',
          language: response.localeIso2,
          intent,
          variables: !_.isEmpty(variables) ? variables : null
        }
`

**Comment by pmjgeraeds** [comment]
Hi estalldecker,

to add to this answer I also modified the chatbot-nlp.js to show the entity.resolution for date and numbers.

gr. Pascal

`// finally process
      const response = await manager.process(language, content);

      // extract vars
      const variables = {};

     // -------------modified by PGE ----------------

 	(response.entities || []).forEach(entity => {
		switch (entity.entity ){
		     case 'date' :
			variables[entity.entity]=entity.resolution.strValue;
			break;
		     case 'number' :
			variables[entity.entity]=entity.resolution.value;
			break;
		     default: variables[entity.entity]=entity.option;
		}
 	});

     // ------------- end of modification ----------

      if (debug) {
        // eslint-disable-next-line no-console
        console.log(lcd.white('[NLP] ') + lcd.grey('Processing model ') + lcd.green(name));
        // eslint-disable-next-line no-console
        console.log('`

![image](https://user-images.githubusercontent.com/58753832/117177692-9ab11a00-add1-11eb-91c9-d9d92148c9c5.png)

**Comment by pmjgeraeds** [comment]
Hi @guidone,

Would you consider adding this piece of code to your next release?

gr. Pascal

**Comment by guidone** [comment]
In this release I've added BER = true by default, it's extracting all default entities and it uses aliases for name, it also normalize some values, it's in 0.19.9 published in a while
