### ISSUE TITLE
Telegrambot Receiver doesn't receive every message

### ISSUE THREAD

**Issue by joshis9** [guidone/node-red-contrib-chatbot#481]
Hi, 

I'm building a telegram bot on node-red, but the receiver works only sometimes and not for every single message. 
the flows are very huge so i created a second bot to test it on smaller flows and it worked fine. I observed the message_ids of the bot, that only works sometimes. And the message_Id counted up even the receiver didn't work. I think that means, that the messages arrives the Telegram Server but the Receiver can't reach them. But why?? the bot with small flows receives all incoming messages. I also changed the bots and the problems are still on the bot with the huge flows. 
Can you help me?

**Comment by guidone** [comment]
It's my understanding that is not a matter of traffic load, but complexity of the flow.
It's likely something in the flow implementation is not working well, did you enabled the debug flag in the telegram bot?
