### ISSUE TITLE
Warning Message

### ISSUE THREAD

**Issue by dedynobre** [guidone/node-red-contrib-chatbot#490]
HI!

On my NR I have four bots configured.
3 of them is showing the error below.
Already deleted the settings and redid and still remains the same. Even with the message the bots are working normally.

![image](https://user-images.githubusercontent.com/8119694/126156193-e0e23beb-9b46-4fcc-b043-f9c61b9a96fe.png)

**Comment by guidone** [comment]
I think it's because all bots installs a route /redbot/telegram, then everyone is trying to remove it when it closes but only the first succed.
Nothing to worry about

**Comment by dedynobre** [comment]
Okay.
Thanks
