### ISSUE TITLE
Facebook Messengaer location no longer works. Location Quick Reply is now deprecated on API 4.0.

### ISSUE THREAD

**Issue by shadyshrif** [guidone/node-red-contrib-chatbot#495]
Using Request node - Location

`(#100) Location Quick Reply is now deprecated on API 4.0. Please refer to our Developer Documentation for more info.
8 Sep 13:30:53 - [error] [chatbot-facebook-node:934b0686a349ab25] (#100) Location Quick Reply is now deprecated on API 4.0. Please refer to our Developer Documentation for more info.
8 Sep 13:30:53 - [error] [chatbot-facebook-send:48fc53dee10183c3] (#100) Location Quick Reply is now deprecated on API 4.0. Please refer to our Developer Documentation for more info.`

**Comment by guidone** [comment]
Working on it
