### ISSUE TITLE
Send two ore more pictures...

### ISSUE THREAD

**Issue by mac-d** [guidone/node-red-contrib-chatbot#498]
Hello, basically chatbot works great.

Beginner question ...
How can I send two or more pictures in one message?

Thanks for a short help ...

**Comment by guidone** [comment]
You just chain two image nodes and connect the last one to the sender node

**Comment by mac-d** [comment]
Hello, I know that you can send several pictures in parallel or one after the other.
Every picture is a message.

In the Telegram APP, however, I can send several images as one message. 
Is that also possible with the chatbot?

**Comment by guidone** [comment]
I don't see this option in the sendPhoto method

https://core.telegram.org/bots/api#sendphoto

**Comment by mac-d** [comment]
Hello, with Telegram WEB or on the smartphone you can send 2 or more
pictures together as one message. I cannot say whether this can also be
done via the API.

[image: image.png]

Schöne Grüße

Dieter
*K U P K A*

Steinleiten 1 * 85302 Gerolsbach
Fon +49 8445-1003 * Fax +49 8445-911337


Am Mi., 22. Sept. 2021 um 15:49 Uhr schrieb Guidone <
***@***.***>:

**Comment by zba** [comment]
> I don't see this option in the sendPhoto method
> 
> https://core.telegram.org/bots/api#sendphoto

https://core.telegram.org/bots/api#sendmediagroup

iti is sendMediaGroup
