### ISSUE TITLE
Api.Ai Action

### ISSUE THREAD

**Issue by fcioffi** [guidone/node-red-contrib-chatbot#50]
Hi,

is possibile to get action when output from api.ai node?

Thanks,
Francesco

**Comment by soundman666** [comment]
Hi,
I was able to get the 'action'. But I have a problem with a topic: I get an array of several topics, do not understand how to reset them.

![image](https://cloud.githubusercontent.com/assets/11494430/23537933/14f14486-ffd8-11e6-8f8a-a94af04c9035.png)

**Comment by ram1505** [comment]
If I'm not wrong, API.AI sends the final outcome of the conversation in the form of "Fulfillment". To access fulfillment data, one must enable websocket. Correct me if my understanding is wrong.
