### ISSUE TITLE
Telegram authenticate by chat id

### ISSUE THREAD

**Issue by vfilter** [guidone/node-red-contrib-chatbot#506]
Hi, maybe I've overlooked a way to do this, but I cannot find an option to authenticate via chatid instead of user id. We want to have multiple users in a chat able to interact with the bot without having to authenticate each one of them separately. Is that possible right now?

**Comment by guidone** [comment]
the chatId is available in `msg.originalMessage`, my advise is to create a flow to handle the authentication.
This is the approach used in the future release with Mission Control, the connectors should not be aware of any authentication concerns.
