### ISSUE TITLE
[CRITICAL] msg.sentMessage.messageId

### ISSUE THREAD

**Issue by Iciir** [guidone/node-red-contrib-chatbot#510]
`msg.sentMessage.messageId`

is not set correctly after [**Telegram Sender**], it's the same as

`msg.originalMessage.messageId`

This is causing me some problems right now, temporarily I do +1 on the original `messageId`.

⋄

Before updating, I was using a technique, getting it from

`payload.params.modifyMessageId`

but now that doesn't work anymore.

**Comment by guidone** [comment]
This should be fixed

https://www.notion.so/redbot/Params-node-d8b27db3949c475184923af913563833
