### ISSUE TITLE
[Buttons node] has been broken by the last update.

### ISSUE THREAD

**Issue by Iciir** [guidone/node-red-contrib-chatbot#511]
Feedback without pop-up is missing and feedback through pop-up does not work.

**Comment by Iciir** [comment]
Actually this might be a current Telegram bug, feedback in past posted menus also don't work. 🤔️

**Comment by guidone** [comment]
I see it working now

<img width="1025" alt="Markup 2022-03-13 at 13 44 24" src="https://user-images.githubusercontent.com/502519/158059976-160639e3-b8f2-477e-8ca9-9d311bb6571e.png">
