### ISSUE TITLE
Messenger Template carousel not working

### ISSUE THREAD

**Issue by Nayar** [guidone/node-red-contrib-chatbot#512]
I tried using the demo object

```
msg.payload = {
  elements: [
    {
      templateType: 'generic',
      title: 'my title',
      subtitle: 'I am a sub title',
      imageUrl: 'http://image.server.com/cover.png',
      buttons: [
        {
          type: 'url',
          url: 'http://javascript-jedi.com',
          label: 'Javascript Jedi'
        }
      ]
    },
    {
      templateType: 'generic',
      title: 'another title',
      subtitle: 'Second sub title',
      imageUrl: 'http://image.server.com/cover2.png',
      buttons: [
        {
          type: 'url',
          url: 'http://javascript-jedi.com',
          label: 'Javascript Jedi'
        }
      ]
    }
  ]      
}
return msg

```

![Screenshot_20211110_001901](https://user-images.githubusercontent.com/454815/140998335-3141323a-ef61-409e-ad32-263a261bb5de.png)

And I get the following errors:

```
"(#194) param name_placeholder[elements][0][buttons] has too few elements."
```

![Screenshot_20211110_002125](https://user-images.githubusercontent.com/454815/140998660-0ee3d4c7-1ba2-4f8c-a51b-d5363121d86b.png)

I've been getting this issue since I upgraded to 0.19.11. The deprecated Generic Template node also doesn't work.

**Comment by guidone** [comment]
Ok thanks for the feedback, fixed in `0.19.13` available in few hours
