### ISSUE TITLE
Uncovered use-case with webhook and ngrok

### ISSUE THREAD

**Issue by djok** [guidone/node-red-contrib-chatbot#513]
before everything, great job.

Let's have configuration with free ngrok tunnel to node-red and redbot with viber webhook.

Every time when we start ngrok we will have new unique public URL, on the other hand we can't set automatically/dynamically this new unique public URL  as webhook URL in redbot.

Is there a way to set redbot webhook config dynamically?

vbr,

**Comment by guidone** [comment]
Hi, there are few roads:

- with a paid account in ngrok it's possible to have a fixed name for the tunneling url
- use the global configuration and some magic with a bash script (https://github.com/guidone/node-red-contrib-chatbot/wiki/Global-Configuration, but I didn't check if it still works, node-red made some changes on this settings key)
- wait for the next release of node-red, it's dockerized and some parameters can be specified externally as environment variable (not specifically the bot configuration, but if someone is interested I can implement it)
