### ISSUE TITLE
Inject doesn't trigger Telegram Sender

### ISSUE THREAD

**Issue by az911** [guidone/node-red-contrib-chatbot#515]
Hi, newbie here. 

I try to use Inject node in order to trigger both manually and using time schedule a simple flow that ends with a Telegram Sender node. 
The same flow is also triggered using Telegram Receiver + Rule nodes. 
When sending from Telegram the command that triggers the Telegram Receiver + Rule nodes the flow works perfectly, but when using the Inject node the flow doesn't end with sending. 
I attached Debug nodes to every step and the Sender node receive everything it needs but still doesn't send... 
From some reason the Telegram Sender node just ignore the input it gets when it is triggered by an Inject node, so I tried mimicking the entire object as received from the Rules node, but that didn't work.

I tried testing the same with TelegramBot Sender node and it did work, however using the two together causes issues and it messes things up...

EDIT: I just found out that it also happen when the source is node-red-contrib-speedtest-updated (even without the Inject node,, it just won't send any data originating from node-red-contrib-speedtest-updated) :(

`[
    {
        "id": "d60c9ba50288021f",
        "type": "chatbot-rules",
        "z": "10e221f653f7bd16",
        "name": "",
        "rules": [
            {
                "type": "command",
                "command": "/time"
            }
        ],
        "outputs": 1,
        "x": 710,
        "y": 260,
        "wires": [
            [
                "204c0fbca3636cea"
            ]
        ]
    },
    {
        "id": "51a2b24ad9b967d9",
        "type": "chatbot-telegram-send",
        "z": "10e221f653f7bd16",
        "bot": "",
        "botProduction": "",
        "track": true,
        "passThrough": false,
        "errorOutput": false,
        "outputs": 1,
        "x": 1190,
        "y": 340,
        "wires": [
            []
        ]
    },
    {
        "id": "584e386bee4de81c",
        "type": "inject",
        "z": "10e221f653f7bd16",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payloadType": "date",
        "x": 540,
        "y": 400,
        "wires": [
            [
                "204c0fbca3636cea"
            ]
        ]
    },
    {
        "id": "204c0fbca3636cea",
        "type": "function",
        "z": "10e221f653f7bd16",
        "name": "timestamp",
        "func": "var today = new Date();\nvar date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();\nvar time = today.getHours() + \":\" + today.getMinutes() + \":\" + today.getSeconds();\nmsg.payload = date.concat(\" \", time);\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 870,
        "y": 340,
        "wires": [
            [
                "6b61c7c48cbcc627"
            ]
        ]
    },
    {
        "id": "6b61c7c48cbcc627",
        "type": "function",
        "z": "10e221f653f7bd16",
        "name": "",
        "func": "let time1 = msg.payload;\n\nmsg.payload = {\n    type : 'message',\n    chatId : 000000,\n    content : time1\n};\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1020,
        "y": 340,
        "wires": [
            [
                "51a2b24ad9b967d9"
            ]
        ]
    },
    {
        "id": "19af70986d063e64",
        "type": "chatbot-telegram-receive",
        "z": "10e221f653f7bd16",
        "bot": "",
        "botProduction": "",
        "x": 550,
        "y": 260,
        "wires": [
            [
                "d60c9ba50288021f"
            ]
        ]
    }
]`

What is wrong here? 

Thanks!

**Comment by guidone** [comment]
Is this still a problem?
