### ISSUE TITLE
Readme screenshots are broken on flows.nodered.org

### ISSUE THREAD

**Issue by sdsanders** [guidone/node-red-contrib-chatbot#52]
There appears to be an issue with the readme image paths: https://flows.nodered.org/node/node-red-contrib-chatbot

**Comment by guidone** [comment]
@sdsanders I guess it's a bug of the nodered.org repository, I've fixed some image urls with the absolute path, let's see the next update.

Meanwhile you can check here

https://www.npmjs.com/package/node-red-contrib-chatbot

the images are ok.

Thanks for the feedback
