### ISSUE TITLE
Unable to set transport or bot config in Conversation node

### ISSUE THREAD

**Issue by p4r4ll4x** [guidone/node-red-contrib-chatbot#521]
**Breaking issue** This breaks all flows that use the conversation node.

Since upgrade to Node Red 2.2.0 (official docker) i'm unable to set transport or bot config in Conversation node.
All these fields in the Conversation node are empty.
I see the problem occurred also in the past.
Running 0.19.11.

`"chatId was correctly specified but without a valid chatbot configuration"`

**Comment by crnah2o** [comment]
same here

**Comment by OidaTiftla** [comment]
@alexandrepossebom and @crnah2o can you test if the error still occurs with this fix: https://github.com/guidone/node-red-contrib-chatbot/pull/522

Instructions to test this fix are in the PR.

**Comment by goessensj** [comment]
> @goessens, @alexandrepossebom or @crnah2o can you test if the error still occurs with this fix: #522
> 
> Instructions to test this fix are in the PR.

I tested this in docker (npm install + restart of container), i still can't select transport or bot config in the dropdown lists.

**Comment by OidaTiftla** [comment]
Hmm okay, sorry. I thought it could be related.

**Comment by crnah2o** [comment]
> @goessens, @alexandrepossebom or @crnah2o can you test if the error still occurs with this fix: #522
> 
> Instructions to test this fix are in the PR.

Sorry, not at the site ATM, will attempt this weekend. Am a noob, so don't know even if I'll be able to install since using home assistant os, or however it's called, + nr addon.
