### ISSUE TITLE
Telegram bot token not encrypted

### ISSUE THREAD

**Issue by dematron** [guidone/node-red-contrib-chatbot#523]
Hello.
May be I made something wrong but when I add a new config of bot and save the configuration, I can see bot token in flow.json as a plain text. At the same time flow_cred.json also updated with new data. Is it a bug or my mistake in configuration?
nodered version - 2.1.6
chatbot version - 0.19.11

**Comment by guidone** [comment]
You're right, the token is visible even if I think the one it's actually used is in the credentials storage.
(Node-RED is able to digest averyhting is passed in flows.json)

**Comment by guidone** [comment]
Fixed in `0.19.16`
