### ISSUE TITLE
v0.19.12 | contextStore.keys is not a function

### ISSUE THREAD

**Issue by Iciir** [guidone/node-red-contrib-chatbot#527]
I still can not run RedBot with Node-RED 2.2.2

![Screenshot_261](https://user-images.githubusercontent.com/93911948/156417943-8c0a954e-8bd4-417a-85ae-3d55ac91954e.png)

**Comment by JanickGers85** [comment]
Same here, plus I have all dropdown on conversation node empty with no item to select.
First one should expose transport options (telegram, ecc...).
The following two the bot configuration (only one in my case).

![20220302_234132](https://user-images.githubusercontent.com/21289907/156462274-5c0cd214-df3f-4334-883e-4387a1783873.png)

My configuration node is correct

![20220302_234437](https://user-images.githubusercontent.com/21289907/156462446-8b41c140-08c4-45e2-ae6e-90d1a0f11a48.png)

Reverting to chatbot v0.19.11 and NR v2.1.6, hoping for a fix :)

**Comment by dajappie** [comment]
Same issue, chatbot no longer receiving or sending after upgrade to NR 2.2.2-16 and chatbot 0.19.12

**Comment by crnah2o** [comment]
could it be we need 0.19.13 which it says here is the latest version? unfortunately it isn't available to me in the pallette.

**Comment by Supergiovane** [comment]
Me too. It doesn't work anymore and throws **"TypeError: contextStore.get is not a function"** error.

**Comment by alasso** [comment]
Same probleme to me. If there is no solution, can you suggest me a library to replace chatbot? 
Thanks!

**Comment by Supergiovane** [comment]
Alasso
Just revert to previous version or wait for the fix. This library is so good!

**Comment by alasso** [comment]
Hi, I just updated to v0.9.13 using command line and worked! Thanks a lot!

**Comment by dajappie** [comment]
> Hi, I just updated to v0.9.13 using command line and worked! Thanks a lot!

Same here, all good with 0.19.13
