### ISSUE TITLE
Can't get slack to work

### ISSUE THREAD

**Issue by lcx** [guidone/node-red-contrib-chatbot#528]
I followed the instructions on slack setup but still got the `Your URL didn't respond with the value of the challenge parameter.` error message mentioned a while back. 
Digging in to this issue a bit, I have found this post: https://stackoverflow.com/questions/70391828/slack-app-error-new-request-url-your-url-didnt-respond-with-the-value-of-the withe the same issue where upgrading slack/events-api to 3.0.1 fixed the issue. 
As far as I can see it's using `events-api-2.3.4` 

```json
bash-5.0$ cat package-lock.json |grep slack
        "@slack/events-api": {
            "resolved": "https://registry.npmjs.org/@slack/events-api/-/events-api-2.3.4.tgz",
        "@slack/logger": {
            "resolved": "https://registry.npmjs.org/@slack/logger/-/logger-2.0.0.tgz",
        "@slack/types": {
            "resolved": "https://registry.npmjs.org/@slack/types/-/types-1.10.0.tgz",
        "@slack/web-api": {
            "resolved": "https://registry.npmjs.org/@slack/web-api/-/web-api-5.15.0.tgz",
                "@slack/logger": ">=1.0.0 <3.0.0",
                "@slack/types": "^1.7.0",
                "@slack/events-api": "^2.3.3",
                "@slack/web-api": "^5.3.0",
```

is something just wrong on my install or is this really an issue which would be solved with the new version? Not into node stuff and have no idea how to temp. update it to verify if it would work.

**Comment by guidone** [comment]
Working on a new version which supports web sockets, few days and it's ready
