### ISSUE TITLE
Persistent Menu - Facebook

### ISSUE THREAD

**Issue by ram1505** [guidone/node-red-contrib-chatbot#53]
Hi,
How can I get the facebook [persistent menu](https://developers.facebook.com/docs/messenger-platform/thread-settings/persistent-menu) working with chatbot?

**Comment by guidone** [comment]
@ram1505 At the moment is not possible, but I'm working on it

**Comment by guidone** [comment]
@ram1505 I have a beta for this, would you like to try?

    npm install node-red-contrib-chatbot@0.6.21-beta-1

Thanks!

**Comment by ram1505** [comment]
Sure. Let me try it out and will feedback to you. Thanks.

**Comment by ram1505** [comment]
For this to work, I need [this](https://github.com/guidone/node-red-contrib-chatbot/issues/54) to be resolved.

**Comment by ram1505** [comment]
I tried this version. I am unable to get it show up on the Messenger. Not sure how to connect this in Node-RED. Should I connect this directly between the Facebook Receiver & Sender or should I connect it to a Text?

**Comment by ram1505** [comment]
I'm getting some errors like this when I try the menu with messenger:

`node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Unable to prepare unknown message type
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error parsing error payload from Facebook.
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Unable to prepare unknown message type
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error parsing error payload from Facebook.
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Unable to prepare unknown message type
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error parsing error payload from Facebook.
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Unable to prepare unknown message type
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error parsing error payload from Facebook.
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): Unable to prepare unknown message type
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error parsing error payload from Facebook.
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Unable to prepare unknown message type
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error parsing error payload from Facebook.
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Unable to prepare unknown message type
(node:1801) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error parsing error payload from Facebook.`

**Comment by guidone** [comment]
@ram1505 should be connected to a Facebook Sender node

**Comment by guidone** [comment]
@ram1505 ok I've fixed some bugs

    npm install node-red-contrib-chatbot@0.6.21-beta-2

**Comment by ram1505** [comment]
Awesome! Works like a charm!

**Comment by ram1505** [comment]
One issue is that, the persistent menu seems super persistant that I can no longer remove it from my bot even after deleting the chatbot menu node. How can I remove the menu items from my facebook messenger now?

**Comment by guidone** [comment]
@ram1505 yes menu in stored on Facebook server, have you tried with a menu node with no elements inside?

**Comment by ram1505** [comment]
I actually used the Facebook's CURL method with empty call to action and it removed the menu.
