### ISSUE TITLE
Problem with Overload

### ISSUE THREAD

**Issue by Iciir** [guidone/node-red-contrib-chatbot#537]
Hello!  I hope to find someone with more knowledge than me who might give me an idea on how to fix this.

I have an extremely complex Administration Bot that I used in about 50 **Telegram** groups, built in Node-RED using RedBot.

It's running very well usually.  I went through many problems, I fixed everything, but I came to a problem I can't fix apparently.

### [ Problem ]
If a Group uses userbots, to add dozens of members in a minute, like.. 3 new member per second, that kind of thing, everything becomes exponentially overwhelmed and my bots' response time increases from ~300ms to ~5-10-20 minutes.

Also if many photos are forwarded, like 100 photos, in a group, it also doesn't respond for about ~1 minute but I don't think that can be solved.

### [ What is not a solution ]
I will not set privacy mode to ON.  Some type of (normal text) messages are analysed. For example messages starting with "!" instead of "/".

### [ What is it doing when a new member enters? ]
If the message is of type "new-user", it sends a HTTP request to delete the "User has joined" message from the chat, after 5 seconds. And it stops, it does not continue with that message in the big flows.

### [ Settings ]
RedBot is set to use "Memory" as context storage.

### [ Conclusion ]
Maybe there is something I can change in Node-RED settings that I can't think about.  I use the default settings.  Any ideas?

**Comment by Iciir** [comment]
I optimized a lot of things, such as never using the HDD for storage (except for backups every hour).

However, I noticed that this lag usually happens when a person forwards a video in multiple groups.

Is there a way to stop RedBot from processing media?

**Comment by Iciir** [comment]
Well let's try to figure it out:

This administration bot is present in ~30 groups.

A person forwards a set of 3 videos, in 10 groups.

Node-RED has to receive and process
30 Buffers

_meanwhile_  people are still typing normal messages, each piling up while the 30 buffers are processed.

Someone types a command, like "`/ban Disrespectful to the other members.`"

_meanwhile_  Node-RED, is processing the 30 Buffers and a lot of other messages that have been piling up.

The banned person sees the "/ban" command and laughs that it's not working.  Admins are considering to switching away from my bots.

About 30 seconds later the person is finally banned because Node-RED got to that request.

In this case, a logical solution would be to separate the **processing of media** (which I actually do, with Teachable Machine, to detect and block NSFW for example) - from the **processing of non-media** messages.

So I would run 2 Node-REDs, one for non-media and one for media (which doesn't matter if it lags, I decided).

But the non-media one is not possible, because I can't stop that.

**Comment by guidone** [comment]
Ok, what if I can introduce a method in the extension node to unregister a message type.

```javascript
node.chat.unregisterMessageType('video');
node.chat.unregisterMessageType('document');
node.chat.unregisterMessageType('audio');
```

In that case the receiver will just ignore these message types

**Comment by Iciir** [comment]
Yes but please make it a checkbox option, because some bots would need those things.

**Comment by guidone** [comment]
Ok, let me think about it

**Comment by Iciir** [comment]
And also, I would suggest (which I edited for my case):

In
`/node_modules/node-red-contrib-chatbot/lib/platforms/telegram.js`

```
Telegram.in(function(message) {
  const connector = this.getOptions().connector;
  const botMsg = message.originalMessage;
  const chatServer = this;
  return new Promise((resolve, reject) => {
    let type = null;
    let fileId = null;
    let duration = null;
    // download one of these binary types
    if (botMsg.photo != null) {
      type = 'photo';
      fileId = _(botMsg.photo).last().file_id;
    } else if (botMsg.video != null) {
      type = 'video';
      fileId = botMsg.video.file_id;
    } else if (botMsg.voice != null) {
      type = 'audio';
      fileId = botMsg.voice.file_id;
      duration = botMsg.voice.duration;
    } else if (botMsg.document != null) {
      type = 'document';
      fileId = botMsg.document.file_id;
    } else if (botMsg.video_note != null) {
      type = 'video_note';
      fileId = botMsg.video_note.file_id;
      duration = botMsg.video_note.duration;
    }
    // if not one of these pass thru
    if (type != null) {
      message.payload.type = type;
      connector.getFileLink(fileId)
        .then(path => chatServer.downloadFile(path))
        .then(
          buffer => {
            message.payload.content = buffer;
            message.payload.caption = botMsg.caption;
            message.payload.duration = duration;
            resolve(message);
          },
          () => { //reject('Error downloading photo'),
            message.payload.content = '#BIG';
            message.payload.caption = botMsg.caption;
            resolve(message);
            },
        );
    } else {
      resolve(message);
    }
  });
});
```

Changing the `reject('Error downloading photo')` to just drop the buffer.

Because that's a way to bypass any checks on the message.

Of course `"#BIG"` changed with something like `null` rather.

**Comment by guidone** [comment]
done in `0.19.18`

**Comment by Iciir** [comment]
![image](https://user-images.githubusercontent.com/93911948/165995765-b252ca2b-348b-41ba-ac39-6e15c39e651c.png)
Wonderful!

Did you do the `reject('Error downloading photo')` part as well?

**Comment by guidone** [comment]
Yes, did you try it?

**Comment by Iciir** [comment]
Yes, I noticed now it logs the error but continues without the buffer which is PERFECT.  :D 

The error can be commented out, no problem.
