### ISSUE TITLE
Slack Websocket API - Warning message in Slack when actioning Buttons

### ISSUE THREAD

**Issue by onestix** [guidone/node-red-contrib-chatbot#546]
Hi @guidone - I hope this finds you well.

I wanted to thank you again for having introduced the [Slack Websocket API](https://github.com/guidone/node-red-contrib-chatbot/issues/471). It's been working really great for me so far.

There is however one tiny challenge I have and that is when implementing buttons, specifically when I click on them. I do successfully receive a "response" message in Node-red, but Slack however shows me a Warning message in the Chat UI:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/84330001/173046875-13d50664-f8ec-471b-8d03-e4e92f87bf1f.png">

I managed to find a ticket directly with Slack where this issue is also described:

https://github.com/slackapi/node-slack-sdk/issues/869

Looking at the provided solution, I wonder if there is something that we are missing on our end, ie. confirming message receipt with Slack, once a button response has been received by Redbot? Or am I just missing a configuration on my setup?

My Node-red configuration looks the following:

1- Message is sent using a block:

![image](https://user-images.githubusercontent.com/84330001/173047379-34fcb8e8-d2a9-4529-b195-d7ee85a18fc0.png)

2- Message (response, including blockid) is well received:

`{"type":"response","chatId":"xx","userId":"xx","ts":null,"transport":"slack","inbound":true,"content":{"my_blockid":"my_value"}}
`
![image](https://user-images.githubusercontent.com/84330001/173047562-433b0ac8-2645-4fb1-af8c-3110706bb73d.png)

Thanks for your help and please let me know if you need further details.

**Comment by guidone** [comment]
FIxed in `0.19.20`
