### ISSUE TITLE
Slack - Blocks Node - Notifications show as "This content can't be displayed."

### ISSUE THREAD

**Issue by onestix** [guidone/node-red-contrib-chatbot#561]
Hi @guidone - I hope all is well.

I am currently having some challenges with notifications that I receive on Slack. All of my messages sent by Slack are currently returning with a "This content can't be displayed." message:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/84330001/185156866-738001c2-7479-4b56-8a07-b38175d7f18d.png">

I am specifically using the Blocks node, where I have defined a custom payload, example below:

```
{
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": " "
			}
		},
		{
			"type": "header",
			"text": {
				"type": "plain_text",
				"text": "This is a test message"
			}
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "This is a test message. This is a test message. This is a test message. This is a test message"
			},
			"accessory": {
				"type": "image",
				"image_url": "https://cdn-icons-png.flaticon.com/512/546/546404.png",
				"alt_text": "x"
			}
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": " "
			}
		}
	]
}
```

Yes, I do not have the cleanest Block, but I am doing so for design/display purposes in Slack.

Now, I have read about this on the Slack github pages as well as the Slack documentation page and it seems that it is possible to add a fallback "text" value in your payload to exactly tackle this issue.

Slack documentation: 

[See here](https://api.slack.com/messaging/composing/layouts#add_blocks_array) - Reads: `When you're using blocks in your message payload, the top-level text field becomes a fallback message displayed in notifications. Blocks should define everything else about the desired visible message.` The sample payload looks the following:

```
{
  "channel": "C1H9RESGL",
  "text": "New Paid Time Off request from Fred Enriquez",
  "blocks": [
		{
			"type": "header",
			"text": {
				"type": "plain_text",
				"text": "New request"
			}
		},
		{
			"type": "section",
			"fields": [
				{
					"type": "mrkdwn",
					"text": "*Type:*\nPaid Time Off"
				},
				{
					"type": "mrkdwn",
					"text": "*Created by:*\n<example.com|Fred Enriquez>"
				}
			]
		},
		{
			"type": "section",
			"fields": [
				{
					"type": "mrkdwn",
					"text": "*When:*\nAug 10 - Aug 13"
				}
			]
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "<https://example.com|View request>"
			}
		}
	]
}
```

Take note of the `"text": "New Paid Time Off request from Fred Enriquez"` entry at the top. This in theory acts as the fallback for notifications.

Now, I wonder if there is a way for me to configure this top-level text entry when configuring my Blocks node. I did try adding the `"text":` entry to my payload, but this did not work. I assume this must be configured as part of the "chat.postMessage" call? Here are some further details I found specifically on this:  https://api.slack.com/methods/chat.postMessage#blocks_and_attachments

<img width="958" alt="image" src="https://user-images.githubusercontent.com/84330001/185155604-88651eb4-0db4-4ab8-bbff-8e3a3dda8e11.png">

Perhaps we could use the Params node to manipulate the call using the value we would like to add or ideally have a field directly on the Blocks node allowing us to configure the `text`?

Thanks for sharing your thoughts and your continued commitment to this project.

Cheers

Similar examples have been also raised here:

https://github.com/sct/overseerr/issues/2408
https://github.com/statping/statping/issues/933

**Comment by guidone** [comment]
Back from vacation, I'll give a look

**Comment by guidone** [comment]
The code ignores the `text` key, I'll fix that

**Comment by onestix** [comment]
Thanks you!

**Comment by onestix** [comment]
Thank you so much! cheers
