### ISSUE TITLE
didn't receive any incoming message for Facebook

### ISSUE THREAD

**Issue by syshen** [guidone/node-red-contrib-chatbot#57]
Hi,
 
I set up a Facebook in node, a Facebook out node, a function node, and a debug node to print out the payload from "Facebook in". 

Facebook webhook verification is working fine. It passes the verification. 

But I cannot get any message from "Facebook in" (try to debug by connecting it to a debug node.)

Then I insert a "HTTP input" node to debug, it shows Facebook actually sends messages to the webhook URL. But why the "Facebook in" node didn't handle it?

**Comment by syshen** [comment]
Just figured out the issue. 

I was embedding NodeRed in an express app. But I didn't include body-parser as middleware to parse the incoming json message. And Facebook-Receiver node just use req.body to parse the chat message. And req.body is underfined without body-parser.

**Comment by guidone** [comment]
@syshen thanks for the feedback, I'll update the docs to include these tips
