### ISSUE TITLE
SQLite context provider: missing parameter "chatbotId"

### ISSUE THREAD

**Issue by OidaTiftla** [guidone/node-red-contrib-chatbot#578]
Hi,

first of all, thanks for that great library. I'm sorry that I have to open an issue.

I updated the library from 0.19.3 to 1.1.0 and after that I had some errors.

As far as I could figure it out, it comes from the `chatbot-context-store` node. It is configured to use SQLite. With SQLite it produces this error:

```
SQLite context provider: missing parameter "chatbotId"
```

Along with some others, that seem to be consequences of the first error:

```
Missing configuration in Telegram Receiver

Invalid Telegram Bot configuration

chatId was correctly specified but without a valid chatbot configuration
```

When I change the `chatbot-context-store` to use memory as storage, all errors are gone. But there is the warning that I will loose context on restarting.

What I have also tried so far:
- remove the *.sqlite file, so that it can be recreated (maybe the new version has a new schema), but the file never gets created again
- I tried to find the source code location where the file gets created and see if there are any prerequisites I missed, but my knowledge was not sufficient to find the source code line.
- I also tried to find the location where the SQLite missing parameter error comes from, but my knowledge wasn't sufficient for that either.

That's why I ask for help in this issue. May someone can help me and maybe give me a clue, which file I have to delete or what I have to configure to get it working again.

Thanks a lot in advance.

Best regards.

---

**Console output:**

```
25 Nov 10:19:59 - [info] Telegram Bot E.D.I.T.H. will be launched, environment is development
25 Nov 10:19:59 - [error] [chatbot-telegram-node:9f29138dd06ad670] SQLite context provider: missing parameter "chatbotId"
registering node e48ab523.8067d8
registering node f4a49a46.f1948
25 Nov 10:19:59 - [warn] [chatbot-telegram-send:fa7b676449c0d370] Missing configuration in Telegram Receiver
25 Nov 10:19:59 - [warn] [chatbot-telegram-send:fbff0f1cdbb12c55] Missing configuration in Telegram Receiver
25 Nov 10:19:59 - [warn] [chatbot-telegram-receive:8d9e422360fb0d75] Missing configuration in Telegram Receiver
25 Nov 10:19:59 - [info] Started flows
25 Nov 10:20:00 - [error] [chatbot-telegram-menu:ce7063a87ac296d3] Invalid Telegram Bot configuration
25 Nov 10:20:00 - [error] [chatbot-conversation:Logs-Group] chatId was correctly specified but without a valid chatbot configuration
25 Nov 10:20:01 - [error] [chatbot-conversation:Logs-Group] chatId was correctly specified but without a valid chatbot configuration
25 Nov 10:20:02 - [error] [chatbot-conversation:Logs-Group] chatId was correctly specified but without a valid chatbot configuration
25 Nov 10:20:06 - [error] [chatbot-conversation:Logs-Group] chatId was correctly specified but without a valid chatbot configuration
```

**Comment by guidone** [comment]
Trying to reproduce without asking to handover your flow: are you using the SQLite context provider without Mission Control (check the "use Mission Control" flag in the chatbot configuration)

**Comment by OidaTiftla** [comment]
`Use Mission Control` is not checked.

**Comment by guidone** [comment]
Ok, it's a problem in the configuration.

Just add in the configuration of the context store the key `chatbotId` with any value

```json
{
  "dbPath": "/data/store.sqlite",
  "chatbotId": "my-bot"
}
```
I'll improve the docs and the error message.

Thanks for the feedback (always apreciated)

**Comment by guidone** [comment]
Fixed in `1.1.1`

**Comment by OidaTiftla** [comment]
Yes thanks, now it's fixed. 👍

**Comment by OidaTiftla** [comment]
Thanks for the really fast fix 🚀
