### ISSUE TITLE
regex entity available?

### ISSUE THREAD

**Issue by altieres** [guidone/node-red-contrib-chatbot#589]
Thanks for this very good library.

Is it possible to create an arbitrary (regex) entity? how?
My bot must be able to process "How can I go to %street_name%". But street_name didn't came in the "variables" object.

Thanks for your time, any direction is appreciated.

**Comment by guidone** [comment]
I need to check, I'm using NLP.js library (a rather old version), need to verify if this is possible in recent version.

**Comment by altieres** [comment]
Ok, thank you!

Maybe this link will help you understand what I was thinking:
https://github.com/axa-group/nlp.js/blob/master/docs/v4/ner-manager.md#regex-entities

**Comment by guidone** [comment]
done in `1.2.1`
