### ISSUE TITLE
Fancy keyboard

### ISSUE THREAD

**Issue by gerardovf** [guidone/node-red-contrib-chatbot#60]
Hi guidone,
In python I can create this nice keyboards:

**HIGH_BRIGHTNESS_SYMBOL = "\U0001F506" # b'\xF0\x9F\x94\x86'
LOW_BRIGHTNESS_SYMBOL = "\U0001F505" # b'\xF0\x9F\x94\x85'
UPWARDS_BLACK_ARROW = "\U00002B06" # b'\xE2\xAC\x86'
DOWNWARDS_BLACK_ARROW = "\U00002B07" # b'\xE2\xAC\x87'
DOOR = "\U0001f6aa" # b'\xF0\x9F\x9A\xAA'
VERTICAL_TRAFFIC_LIGHT = "\U0001F6A6" # b'\xF0\x9F\x9A\xA6'
CAMERA = "\U0001F4F7" # b'\xF0\x9F\x93\xB7'**

**def setNormalKeyboard(cid):
    markup = types.ReplyKeyboardMarkup()
    itembtn11 = types.KeyboardButton(UPWARDS_BLACK_ARROW+"\nBlind #1")
    itembtn12 = types.KeyboardButton(UPWARDS_BLACK_ARROW+"\nBlind #2")
    itembtn13 = types.KeyboardButton(UPWARDS_BLACK_ARROW+"\nBlind #3")
    itembtn14 = types.KeyboardButton(UPWARDS_BLACK_ARROW+"\nBlind #4")
    itembtn15 = types.KeyboardButton(HIGH_BRIGHTNESS_SYMBOL+"\nON")
    markup.row(itembtn11, itembtn12, itembtn13, itembtn14, itembtn15)
    itembtn21 = types.KeyboardButton(DOWNWARDS_BLACK_ARROW+"\nBlind #1")
    itembtn22 = types.KeyboardButton(DOWNWARDS_BLACK_ARROW+"\nBlind #2")
    itembtn23 = types.KeyboardButton(DOWNWARDS_BLACK_ARROW+"\nBlind #3")
    itembtn24 = types.KeyboardButton(DOWNWARDS_BLACK_ARROW+"\nBlind #4")
    itembtn25 = types.KeyboardButton(LOW_BRIGHTNESS_SYMBOL+"\nOFF")
    markup.row(itembtn21, itembtn22, itembtn23, itembtn24, itembtn25)
    itembtn31 = types.KeyboardButton(CAMERA+"#1")
    itembtn32 = types.KeyboardButton(CAMERA+"#2")
    itembtn33 = types.KeyboardButton(DOOR+"\nSmall Door1")
    itembtn34 = types.KeyboardButton(VERTICAL_TRAFFIC_LIGHT+"\nMORE")
    markup.row(itembtn31, itembtn32, itembtn33, itembtn34)**

    strMessage = "Choose one action:"
    try:
        bot.send_message(chat_id=cid, text=strMessage, reply_markup=markup)
    except:
        pass

Can I do the same with your Chatbot?
![screenshot_20170326-165747](https://cloud.githubusercontent.com/assets/21976915/24332534/50c86746-1248-11e7-9eff-27a6086f95f9.jpg)

**Comment by guidone** [comment]
@gerardovf yes, I guess the node-red ui will eat all your special chars but you can prepare the payload in an upstream function node, something like

```
msg.payload = {
  message: 'The message with the buttons',
  buttons: [
    {
      value: 'text 1',
      label: 'label of the button 1',
      answer: 'this is the answer',
      alert: true,
      newLine: true
    },
    {
      value: 'text 2',
      label: 'another label',
      answer: 'this is the answer 2',
      alert: false
    }
  ]
}
return msg;
```

**Comment by gerardovf** [comment]
@guidone You were right!! Now only the 'newLine' is still not working... (I wanted to show a 2x2 buttons keyboard)

I used this page to get the emoji conversion: http://www.fileformat.info/info/unicode/char/search.htm

Then in the upstream function node I inserted:

_console.log(msg);
var chat = msg.chat();
var cloned = RED.util.cloneMessage(msg);
cloned.payload = {
  type: "buttons",
  content: 'The message with the buttons',
  messageId: null,
  chatId: chat.get('chatId'),
  buttons: [
    {
      value: '\uD83D\uDD06\nON1',
      label: 'label of the button 1',
      answer: 'this is the answer',
      alert: true,
      newLine: false
    },
    {
      value: '\u2B06\nON2',
      label: 'another label',
      answer: 'this is the answer 2',
      alert: false,
      newLine: true
    },
    {
      value: '\uD83D\uDD05\nOFF1',
      label: 'label of the button 3',
      answer: 'this is the answer 3',
      alert: true,
      newLine: false
    },
    {
      value: '\u2B07\nOFF2',
      label: 'another label 2',
      answer: 'this is the answer 4',
      alert: false,
      newLine: true
    }
  ]
}
return cloned;_

![fancykbd](https://cloud.githubusercontent.com/assets/21976915/24414343/74a1a992-13de-11e7-9da8-9d0a15690a8d.png)

**Comment by gerardovf** [comment]
@guidone I also checked that 'newLine' is working with "inline-buttons"

_console.log(msg);
var chat = msg.chat();
var cloned = RED.util.cloneMessage(msg);
cloned.payload = {
  type: "inline-buttons",
  content: 'The message with the buttons',
  messageId: null,
  chatId: chat.get('chatId'),
  buttons: [
    {
      value: '\uD83D\uDD06\nON1',
      label: '\uD83D\uDD06\nON1',
      answer: 'this is the answer',
      newLine: false
    },
    {
      value: '\u2B06\nON2',
      label: '\u2B06\nON2',
      answer: 'this is the answer 2',
      newLine: true
    },
    {
      value: '\uD83D\uDD05\nOFF1',
      label: '\uD83D\uDD05\nOFF1',
      answer: 'this is the answer 3',
      newLine: false
    },
    {
      value: '\u2B07\nOFF2',
      label: '\u2B07\nOFF2',
      answer: 'this is the answer 4',
      newLine: true
    }
  ]
}
return cloned;_

![fancybuttons](https://cloud.githubusercontent.com/assets/21976915/24415372/9671f240-13e1-11e7-82ba-0512221ac8ff.png)
