### ISSUE TITLE
no output from Facebook Receiver

### ISSUE THREAD

**Issue by dalleraro** [guidone/node-red-contrib-chatbot#61]
Hi,
I'm using an instance of the Facebook Receiver on IBM Bluemix,
I configured the messenger webhook to call it and it registered the configuration with no problem.
The issue is that when I send a message through messanger nothing is coming out from the node, I can see it replying to the http post request on the console but there is no output.
Do you have any idea on what could cause the problem?
Thanks!

**Comment by guidone** [comment]
Hi @dalleraro, is this https://github.com/guidone/node-red-contrib-chatbot/issues/57 of any help?

**Comment by dalleraro** [comment]
Thanks for the quick reply,
I think that in bluemix there is a bodyparser middleware, but I'm not complitely sure. I'm new to that platform and it doesn't allow a lot of costumization. Anyway if I use an http node to capture the request from facebook I can see it fine with the req.body.

**Comment by guidone** [comment]
@dalleraro is it working now?

**Comment by rola93** [comment]
I have the same issue, but I'm not running in Bluemix. I'm running node-red locally, and using [ngork](https://ngrok.com/) to expose the server. As far as I know, I set up everything well on Facebook, connected Facebook Receiver to a debug node, but no output is shown. any idea? how can I use an http node to capture the request as mentioned by @dalleraro ?

Thanks!

**Comment by ram1505** [comment]
Are you using a static landing page? If so, try removing it and make node red editor as landing page. I had same issue on both Bluemix as well as Heroku.

**Comment by rola93** [comment]
Solved it! I had to subscribe my app to events from the fan page. I thought it was done when token was generated, but I had to subscribe it in webhooks too.
