### ISSUE TITLE
Is it possible to response multiple messages at once? 

### ISSUE THREAD

**Issue by syshen** [guidone/node-red-contrib-chatbot#62]
Hi Guidone

I am wondering is it possible to response with multiple messages at once when the bot gets a message from the user? 
I checked it might be not possible since the later message will replace the previous one since the message is stored in the same msg.payload.content. But is there any other workaround way to do the same behavior? Or you have any plan to add such feature in the future (allow the bot creator to add multiple messages in the text)?

**Comment by guidone** [comment]
@syshen yes, you can split the flow

![Uploading Schermata 2017-03-28 alle 13.19.45.png…]()

you may want to insert a delay node between the message that is supposed to come after the first and the output node, otherwise the order will be unpredictable

**Comment by gabbiano83** [comment]
Hi,
i use this topic to ask similar question, is it possible to send a single message to multiple users?
E.g For telegram:
`var originalRequester = msg.originalMessage
msg.administratorslist = msg.payload
flow.set('originalMessage',originalRequester);

for (var i in msg.payload){
 var cloned = RED.util.cloneMessage(msg);
cloned.payload = {};
cloned.payload.type = "message"
cloned.payload.messageId = msg.originalMessage.messageId
cloned.payload.content =  "L'utente " + msg.originalMessage.from.id + ", " +  "ha tentato un accesso."
cloned.payload.chatId = msg.payload[i]._id
cloned.payload.inbound = false
cloned.i = i
return cloned;   
}
msg.payload = {}


return null;`

using this, only first administrator is currently notified

**Comment by guidone** [comment]
@gabbiano83 yes you can do it without coding, just split the message node output to as many conversation node for each user who is supposed to receive the message and connect them to a telegram output node

<img width="706" alt="schermata 2017-04-03 alle 10 44 19" src="https://cloud.githubusercontent.com/assets/502519/24601788/8b900718-185a-11e7-821f-462767528b8a.png">

For each conversation node you'll need to setup the correct chatId
