### ISSUE TITLE
"Topic"  TAG is not processed  into block. 

### ISSUE THREAD

**Issue by remybeaudenon** [guidone/node-red-contrib-chatbot#63]
in the following sample the script process successfully  {topic=sorry}  on replying .
unfortunately it does process {topic=random}  on "It's OK, I'll forgive you!"  replying.  
Is somebody can help ? 
Regards. 

! version = 2.0
+ i hate you
- You're really mean! I'm not talking again until you apologize.{topic=sorry}

> topic sorry

  // This will match if the word "sorry" exists ANYWHERE in their message
  + [*] sorry [*]
  - It's OK, I'll forgive you!{topic=random}

  + *
  - Nope, not until you apologize.
  - Say you're sorry!
  - Apologize!

< topic

**Comment by remybeaudenon** [comment]
add Telegram

**Comment by guidone** [comment]
@remybeaudenon I don't understand what is not working as expected, if I'm not wrong this is an example taken from RiveScript, this

- It's OK, I'll forgive you!{topic=random}

will output the string "It's OK, I'll forgive you!" and switch the topic to random, this is how is supposed to work
