### ISSUE TITLE
Parse Location

### ISSUE THREAD

**Issue by ram1505** [guidone/node-red-contrib-chatbot#64]
Hi,
This could be a lame but how do I change the parsed payload location from 

`{latitude: xxxx, longitude: yyyy}`

to

`{lat:xxx, lon:yyy}`

**Comment by guidone** [comment]
Just use a function blog

```
msg.payload = {
  lat: msg.payload.latitude,
  lon: msg.payload.longitude
};
return msg;
```

**Comment by ram1505** [comment]
Thanks

**Comment by ram1505** [comment]
Can you please share how you parsed out the latitude and longitude via Google places in this [example](https://github.com/guidone/node-red-contrib-chatbot#send-a-location)?
