### ISSUE TITLE
Facebook Menu

### ISSUE THREAD

**Issue by webfrank** [guidone/node-red-contrib-chatbot#65]
Hi, I'm trying to setup a Messenger menu but when I send back to Facebook the output of the block I got this error:

(#105) Number of call to actions exceeds the maximum allowed number

This is the debug output after the node:

11/4/2017, 16:50:28node: 2ea50287.0cd00e
msg : Object
object
payload: object
type: "persistent-menu"
chatId: "1702515586442155"
messageId: "mid.$cAAXuokGHoY1hjsPbAVbXX8SqR5aN"
items: array[6]
0: object
type: "postback"
title: "News"
payload: "News"
1: object
2: object
3: object
4: object
5: object
originalMessage: object
transport: "facebook"
chat: object
id: "1702515586442155"
_msgid: "587da288.c756ec"

**Comment by guidone** [comment]
I think the problem is here, items are limited to 5, I'll add into the node validation

![schermata 2017-05-03 alle 10 00 59](https://cloud.githubusercontent.com/assets/502519/25652245/8b07ec26-2fe7-11e7-8d39-2ba45058d579.png)
