### ISSUE TITLE
no nodes on node-red after installation 

### ISSUE THREAD

**Issue by vincenzo85** [guidone/node-red-contrib-chatbot#67]
root@v9069:~/.node-red# npm install node-red-contrib-chatbot
/root/.node-red
`-- node-red-contrib-chatbot@0.6.21
  +-- @slack/client@3.9.0
  | +-- async@1.5.2
  | +-- bluebird@3.5.0
  | +-- eventemitter3@1.2.0
  | +-- https-proxy-agent@1.0.0
  | | `-- agent-base@2.0.1
  | |   `-- semver@5.0.3
  | +-- inherits@2.0.3
  | +-- lodash@4.17.4
  | +-- pkginfo@0.4.0
  | +-- retry@0.9.0
  | +-- url-join@0.0.1
  | +-- winston@2.3.1
  | | +-- async@1.0.0
  | | +-- colors@1.0.3
  | | +-- cycle@1.0.3
  | | +-- eyes@0.1.8
  | | `-- stack-trace@0.0.9
  | `-- ws@1.1.4
  |   +-- options@0.0.6
  |   `-- ultron@1.0.2
  +-- apiai@3.0.3
  +-- cli-color@1.2.0
  | +-- ansi-regex@2.1.1
  | +-- d@1.0.0
  | +-- es5-ext@0.10.15
  | | `-- es6-symbol@3.1.1
  | +-- es6-iterator@2.0.1
  | +-- memoizee@0.4.4
  | | +-- es6-weak-map@2.0.2
  | | +-- event-emitter@0.3.5
  | | +-- is-promise@2.1.0
  | | +-- lru-queue@0.1.0
  | | `-- next-tick@1.0.0
  | `-- timers-ext@0.1.2
  +-- compromise@7.0.28
  +-- cookie-parser@1.4.3
  | +-- cookie@0.3.1
  | `-- cookie-signature@1.0.6
  +-- fast-levenshtein@1.1.4
  +-- languagedetect@1.1.1
  +-- moment@2.18.1
  +-- nlp_compromise@6.5.3
  +-- node-emoji@1.5.1
  | `-- string.prototype.codepointat@0.2.0
  +-- node-telegram-bot-api@0.24.0
  | +-- bl@1.2.0
  | | `-- readable-stream@2.2.9
  | |   +-- buffer-shims@1.0.0
  | |   +-- core-util-is@1.0.2
  | |   +-- isarray@1.0.0
  | |   +-- process-nextick-args@1.0.7
  | |   `-- string_decoder@1.0.0
  | +-- debug@2.6.4
  | | `-- ms@0.7.3
  | +-- file-type@3.9.0
  | +-- mime@1.3.4
  | +-- pump@1.0.2
  | | +-- end-of-stream@1.4.0
  | | `-- once@1.4.0
  | |   `-- wrappy@1.0.2
  | `-- request-promise@2.0.1
  |   `-- bluebird@2.11.0
  +-- prettyjson@1.2.1
  | +-- colors@1.1.2
  | `-- minimist@1.2.0
  +-- qr-image@3.2.0
  +-- request@2.81.0
  | +-- aws-sign2@0.6.0
  | +-- aws4@1.6.0
  | +-- caseless@0.12.0
  | +-- combined-stream@1.0.5
  | | `-- delayed-stream@1.0.0
  | +-- extend@3.0.0
  | +-- forever-agent@0.6.1
  | +-- form-data@2.1.4
  | | `-- asynckit@0.4.0
  | +-- har-validator@4.2.1
  | | +-- ajv@4.11.7
  | | | +-- co@4.6.0
  | | | `-- json-stable-stringify@1.0.1
  | | |   `-- jsonify@0.0.0
  | | `-- har-schema@1.0.5
  | +-- hawk@3.1.3
  | | +-- boom@2.10.1
  | | +-- cryptiles@2.0.5
  | | +-- hoek@2.16.3
  | | `-- sntp@1.0.9
  | +-- http-signature@1.1.1
  | | +-- assert-plus@0.2.0
  | | +-- jsprim@1.4.0
  | | | +-- assert-plus@1.0.0
  | | | +-- extsprintf@1.0.2
  | | | +-- json-schema@0.2.3
  | | | `-- verror@1.3.6
  | | `-- sshpk@1.13.0
  | |   +-- asn1@0.2.3
  | |   +-- assert-plus@1.0.0
  | |   +-- bcrypt-pbkdf@1.0.1
  | |   +-- dashdash@1.14.1
  | |   | `-- assert-plus@1.0.0
  | |   +-- ecc-jsbn@0.1.1
  | |   +-- getpass@0.1.6
  | |   | `-- assert-plus@1.0.0
  | |   +-- jodid25519@1.0.2
  | |   +-- jsbn@0.1.1
  | |   `-- tweetnacl@0.14.5
  | +-- is-typedarray@1.0.0
  | +-- isstream@0.1.2
  | +-- json-stringify-safe@5.0.1
  | +-- mime-types@2.1.15
  | | `-- mime-db@1.27.0
  | +-- oauth-sign@0.8.2
  | +-- performance-now@0.2.0
  | +-- qs@6.4.0
  | +-- safe-buffer@5.0.1
  | +-- stringstream@0.0.5
  | +-- tough-cookie@2.3.2
  | | `-- punycode@1.4.1
  | +-- tunnel-agent@0.6.0
  | `-- uuid@3.0.1
  +-- rivescript@1.17.1
  | +-- fs-readdir-recursive@1.0.0
  | `-- rsvp@3.5.0
  +-- sanitize-filename@1.6.1
  | `-- truncate-utf8-bytes@1.0.2
  |   `-- utf8-byte-length@1.0.4
  +-- smooch-core@2.1.1
  | +-- form-data@0.2.0
  | | +-- async@0.9.2
  | | +-- combined-stream@0.0.7
  | | | `-- delayed-stream@0.0.5
  | | `-- mime-types@2.0.14
  | |   `-- mime-db@1.12.0
  | +-- isomorphic-fetch@2.2.0
  | | +-- node-fetch@1.6.3
  | | | +-- encoding@0.1.12
  | | | | `-- iconv-lite@0.4.15
  | | | `-- is-stream@1.1.0
  | | `-- whatwg-fetch@2.0.3
  | `-- jsonwebtoken@5.4.1
  |   `-- jws@3.1.4
  |     +-- base64url@2.0.0
  |     `-- jwa@1.1.5
  |       +-- buffer-equal-constant-time@1.0.1
  |       `-- ecdsa-sig-formatter@1.0.9
  +-- speakeasy-nlp@0.2.12
  | `-- levenshtein@1.0.5
  +-- underscore@1.8.3
  `-- underscore.string@3.3.4
    +-- sprintf-js@1.0.3
    `-- util-deprecate@1.0.2

npm WARN enoent ENOENT: no such file or directory, open '/root/.node-red/package.json'
npm WARN .node-red No description
npm WARN .node-red No repository field.
npm WARN .node-red No README data
npm WARN .node-red No license field.

this is the outpot of installation

**Comment by vincenzo85** [comment]
root@v9069:~# cd ./
.cache/       .node-gyp/    .npm/
.nano/        .node-red/    node_modules/
root@v9069:~# cd ./.node-red/
root@v9069:~/.node-red# npm install node-red-contrib-chatbot
npm ERR! Linux 4.4.49-1-pve
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-contrib-chatbot"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! file /root/.node-red/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, only a whitespace at 2:1
npm ERR!
npm ERR! ^
npm ERR! File: /root/.node-red/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log

**Comment by vincenzo85** [comment]
root@v9069:~# cd ./
.cache/       .node-gyp/    .npm/
.nano/        .node-red/    node_modules/
root@v9069:~# cd ./.node-red/
root@v9069:~/.node-red# npm install node-red-contrib-chatbot
npm ERR! Linux 4.4.49-1-pve
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-contrib-chatbot"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! file /root/.node-red/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, only a whitespace at 2:1
npm ERR!
npm ERR! ^
npm ERR! File: /root/.node-red/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log

**Comment by guidone** [comment]
Sorry @vincenzo85 what is the problem exactly?

**Comment by vincenzo85** [comment]
Issue solved I write a blank file package.json

**Comment by guidone** [comment]
👍
