### ISSUE TITLE
duplicates messages

### ISSUE THREAD

**Issue by gabbiano83** [guidone/node-red-contrib-chatbot#77]
Hi,

I really don't understand if this is a specific issue of this contrib plugin, but designing a simple flow like this:

And send /help command, I got sometimes 2, sometimes 3 identical return messages
![immagine](https://cloud.githubusercontent.com/assets/26217851/26667665/8e40c2c0-46a6-11e7-927f-4106350aa314.png)

Someone have ideas?

I've changed my server unchanging workflow, and even adding a 1 sec delay issue still persist

EDIT: I've just noticed that from 1 phone carrier issue does not appear, even from my telegram on PC.
On work phone (other carrier) the issue is present

It appears like a network issue, but do you have some ideas about how to mitigate?
Could I think to limit rate of messages and drop intermediate? Is safe? Taking message limit per second and flagging "drop intermediate" could i lose some single messages?

EDIT2: Using this node: https://github.com/peterstrapp/node-red-contrib-deduplicate I've solved the issue I think could be safer way

**Comment by guidone** [comment]
@gabbiano83 it never happened to me and I've never heard, which carrier is it?
Can we consider closed the issue?

**Comment by gabbiano83** [comment]
Yes, you can close, I think it was a networking issue and not related to node-red
Thanks
