### ISSUE TITLE
deprecated node-telegram-bot-api usage?

### ISSUE THREAD

**Issue by mrummuka** [guidone/node-red-contrib-chatbot#79]
Noted this on logs.

Sat, 03 Jun 2017 17:23:50 GMT node-telegram-bot-api deprecated `options.polling.timeout` is deprecated. Use `options.polling.params` instead. at ../../usr/local/lib/node_modules/node-red-contrib-cha
tbot/node_modules/node-telegram-bot-api/lib/telegram.js:304:25

**Comment by guidone** [comment]
@mrummuka you're right, fixed in `0.7.1`
