### ISSUE TITLE
telegram: save voice message to file

### ISSUE THREAD

**Issue by gabbiano83** [guidone/node-red-contrib-chatbot#83]
Is it possible to save audio message received on telegram via mic phone message to a wav or flac file?

How?

Using sample telegram receive node I got message with msg.payload.type = "voice" but how I can save this as .wav or mp3 or flac file?

**Comment by guidone** [comment]
Yes, you can connect a `Parse node` and select the audio type from the combobox, that will transform the payload into something that node-red is ready to understand, in that case a file buffer. If you connect the parse node to the a file node it will save the buffer into a file.

**Comment by gabbiano83** [comment]
It works correctly with image file, but not with audio message....
With audio format it appears no message output returned from parse node

**Comment by guidone** [comment]
Ok, I'll try and fix it

**Comment by gabbiano83** [comment]
Thanks Guido, we really appreciate your help and support
Matteo

**Comment by guidone** [comment]
@gabbiano83 fixed in 0.7.2, was totally missing the code to handle upload of document, audio and videos
