### ISSUE TITLE
Facebook receiver without output

### ISSUE THREAD

**Issue by rdricco** [guidone/node-red-contrib-chatbot#84]
Almost the same issue as the #57 & #61, but I have body-parser installed and the webhook is subscribed to the page events. Any idea?

**Comment by guidone** [comment]
If you manually call

https://<your-public-address>/redbot/facebook/test

do you see something in the console? do you see something with the debug node in node-red?

**Comment by rdricco** [comment]
Both results from /redbot/facebook/test and /redbot/facebook/_status are: {"status":"ok"}

Debug node didn't print any message. (Tried using the redbot-debug node too)

This is what i got on bluemix log when receiving a message:

```
RTR/0

{{mypublicaddress}} - [2017-06-27T08:23:51.691+0000] "POST /redbot/facebook HTTP/1.1" 200 511 15 "-" "-" "192.155.237.114:32322" "192.155.243.38:60899" x_forwarded_for:"173.252.90.240" x_forwarded_proto:"https" vcap_request_id:"1c36da28-3418-4a7f-54bc-0e14f6f91567" response_time:0.003210455 app_id:"9063a36b-b90c-4531-b64e-29aa997a4cde" app_index:"0" x_global_transaction_id:"81623540" x_b3_traceid:"0502f78389e5aec7" x_b3_spanid:"0502f78389e5aec7" x_b3_parentspanid:"-"
```

**Comment by guidone** [comment]
@rdricco thanks, I'll try with this boilerplate and try to add some debug/warning message and resolve this problem for good

**Comment by rdricco** [comment]
Nice. I tried on heroku using this "Button" too and have the same results.

**Comment by guidone** [comment]
Does it work locally?

I tried locally with this

https://github.com/ibmets/node-red-bluemix-starter/blob/master/index.js

and it works, I'm able to receive the payload. Can you check if in the configuration panel on `Facebook Receiver` you have just one you have just one configuration with the same token.

It happened a couple of times that with a double bot with the same token it was not able to forware the message correctly to the nodes

**Comment by rdricco** [comment]
I don't know why but it's working now. I had a error when starting my node-red and need to reinstall the chatbot node, after this worked on first test. Thank you anyway.
