### ISSUE TITLE
Can you set a phone-call button?

### ISSUE THREAD

**Issue by Alessandro1992** [guidone/node-red-contrib-chatbot#86]
Hi @guidone, recently i'm working with the redbot tool but i couldn't find if there is a way to set the button node to iniciate a phone call like this https://developers.facebook.com/docs/messenger-platform/send-api-reference/call-button. Thanks for your help.

**Comment by guidone** [comment]
@Alessandro1992 Yes, it's missing, I'll work on it

**Comment by Alessandro1992** [comment]
Thanks @guidone, it will be a good enhancement.

**Comment by guidone** [comment]
Hi @Alessandro1992 I'm working on this, you can try it in beta installing this

`npm install node-red-contrib-chatbot@0.8.0-beta-1`

It will be merged in few days

**Comment by Alessandro1992** [comment]
Ok, thanks!

**Comment by guidone** [comment]
This is merged in 0.8.0
