### ISSUE TITLE
No response from bot

### ISSUE THREAD

**Issue by Hostile** [guidone/node-red-contrib-chatbot#89]
Hi, followed all steps
Created flow but not geting any response from bot

What it can be ?

How do I put my username?   as @username or username?

http://i.imgur.com/dTwmRp9.png

http://i.imgur.com/DbYlIhM.png

http://i.imgur.com/9BTa5go.png

**Comment by fpsimonee** [comment]
@Hostile Hi man, you need to connect the nodes to send the messages with the redbot. To test your Robot, at least on facebook, I do not need to add anything in the Users field. Only configurate a testers and Developers on Facebook Developers console. 
![screenshot from 2017-07-05 14 03 16](https://user-images.githubusercontent.com/11202288/27875756-b9fe8218-618a-11e7-9cb5-2fdc6fe46559.png)

**Comment by Hostile** [comment]
Thank u.
Sorry for asking here in issues.
Hiw do I connect dots ?

**Comment by Hostile** [comment]
@fpsimonee thanks, doing it first time
got response now :)
