### ISSUE TITLE
Bug: Rivescript assumes error when global debug true

### ISSUE THREAD

**Issue by TotallyInformation** [guidone/node-red-contrib-chatbot#94]
If you use `! global debug = true` in a rivescript, the node shows a status of "parsing errors" even if the script is valid.

I think this is because the debug output uses `node.error`.

**Comment by guidone** [comment]
@TotallyInformation Ok, makes sense, I'll fix using the normal debug

**Comment by guidone** [comment]
fixed in 0.7.4
