### ISSUE TITLE
missing chatbot-analyze

### ISSUE THREAD

**Issue by fragolinux** [guidone/node-red-contrib-chatbot#97]
hi, i installed node-red-contrib-chatbot and when i start manually node-red via node-red-start, it complains about a missing module:

28 Jul 17:11:57 - [warn] Missing node modules:
28 Jul 17:11:57 - [warn]  - node-red-contrib-chatbot (0.7.4): chatbot-analyze

but i can't find such a node... can you address me on how to solve, or bypass this warning? Thanks

**Comment by guidone** [comment]
Yes, this node was deprecated a while ago, too low level, basically replaced by listen node and language node. How are you using it?

**Comment by fragolinux** [comment]
actually just installed with Peter Scargill's Script, plan to play with it during vacations :)
so that warning can be ignored? or can you update to point to the correct nodes?
thanks

**Comment by guidone** [comment]
Ok thanks, I think this script has an old flow, you should see a dashed node (means it's in the configuration but the node doesn't exist anymore) you can safely delete it
