### ISSUE TITLE
Facebook Receiver is not getting voice notes

### ISSUE THREAD

**Issue by alex0520** [guidone/node-red-contrib-chatbot#98]
Hello, I'm trying to use the Facebook receiver node, it works well with video and text messages, but  when I send a voice note, the receiver node is not getting fired, I am using ngrok, so I see that the request is there, but nothing happens in my flow, could you help me? thanks!

> {
    "object": "page",
    "entry": [
        {
            "id": "1507595379263575",
            "time": 1501256247170,
            "messaging": [
                {
                    "sender": {
                        "id": "1994375427246619"
                    },
                    "recipient": {
                        "id": "1507595379263575"
                    },
                    "timestamp": 1501256246940,
                    "message": {
                        "mid": "mid.$cAAUB0iUrh6Zjux2unFdidhjdNedE",
                        "seq": 113942,
                        "attachments": [
                            {
                                "type": "audio",
                                "payload": {
                                    "url": "https://cdn.fbsbx.com/v/t59.3654-21/20036905_801639886683602_5493332913262952448_n.mp4/audioclip-1501256246000-2560.mp4?oh=220f8d374e2c1ac44c1cb5f0873efa80&oe=597D313D"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    ]
}

**Comment by alex0520** [comment]
I figured out that there is not support for audio files, so I added it, here is the pull request  #99

**Comment by guidone** [comment]
Perfect! Thank you very much for the contribution, I'merging it
